import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Timing & Silence (Moves 43–48). */
export const TIMING: MoveInput[] = [
  {
    id: "mv_043", number: 43, slug: "use-the-pause", title: "Use the Pause",
    summary: "Take deliberate time before responding to a surprising offer or demand, so your answer comes from judgement rather than reflex.",
    category: "timing", situations: ["offer", "difficult_conversation", "pricing", "escalation"],
    goals: ["de_escalate", "clarity"], channels: ["in_person", "phone", "email", "chat"],
    relationships: ["client", "employer", "manager", "colleague", "vendor"], urgency: ["today"],
    principle: "The quality of a reply depends heavily on how long you waited to give it.",
    whyItWorks: "Pressure narrows thinking and pushes people to agree or retaliate. A short, stated pause — 'let me think about that' — interrupts the reflex, buys time to check facts and signals you are not easily rushed. Most deadlines can absorb a day.",
    whenToUse: ["You receive an unexpected offer, demand or criticism.", "You feel a strong urge to respond immediately."],
    whenNotToUse: ["A genuine emergency requires an immediate decision.", "Delay would be read as evasion after you already promised a quick answer."],
    signals: ["Your heart rate is up and you are drafting a reply in your head.", "The other side is pressing for an instant yes."],
    preparation: ["Have a standard phrase ready for asking for time.", "Know your usual reasonable delay (an hour, a day)."],
    steps: ["Acknowledge what was said.", "Ask for a specific amount of time.", "Use the time to check facts and your walk-away point.", "Reply at the promised time."],
    openingLine: "Thank you — I'd like to think about that properly. Can I come back to you tomorrow morning?",
    scripts: {
      default: "Thanks for laying that out. I'd like to take until tomorrow at ten to give you a considered answer.",
      diplomatic: "I appreciate you sharing this. It deserves a proper response, so may I take until tomorrow morning to think it through?",
      direct: "I'll respond tomorrow at ten.",
      firm: "I don't make decisions like this on the spot. You'll have my answer tomorrow at ten.",
      written: "Thank you for the revised terms. I want to give them proper consideration, so I'll reply by 10am tomorrow. If anything in the timing is critical on your side, let me know.",
      message: "Thanks — let me think it over. I'll reply by 10am tomorrow.",
    },
    reactions: [
      { ifThey: "insist on an answer now", counter: "Ask what makes it urgent. If the reason is real, decide; if not, restate your time." },
      { ifThey: "add pressure with an expiring offer", counter: "Ask whether the deadline is firm and, if so, decide against your prepared limits." },
    ],
    secondMove: "If the pressure is artificial, use Slow Down Artificial Urgency.",
    followUp: "Reply exactly when you said you would; reliability makes future pauses easier.",
    mistakes: ["Pausing without saying when you will reply.", "Using the pause to avoid deciding at all."],
    ethicalBoundary: "Pause to think, not to manipulate. Strategic silence designed to make someone anxious is not the same as taking time.",
    risk: "low", walkAway: ["They withdraw the offer simply because you asked for a day, suggesting the pressure was the strategy."],
    example: "A supplier phoned a shop owner with a 'today only' bulk price. She asked for a day, checked her stock data and realised she didn't need the volume. The supplier offered the same price the following week.",
    related: ["mv_046", "mv_019", "mv_075"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_044", number: 44, slug: "dont-fill-the-silence", title: "Don't Fill the Silence",
    summary: "After you make a request or state a price, stay quiet and let the other side respond, rather than rushing in with concessions.",
    category: "timing", situations: ["pricing", "compensation", "offer"],
    goals: ["protect_value", "negotiate_terms"], channels: ["in_person", "phone", "video"],
    relationships: ["client", "employer", "vendor"], urgency: ["today"],
    principle: "Silence after an ask belongs to the other side; filling it gives away your position.",
    whyItWorks: "Silence is uncomfortable, and people instinctively fill it — often with qualifiers, discounts or retractions. Holding still for a few seconds lets the other person think and respond to your actual proposal, and often prompts them to offer information or acceptance.",
    whenToUse: ["You have just stated a price, salary request or condition.", "The other side goes quiet after hearing your proposal."],
    whenNotToUse: ["The silence is caused by confusion and needs clarification.", "In written channels, where silence works differently; follow up appropriately instead."],
    signals: ["You often add 'but we could…' immediately after an ask.", "You feel relief only when the other person speaks."],
    preparation: ["Practise stating a request and counting silently to ten.", "Decide that your next words, if any, will be a question, not a concession."],
    steps: ["Make the request clearly.", "Stop speaking.", "Hold eye contact or stay calmly present for up to ten seconds.", "If needed, ask a question rather than softening the proposal."],
    openingLine: "Based on everything we've discussed, I'm asking for a 10% increase.",
    scripts: {
      default: "I'm asking for a base of 85,000. [Pause.]",
      diplomatic: "Given what we've covered, I'd like to ask for 85,000. [Pause.] What are your thoughts?",
      direct: "I'm asking for 85,000. [Pause.]",
      firm: "My request is 85,000. [Pause.]",
      written: "Thank you for the discussion today. As mentioned, I'm requesting a base salary of 85,000 effective from the next review period. I look forward to hearing your thoughts.",
      message: "As discussed, I'm requesting 85k base. Look forward to your thoughts.",
    },
    reactions: [
      { ifThey: "stay silent too", counter: "After ten seconds, ask 'How does that sit with you?' rather than lowering the request." },
      { ifThey: "respond with an objection", counter: "Listen fully, then respond to the objection's substance." },
    ],
    secondMove: "If an objection arrives, use Label the Objection.",
    followUp: "In written settings, follow up after a reasonable period rather than sending immediate clarifications.",
    mistakes: ["Filling silence with self-deprecating jokes.", "Using silence aggressively as a stare-down."],
    ethicalBoundary: "Silence should give space, not intimidate. Holding a hostile stare to unsettle someone crosses into pressure.",
    risk: "low", walkAway: ["Silence is met with repeated attempts to make you retract the request without discussion."],
    example: "A nurse requesting a schedule change stated her ask and waited. After a long pause, her manager said 'I think we can do Tuesdays' — more than she had planned to settle for.",
    related: ["mv_032", "mv_043", "mv_056"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_045", number: 45, slug: "set-a-response-window", title: "Set a Response Window",
    summary: "Give a clear, reasonable date by which you need an answer, so an open question does not drift indefinitely.",
    category: "timing", situations: ["follow_up", "offer", "commitment", "vendor"],
    goals: ["gain_commitment", "clarity"], channels: ["email", "phone", "chat"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["this_week"],
    principle: "An offer without a timeline is a wish.",
    whyItWorks: "Open-ended proposals compete with every other priority and usually lose. A specific, explained response date gives the other side a reason to decide, lets you plan, and makes it legitimate to follow up or move on without seeming impatient.",
    whenToUse: ["You have sent a proposal or offer and need to plan around the answer.", "Previous proposals with this counterpart have gone quiet."],
    whenNotToUse: ["The counterpart has explained a legitimate longer decision process.", "Setting a date would feel coercive in a sensitive personal context."],
    signals: ["Proposals sit unanswered for weeks.", "You are holding capacity for a client who has not committed."],
    preparation: ["Choose a date that is reasonable for their process.", "Have a real reason for the date (capacity, pricing validity, start date)."],
    steps: ["State the response date with its reason.", "Offer to answer questions before then.", "Follow up once shortly before the date.", "Act on the date: release capacity or proceed."],
    openingLine: "To hold the start date for you, I'd need to know by Thursday.",
    scripts: {
      default: "To hold the March start for you, I'd need confirmation by Thursday the 9th. After that I'll open the slot to other clients.",
      diplomatic: "I'd love to keep March open for you. Would Thursday the 9th work as a decision date? I'm happy to answer questions before then.",
      direct: "I need your answer by Thursday the 9th to hold March.",
      firm: "The March slot is held until Thursday the 9th. After that it's released.",
      written: "Thank you for considering the proposal. To keep the March start date available, I'd need your confirmation by Thursday the 9th. If you have questions before then, I'm happy to set up a call. If the timing doesn't work, let me know and we can look at April.",
      message: "Quick note: can hold March for you until Thu the 9th. Any questions before then?",
    },
    reactions: [
      { ifThey: "ask for more time", counter: "Ask what they need to decide and agree a new, specific date." },
      { ifThey: "miss the date", counter: "Release the slot as stated and let them know politely." },
    ],
    secondMove: "If the window passes in silence, use Follow Up After Silence.",
    followUp: "Send one reminder two days before the deadline.",
    mistakes: ["Setting a deadline with no consequence and then ignoring it.", "Choosing an unreasonably short window."],
    ethicalBoundary: "Deadlines must be real. Fabricated urgency ('only two slots left') when untrue is manipulation.",
    risk: "low", walkAway: ["Repeated windows pass without response or explanation."],
    example: "A consultant who usually waited weeks on proposals began adding 'I can hold this start date until Friday'. Her average response time fell from three weeks to five days.",
    related: ["mv_048", "mv_065", "mv_084"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_046", number: 46, slug: "slow-down-artificial-urgency", title: "Slow Down Artificial Urgency",
    summary: "When someone pushes for an instant decision without a clear reason, calmly ask what drives the deadline before you commit.",
    category: "timing", situations: ["offer", "vendor", "pricing", "escalation"],
    goals: ["protect_value", "clarity"], channels: ["phone", "in_person", "email", "chat"],
    relationships: ["vendor", "client", "employer"], urgency: ["today"],
    principle: "Urgency the other side created is urgency they can usually relax.",
    whyItWorks: "Exploding offers and 'decide today' pressure exploit fear of loss. Asking what the deadline depends on separates real constraints from tactics. Genuine deadlines survive the question; artificial ones tend to soften once you show you will not be rushed.",
    whenToUse: ["You are told an offer expires within hours.", "You feel rushed and cannot identify why the timing matters."],
    whenNotToUse: ["The deadline is clearly real and documented (for example a tender closing).", "You have already done your analysis and are ready to decide."],
    signals: ["The deadline arrives with no explanation.", "Pressure increases as you ask questions."],
    preparation: ["Know your walk-away point before the call.", "Prepare a neutral question about the deadline."],
    steps: ["Acknowledge the timing they mentioned.", "Ask what the deadline is tied to.", "State when you can realistically decide.", "Decide based on your criteria, not the countdown."],
    openingLine: "I understand there's time pressure. What's the deadline tied to?",
    scripts: {
      default: "I hear the offer expires today. What's driving that date? I can give you an answer by Friday.",
      diplomatic: "I appreciate you letting me know about the timing. Could you help me understand what's behind today's deadline? I want to decide well, not quickly.",
      direct: "What makes today the deadline? I can decide by Friday.",
      firm: "I don't decide under same-day pressure. If the offer stands until Friday, I'll give you an answer then.",
      written: "Thanks for the offer. I noticed it's marked as valid until end of day. I'm interested, but I need until Friday to review it properly. Could you let me know whether the deadline is fixed, and if so, what it relates to?",
      message: "Interested — but need till Friday. Is today's deadline fixed?",
    },
    reactions: [
      { ifThey: "give a real reason", counter: "Take it seriously and decide within the real constraint." },
      { ifThey: "extend without explanation", counter: "Note it as a signal; the urgency was likely a tactic. Use the time." },
      { ifThey: "withdraw the offer", counter: "Accept it; a deal that cannot survive one day of consideration is often not worth taking." },
    ],
    secondMove: "With the pressure reduced, use Use the Pause to consider fully.",
    followUp: "Record the pattern; counterparts who manufacture urgency usually repeat it.",
    mistakes: ["Assuming every deadline is fake.", "Responding sarcastically to the pressure."],
    ethicalBoundary: "Respect genuine deadlines and do not use this Move to stall in bad faith when a real decision is due.",
    risk: "low", walkAway: ["The counterpart continues to manufacture deadlines after being asked directly."],
    example: "A car salesperson said a discount ended at closing. The buyer asked what it was tied to; the answer was 'monthly targets'. She came back the next week and received the same price.",
    related: ["mv_043", "mv_019", "mv_020"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_047", number: 47, slug: "choose-the-moment", title: "Choose the Moment",
    summary: "Raise important requests at a time when the other person has the attention, information and authority to respond well.",
    category: "timing", situations: ["compensation", "promotion", "difficult_conversation", "leadership_alignment"],
    goals: ["gain_commitment", "negotiate_terms"], channels: ["in_person", "video", "email"],
    relationships: ["manager", "employer", "client", "colleague"], urgency: ["this_week", "exploring"],
    principle: "A good request at a bad moment is a bad request.",
    whyItWorks: "The same ask can succeed or fail depending on context: budget cycles, workload, recent events and mood. Choosing a moment when the decision-maker can focus — and has just seen your value — removes obstacles unrelated to the merits of your request.",
    whenToUse: ["You are planning a significant request such as a raise or new role.", "Previous attempts were brushed off because of timing."],
    whenNotToUse: ["Waiting for the perfect moment has become avoidance.", "The issue is urgent, such as a safety or ethical concern."],
    signals: ["You plan to raise it 'at the end of the meeting' or in passing.", "The decision-maker is in the middle of a crisis."],
    preparation: ["Find out when decisions of this kind are made (budget cycles, planning).", "Request a dedicated time rather than raising it ad hoc."],
    steps: ["Identify the decision calendar.", "Request a specific meeting with a clear topic.", "Hold it after, not before, a visible success if possible.", "Avoid days of known stress for the decision-maker."],
    openingLine: "Could we find 30 minutes next week to discuss my role? I'd like to give it proper time.",
    scripts: {
      default: "Could we set aside 30 minutes before budgets close next month to discuss my compensation?",
      diplomatic: "I know things are busy with the launch. Once it's done, could we find a time to talk about my next step here?",
      direct: "I'd like 30 minutes before budget close to discuss compensation.",
      firm: "This needs a dedicated conversation before budgets close. Can we book it this week?",
      written: "Hi Tom — I'd like to schedule 30 minutes to discuss my compensation and role, ideally before budgets are finalised at the end of the month. Would Tuesday or Wednesday next week work?",
      message: "Could we book 30 min before budget close to talk about my role and comp?",
    },
    reactions: [
      { ifThey: "postpone repeatedly", counter: "Ask them to name a date; then use Set a Response Window." },
      { ifThey: "ask what it's about", counter: "Be honest and brief; surprise rarely helps." },
    ],
    secondMove: "In the meeting, use Strengthen Your Position Before Asking to lead with evidence.",
    followUp: "Send a calendar invite with the topic stated.",
    mistakes: ["Ambushing the person in a corridor.", "Raising it immediately after bad news for the team."],
    ethicalBoundary: "Timing should enable a fair decision, not exploit someone's vulnerable moment or distraction.",
    risk: "low", walkAway: ["The decision-maker refuses to make time for the conversation over several months."],
    example: "An engineer had twice mentioned a raise at the end of standups. He instead booked a meeting the week after his feature launched and before budgets closed; the raise was approved.",
    related: ["mv_022", "mv_005", "mv_016"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_048", number: 48, slug: "follow-up-after-silence", title: "Follow Up After Silence",
    summary: "When a client or counterpart goes quiet, send a short, low-pressure follow-up that makes replying easy and offers a clear exit.",
    category: "timing", situations: ["follow_up", "client_scope", "offer", "commitment"],
    goals: ["gain_commitment", "clarity"], channels: ["email", "text", "chat"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["this_week"],
    principle: "Silence is usually a priority problem, not a verdict — make it easy to answer.",
    whyItWorks: "People go quiet because they are busy, undecided or uncomfortable saying no. A brief message that summarises the open point, offers simple response options and permits a 'no' lowers the effort of replying and often restarts the conversation or brings honest closure.",
    whenToUse: ["A client stopped replying after a proposal or meeting.", "A hiring process has gone quiet past the promised date."],
    whenNotToUse: ["You have already followed up several times; consider closing instead.", "The silence follows a conflict that needs repair first."],
    signals: ["Two weeks or more without reply to a time-sensitive question.", "You are drafting increasingly long follow-ups."],
    preparation: ["Summarise the open question in one sentence.", "Offer two or three easy reply options."],
    steps: ["Reference the original topic briefly.", "Offer simple choices including 'not now'.", "Keep it under five sentences.", "If no reply, send one final close-the-loop message after a set period."],
    openingLine: "Just checking in on the proposal — a quick one-word reply is fine.",
    scripts: {
      default: "Hi Ben — checking in on the proposal from the 3rd. Is it (a) still under consideration, (b) a go, or (c) not right for now? Any answer helps me plan.",
      diplomatic: "Hi Ben — I know things get busy. Just checking whether the proposal is still of interest. If the timing isn't right, that's completely fine to say.",
      direct: "Is the proposal still under consideration?",
      firm: "I'll assume the proposal isn't moving forward unless I hear by Friday.",
      written: "Hi Ben — following up on the proposal I sent on the 3rd. To help me plan the next quarter, could you let me know whether it's (a) still being considered, (b) ready to go ahead, or (c) not right at the moment? A one-letter reply is perfect. If it's (c), no problem at all — I'd be glad to reconnect later.",
      message: "Hi Ben — quick check on the proposal: a) still deciding, b) go, c) not now?",
    },
    reactions: [
      { ifThey: "reply 'not now'", counter: "Thank them, ask whether you can check back in a set number of months, and close gracefully." },
      { ifThey: "still don't reply", counter: "Send one final message closing the loop and stop following up." },
    ],
    secondMove: "If silence continues after the final message, use Step Back Without Burning the Bridge.",
    followUp: "Log the date of each follow-up so you stop after two or three.",
    mistakes: ["Guilt-tripping language like 'I haven't heard back from you'.", "Following up daily."],
    ethicalBoundary: "Respect a non-answer after reasonable attempts. Persistent chasing after clear disinterest becomes harassment.",
    risk: "low", walkAway: ["Two or three follow-ups over several weeks receive no reply at all."],
    example: "A freelancer's multiple-choice follow-up got a reply within an hour: '(a) — budget approval is next week'. Her previous three open-ended emails had received no answer.",
    related: ["mv_045", "mv_086", "mv_065"], access: "free", editorial: DRAFT_EDITORIAL,
  },
];
