import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Exit & Recovery (Moves 85–90). */
export const EXIT: MoveInput[] = [
  {
    id: "mv_085", number: 85, slug: "decide-your-exit-before-you-need-it", title: "Decide Your Exit Before You Need It",
    summary: "Write down, while calm, the specific conditions under which you would leave a deal, client or role, so the decision is not made in panic.",
    category: "exit", situations: ["walk_away", "client_scope", "partnership"],
    goals: ["decide_walk_away", "clarity"], channels: ["in_person", "email"],
    relationships: ["client", "employer", "partner", "vendor"], urgency: ["exploring"],
    principle: "Exit conditions written in calm protect you from decisions made in heat.",
    whyItWorks: "In the middle of stress, it is hard to tell whether to leave or persist. Defining exit conditions in advance — specific, observable triggers — makes the decision clearer, prevents both premature exits and staying too long, and lets you engage fully until a trigger is met.",
    whenToUse: ["You are starting a new client, role or partnership.", "You feel uneasy about a relationship but cannot say why."],
    whenNotToUse: ["You are already certain you need to leave.", "Exit planning would distract you from a short, fixed engagement."],
    signals: ["You have stayed in difficult situations longer than you should have before.", "You are unsure what would make you leave."],
    preparation: ["List three specific conditions that would make you leave.", "Note how you would leave if a condition is met."],
    steps: ["Write the conditions privately.", "Review them monthly.", "When a condition is met, take a day to confirm.", "Act on the decision calmly."],
    openingLine: "I've set myself clear conditions for this engagement, so I can commit fully until they're met.",
    scripts: {
      default: "My conditions for continuing: payment within 45 days, no more than one major scope change per quarter, and respectful communication. If two are broken, I'll plan an exit.",
      diplomatic: "To give this partnership my full commitment, I find it helps to be clear with myself about what makes it work. I'd like us to agree payment within 45 days and a quarterly scope review.",
      direct: "Payment beyond 45 days or repeated scope changes would end this for me.",
      firm: "If payment exceeds 45 days again, I will end the engagement.",
      written: "Private note — exit conditions for the Lancaster engagement: (1) invoices paid more than 45 days late twice; (2) more than one unpriced scope change per quarter; (3) disrespectful communication after it has been raised once. If any two occur, I'll give 30 days' notice in line with the contract.",
      message: "Note to self: exit if 2 of 3 conditions hit — late pay, unpriced scope, disrespect.",
    },
    reactions: [
      { ifThey: "meet all conditions", counter: "Commit fully; the conditions were for clarity, not distrust." },
      { ifThey: "breach a condition", counter: "Raise it once directly; if it repeats, follow your plan." },
    ],
    secondMove: "When a condition is met, use Step Back Without Burning the Bridge.",
    followUp: "Review and update the conditions each quarter.",
    mistakes: ["Setting vague conditions like 'if it gets bad'.", "Ignoring conditions once they are met."],
    ethicalBoundary: "Respect contractual notice periods when exiting. Leaving abruptly in breach of agreements harms others and may carry liability.",
    risk: "low", walkAway: ["Two or more written exit conditions are met."],
    example: "A consultant set three exit conditions for a difficult client. Six months in, two were met. She gave notice calmly and replaced the income within two months, rather than staying a year.",
    related: ["mv_019", "mv_086", "mv_004"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_086", number: 86, slug: "step-back-without-burning-the-bridge", title: "Step Back Without Burning the Bridge",
    summary: "Decline or end a deal in a calm, professional way that leaves the door open for future work or references.",
    category: "exit", situations: ["walk_away", "offer", "client_scope", "partnership"],
    goals: ["decide_walk_away", "recover_relationship"], channels: ["email", "phone", "in_person"],
    relationships: ["client", "employer", "partner", "vendor"], urgency: ["today", "this_week"],
    principle: "How you leave is remembered longer than why.",
    whyItWorks: "Industries are smaller than they seem, and people move. A graceful exit — thanking them, stating the decision plainly and offering a clean transition — protects your reputation, preserves the chance of future work and avoids the regret of a dramatic departure.",
    whenToUse: ["You have decided to decline an offer or end an engagement.", "The relationship has value even if this deal does not."],
    whenNotToUse: ["The other side has acted unethically and a formal exit is needed.", "You have not actually decided and are using this to pressure them."],
    signals: ["You feel tempted to explain all their faults on the way out.", "You may want to work with them, or people they know, again."],
    preparation: ["Write a short message: thanks, decision, transition.", "Decide what you will offer to make the exit smooth."],
    steps: ["Thank them sincerely.", "State the decision clearly.", "Offer a practical transition or referral.", "Close warmly and do not relitigate."],
    openingLine: "Thank you for the opportunity. I've decided to step back, and I want to do it well.",
    scripts: {
      default: "Thank you for the offer and the conversations. I've decided not to accept. I've enjoyed getting to know the team and hope our paths cross again.",
      diplomatic: "I'm really grateful for your time and the offer. After careful thought, I've decided it isn't the right fit for me at this point. I'd love to stay in touch.",
      direct: "Thank you, but I've decided not to accept.",
      firm: "I've decided to end the engagement at the end of this month, in line with our notice period.",
      written: "Hi Kim — thank you for the time you and the team have invested in these conversations. After careful consideration, I've decided not to accept the offer. This was a difficult decision, and it reflects fit and timing rather than anything about the team. I'd be glad to stay in touch, and I'm happy to recommend people who might be a strong fit.",
      message: "Thanks so much for the offer — I've decided to decline, but would love to stay in touch.",
    },
    reactions: [
      { ifThey: "try to change your mind", counter: "Thank them and restate the decision; avoid reopening negotiation unless you genuinely want to." },
      { ifThey: "react badly", counter: "Stay courteous and do not respond in kind." },
    ],
    secondMove: "If you are ending active work, use Hand Over Cleanly.",
    followUp: "Send a short thank-you note after the transition is complete.",
    mistakes: ["Listing grievances on the way out.", "Leaving without a clear transition."],
    ethicalBoundary: "Exit honestly and in line with your commitments and notice periods.",
    risk: "low", walkAway: ["You have decided to leave and the relationship no longer serves either side."],
    example: "A designer declined a full-time offer with a gracious note and two referrals. A year later, the same company hired her for a well-paid freelance project.",
    related: ["mv_085", "mv_088", "mv_048"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_087", number: 87, slug: "pause-instead-of-quitting", title: "Pause Instead of Quitting",
    summary: "When a relationship or project is under strain, propose a defined pause or reduced commitment rather than an all-or-nothing exit.",
    category: "exit", situations: ["walk_away", "partnership", "client_scope", "boundary"],
    goals: ["decide_walk_away", "set_boundary", "recover_relationship"], channels: ["email", "in_person", "video"],
    relationships: ["client", "partner", "employer"], urgency: ["this_week"],
    principle: "Between staying as you are and leaving altogether there is usually a third option.",
    whyItWorks: "Under strain, people often see only two choices: endure or quit. A defined pause — fewer hours, a break between phases, a shorter engagement — relieves pressure, tests whether the issue is temporary and keeps value for both sides that a full exit would destroy.",
    whenToUse: ["You are exhausted or frustrated but the relationship has value.", "Circumstances may improve with time."],
    whenNotToUse: ["The problem is fundamental and a pause would only delay the inevitable.", "The other side's behaviour is unacceptable and must end."],
    signals: ["You are considering quitting after a single bad period.", "Both sides are frustrated but the work still matters."],
    preparation: ["Define the pause: length, scope and what happens after.", "Decide what you would need to see to resume fully."],
    steps: ["Name the strain honestly.", "Propose a specific pause or reduction with dates.", "Agree how and when you will review.", "Review on the agreed date and decide."],
    openingLine: "I'd like to suggest a short pause rather than continuing as we are.",
    scripts: {
      default: "The current pace isn't sustainable for me. Could we pause new work for four weeks after the launch and then review whether to continue at the same level?",
      diplomatic: "I really want to keep working together, and I'm feeling stretched. Would a short pause after the launch help us both reset?",
      direct: "I'd like to pause new work for four weeks after launch.",
      firm: "I'm pausing new work for four weeks after launch. We'll review on the 1st.",
      written: "Hi Lou — I've valued our work together and want it to continue sustainably. I'd like to propose a four-week pause on new projects after the launch on the 3rd, with a review call on 1 July to decide how we continue. Existing commitments will be completed as planned.",
      message: "Could we pause new work for 4 weeks after launch and review on 1 July?",
    },
    reactions: [
      { ifThey: "agree", counter: "Confirm dates in writing and protect the pause." },
      { ifThey: "push back", counter: "Ask what they need during that time and see whether a reduced commitment works." },
    ],
    secondMove: "At the review, if things have not improved, use Step Back Without Burning the Bridge.",
    followUp: "Prepare a short reflection before the review.",
    mistakes: ["Pausing without an end date.", "Continuing to work during the pause."],
    ethicalBoundary: "Honour existing commitments during the pause. A pause should not leave the other side stranded mid-project.",
    risk: "low", walkAway: ["After the pause, the same issues remain unchanged."],
    example: "A part-time CFO near burnout proposed a one-month pause after year-end close. She returned refreshed, reduced to two days a week and stayed with the company for another three years.",
    related: ["mv_004", "mv_085", "mv_049"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_088", number: 88, slug: "hand-over-cleanly", title: "Hand Over Cleanly",
    summary: "When leaving a project or role, provide a clear, organised handover so the work continues and your reputation is protected.",
    category: "exit", situations: ["walk_away", "client_scope", "partnership"],
    goals: ["recover_relationship", "decide_walk_away"], channels: ["email", "video", "in_person"],
    relationships: ["client", "employer", "colleague", "partner"], urgency: ["this_week"],
    principle: "A clean handover is the last piece of work people judge you by.",
    whyItWorks: "Messy exits leave others struggling and create lasting negative impressions. A structured handover — status, documents, access, open risks — lets the work continue, reduces the chance of disputes and is often what people remember most about how you worked.",
    whenToUse: ["You are ending an engagement or moving roles.", "Someone else will take over your work."],
    whenNotToUse: ["The engagement ends with no continuing work.", "Confidentiality or legal advice restricts what you can share."],
    signals: ["Only you know where key files or passwords are.", "Your successor has not been briefed."],
    preparation: ["List all active work, files, access and contacts.", "Note open risks and decisions pending."],
    steps: ["Create a handover document.", "Walk the successor through it.", "Transfer access and remove your own as agreed.", "Offer a short post-handover check-in window."],
    openingLine: "I've prepared a handover so the transition is as smooth as possible.",
    scripts: {
      default: "I've prepared a handover doc covering current status, open risks, file locations and key contacts. Can we do a 45-minute walkthrough with Alex on Thursday?",
      diplomatic: "I want to make sure you're fully set up after I leave. I've put together a handover and I'm happy to walk through it.",
      direct: "Handover doc is ready. Walkthrough Thursday.",
      firm: "The handover will be completed by the 28th. Access will transfer that day.",
      written: "Hi team — attached is the handover document for the website project: current status, outstanding tasks, open risks (hosting renewal due 15 July), file locations, and key contacts. I've scheduled a walkthrough with Alex for Thursday at 2pm. After the 28th, I'm happy to answer quick questions by email for two weeks.",
      message: "Handover doc is in the shared folder. Walkthrough with Alex Thu 2pm.",
    },
    reactions: [
      { ifThey: "ask for ongoing support", counter: "Offer a defined, limited period, or a paid support arrangement." },
      { ifThey: "seem satisfied", counter: "Confirm the completion in writing." },
    ],
    secondMove: "After the handover, use Run the Post-Mortem for your own learning.",
    followUp: "Send a brief completion confirmation and remove your access as agreed.",
    mistakes: ["Leaving undocumented passwords or knowledge.", "Offering unlimited post-exit support."],
    ethicalBoundary: "Hand over completely and honestly, including known risks. Withholding information to make the transition difficult is unprofessional.",
    risk: "low", walkAway: ["Not applicable: complete the handover even when the relationship has soured, within your obligations."],
    example: "An agency ending a contract provided a twelve-page handover and a two-week support window. The client later referred two new customers, citing the professionalism of the exit.",
    related: ["mv_086", "mv_067", "mv_090"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_089", number: 89, slug: "recover-after-a-move-fails", title: "Recover After a Move Fails",
    summary: "When a negotiation or request does not work, acknowledge the result calmly, protect the relationship and plan your next attempt.",
    category: "exit", situations: ["relationship_repair", "compensation", "offer", "walk_away"],
    goals: ["recover_relationship", "clarity"], channels: ["in_person", "email", "video"],
    relationships: ["manager", "employer", "client", "partner"], urgency: ["today", "this_week"],
    principle: "A failed Move is information, not a verdict.",
    whyItWorks: "After a rejection, people often withdraw, sulk or overcorrect. Accepting the result gracefully, asking what would change the answer and planning a better-prepared next attempt preserves the relationship and turns failure into learning and a clearer path.",
    whenToUse: ["Your request, offer or negotiation was declined.", "You feel embarrassed or angry after a no."],
    whenNotToUse: ["The no revealed that you should leave; consider exit instead.", "Immediately pushing again would seem disrespectful."],
    signals: ["You want to avoid the person after a rejection.", "You are replaying what you should have said."],
    preparation: ["Write down what happened factually.", "Identify one thing to learn and one question to ask."],
    steps: ["Thank them for the decision.", "Ask what would change the answer in future.", "Agree a time to revisit if appropriate.", "Plan improvements before the next attempt."],
    openingLine: "Thank you for considering it. Could you help me understand what would change the answer?",
    scripts: {
      default: "Thanks for the honest answer. Could you tell me what I'd need to show for this to be a yes in six months?",
      diplomatic: "I appreciate you considering it, and I understand the decision. I'd value your view on what would make a stronger case next time.",
      direct: "What would make this a yes next time?",
      firm: "I accept the decision for now. I'd like clear criteria for when we revisit.",
      written: "Hi Pat — thank you for considering my request for promotion. I understand the decision. To make sure I'm working on the right things, could you share what you'd need to see for the next review? I'd welcome a short meeting to agree specific criteria.",
      message: "Thanks for the honest answer — could we agree what a yes would need next time?",
    },
    reactions: [
      { ifThey: "give clear criteria", counter: "Write them down, confirm them and work toward them visibly." },
      { ifThey: "are vague", counter: "Propose specific criteria and ask whether they agree." },
    ],
    secondMove: "With criteria agreed, use Strengthen Your Position Before Asking.",
    followUp: "Update them periodically on progress against the criteria.",
    mistakes: ["Withdrawing or sulking after the no.", "Repeating the same request without change."],
    ethicalBoundary: "Accept the decision respectfully. Retaliating through reduced effort or gossip damages trust and your reputation.",
    risk: "low", walkAway: ["Agreed criteria are met and the answer remains no without explanation."],
    example: "An engineer whose promotion was declined asked for written criteria. She met them over two quarters, presented the evidence and was promoted at the next cycle.",
    related: ["mv_022", "mv_090", "mv_065"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_090", number: 90, slug: "run-the-post-mortem", title: "Run the Post-Mortem",
    summary: "After any significant negotiation or conflict, review what happened, what worked and what you would change, so each experience improves the next.",
    category: "exit", situations: ["follow_up", "walk_away", "relationship_repair"],
    goals: ["clarity"], channels: ["in_person", "email"],
    relationships: ["client", "employer", "manager", "partner", "colleague"], urgency: ["exploring"],
    principle: "Experience only becomes judgement when you stop to examine it.",
    whyItWorks: "Most people move on quickly after a difficult situation and repeat the same mistakes. A short, honest review — facts, what you did, what you would change — converts experience into skill. Over time it reveals your personal patterns, which is the most useful insight of all.",
    whenToUse: ["A negotiation, conflict or major conversation has concluded.", "The outcome was surprising, good or bad."],
    whenNotToUse: ["You are still too upset to review it fairly; wait a few days.", "The review would turn into self-criticism without learning."],
    signals: ["You keep facing similar situations with similar outcomes.", "You cannot say what you would do differently."],
    preparation: ["Set aside 20 minutes within a week of the event.", "Gather notes, recaps and messages."],
    steps: ["Write what happened in facts.", "Note what worked.", "Note one or two things you would change.", "Record the lesson where you will see it before the next similar situation."],
    openingLine: "Let me take twenty minutes to look back on how that went.",
    scripts: {
      default: "Post-mortem: I anchored well and held my number. I conceded on the timeline too early. Next time, I'll trade timeline for payment terms.",
      diplomatic: "I'd love to do a quick review with you of how the project went — what worked well and what we'd change next time.",
      direct: "What worked, what didn't, what we change next time.",
      firm: "We'll hold a 30-minute review of the launch on Friday. Attendance is expected.",
      written: "Post-mortem — Brightline renewal (12 June). Outcome: renewed at +6% (target +10%). Worked: early data on results, calm response to the competitor quote. Didn't: accepted the timeline change without asking for anything in return. Change next time: prepare a list of trades in advance; use Trade, Never Concede on timeline. Lesson filed in my negotiation notes.",
      message: "Doing a quick post-mortem on the renewal — what worked and what to change.",
    },
    reactions: [
      { ifThey: "join a shared review", counter: "Focus on the process, not blame, so people speak openly." },
      { ifThey: "decline a shared review", counter: "Do it privately; the learning is still valuable." },
    ],
    secondMove: "Use the lesson to prepare with Define Success Before You Start next time.",
    followUp: "Review your post-mortem notes every few months for patterns.",
    mistakes: ["Only reviewing failures.", "Writing vague lessons like 'be better prepared'."],
    ethicalBoundary: "Keep shared reviews blame-free and protect confidential details when recording lessons.",
    risk: "low", walkAway: ["Not applicable: this Move is a learning practice rather than a negotiation."],
    example: "A sales manager began writing five-line post-mortems after each major deal. After three months she noticed she always conceded on payment terms first, changed her approach, and her average deal value rose.",
    related: ["mv_004", "mv_089", "mv_030"], access: "free", editorial: DRAFT_EDITORIAL,
  },
];
