import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Positioning & Value (Moves 25–30). */
export const POSITIONING: MoveInput[] = [
  {
    id: "mv_025", number: 25, slug: "lead-with-the-outcome", title: "Lead with the Outcome, Not the Hours",
    summary: "Describe your work by the result it produces for them, so the conversation is about value delivered rather than time spent.",
    category: "positioning", situations: ["pricing", "client_scope", "compensation"],
    goals: ["protect_value", "negotiate_terms"], channels: ["in_person", "video", "email"],
    relationships: ["client", "employer", "partner"], urgency: ["this_week", "exploring"],
    principle: "Buyers compare hours; they invest in outcomes.",
    whyItWorks: "Hours invite haggling because they are easy to count and compare. Outcomes — revenue protected, time saved, risk removed — are what the buyer actually wants. When you lead with the outcome, price is judged against that value rather than against someone cheaper per hour.",
    whenToUse: ["A client is questioning your fee by comparing hourly rates.", "You are writing a proposal or describing your role in a review."],
    whenNotToUse: ["The contract is explicitly time-and-materials and the client needs hour reporting.", "You cannot credibly connect your work to a measurable result."],
    signals: ["Questions focus on 'how long will it take' rather than 'what will we get'.", "Your proposals list tasks but never results."],
    preparation: ["Write the outcome in the client's terms: what changes for them when you finish.", "Attach one number or example that makes it concrete."],
    steps: ["Open with the outcome and why it matters to them.", "Describe the approach briefly as the route to that outcome.", "State the price as the investment for the outcome.", "If hours are raised, answer briefly and return to the result."],
    openingLine: "Let me start with what you'll have at the end of this, because that's what the fee is for.",
    scripts: {
      default: "At the end of this engagement your team will close month-end in three days instead of eight. The fee for that is 18,000.",
      diplomatic: "I'd love to start with what this changes for your team: month-end in three days rather than eight. The investment to get you there is 18,000.",
      direct: "Outcome: three-day month-end. Fee: 18,000.",
      firm: "I price on the result, not the hours. A three-day close is worth 18,000 to you, and that's the fee.",
      written: "Thank you for the conversation. In short, this project will reduce your month-end close from eight days to three, freeing roughly 40 staff hours each month. The fixed fee for the engagement is 18,000. I'd be glad to walk through the approach on a call.",
      message: "Summary: 8-day close down to 3. Fixed fee 18k. Happy to walk through it.",
    },
    reactions: [
      { ifThey: "ask how many hours it will take", counter: "Give an honest range, then note the fee is fixed to the outcome so overruns are your risk, not theirs." },
      { ifThey: "doubt the outcome", counter: "Offer a case example or a milestone check where the result is measured." },
    ],
    secondMove: "If they still push on price, use Offer Tiers, Not Discounts to give smaller outcomes at lower prices.",
    followUp: "Measure the outcome at the end and share it; it becomes evidence for the next proposal.",
    mistakes: ["Promising outcomes you cannot control.", "Reverting to hourly justification at the first objection."],
    ethicalBoundary: "Only claim outcomes you can reasonably deliver, and state assumptions. Overpromising to win the work shifts risk unfairly to the client.",
    risk: "low", walkAway: ["The client insists on paying only for hours at a rate below your floor."],
    example: "A bookkeeper repositioned her proposal from '20 hours a month' to 'monthly reports ready by the 5th'. The client stopped asking for an hourly discount and accepted a fee 25% above her previous rate.",
    related: ["mv_026", "mv_032", "mv_033"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_026", number: 26, slug: "show-the-cost-of-the-problem", title: "Show the Cost of the Problem",
    summary: "Quantify what the unsolved problem is already costing them, so your proposal is weighed against that cost instead of against zero.",
    category: "positioning", situations: ["pricing", "vendor", "leadership_alignment"],
    goals: ["protect_value", "gain_commitment"], channels: ["in_person", "video", "email"],
    relationships: ["client", "manager", "partner"], urgency: ["this_week", "exploring"],
    principle: "A price looks high only when it stands alone; next to the cost of doing nothing it often looks small.",
    whyItWorks: "Decision-makers compare your fee to an imagined baseline of no spending. Making the current cost visible — lost hours, missed sales, churn, rework — changes that baseline. The conversation becomes whether the problem is worth solving, which is the right question.",
    whenToUse: ["The client agrees the problem is real but balks at the price.", "Leadership is deprioritising an issue that is quietly expensive."],
    whenNotToUse: ["You lack reasonable data and would have to invent figures.", "The cost is emotional for the counterpart and quantifying it would seem callous."],
    signals: ["They say 'it's not that bad' while describing recurring issues.", "Budget conversations ignore the cost of the status quo."],
    preparation: ["Estimate the monthly cost conservatively, showing your assumptions.", "Ask them to correct your numbers rather than defending them."],
    steps: ["Describe the problem in their words.", "Show a conservative cost estimate with assumptions visible.", "Invite them to adjust the numbers.", "Place your proposal next to the agreed cost."],
    openingLine: "Before we talk about the fee, can we put a rough number on what this is costing now?",
    scripts: {
      default: "If each delayed invoice takes about two hours to chase and you have forty a month, that's eighty hours monthly. Does that match your sense of it?",
      diplomatic: "I may be off, so please correct me — my rough estimate is that chasing late invoices takes around eighty staff hours a month. Does that sound right?",
      direct: "Late invoices cost you about eighty hours a month. The fix costs less than two months of that.",
      firm: "The status quo costs roughly eighty hours a month. Waiting another quarter is the most expensive option on the table.",
      written: "Thanks for the call. As a starting point, here's a conservative estimate: forty late invoices a month at around two hours each to chase is roughly eighty staff hours. Please adjust these figures if they're off. Against that, the proposed system costs the equivalent of about six weeks of current effort.",
      message: "Rough math: ~80 hrs/month chasing invoices. Fix pays back in ~6 weeks. Tell me if numbers are off.",
    },
    reactions: [
      { ifThey: "dispute the estimate", counter: "Invite their number and recalculate together; shared figures persuade better than yours." },
      { ifThey: "agree but still delay", counter: "Ask what would need to be true to start, then use Name the Decision." },
    ],
    secondMove: "Once the cost is agreed, use Lead with the Outcome, Not the Hours to present your proposal.",
    followUp: "Send the agreed cost figure in writing so it anchors later budget discussions.",
    mistakes: ["Inflating the cost to make your price look small.", "Presenting the number as an accusation of poor management."],
    ethicalBoundary: "Use honest, conservative assumptions and show them. Inflated cost estimates are manipulation even if the solution is good.",
    risk: "low", walkAway: ["They agree on the cost and still refuse to address it, signalling it is not a real priority."],
    example: "An IT contractor showed a dental practice that system downtime cost roughly two cancelled appointments a week. The 4,000 upgrade, first rejected as too expensive, was approved once compared with about 1,600 monthly in lost bookings.",
    related: ["mv_012", "mv_025", "mv_027"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_027", number: 27, slug: "use-evidence-not-adjectives", title: "Use Evidence, Not Adjectives",
    summary: "Replace claims like 'high quality' and 'experienced' with specific proof, so your value is believed instead of merely stated.",
    category: "positioning", situations: ["pricing", "promotion", "partnership", "compensation"],
    goals: ["protect_value"], channels: ["email", "in_person", "video"],
    relationships: ["client", "employer", "manager", "partner"], urgency: ["this_week", "exploring"],
    principle: "Adjectives ask for trust; evidence earns it.",
    whyItWorks: "Everyone claims to be reliable and skilled, so adjectives carry almost no information. A specific number, named project or short case story is memorable and checkable. It lets the other side justify choosing you to their own colleagues, which is often the real hurdle.",
    whenToUse: ["You are writing a proposal, bio, review self-assessment or pitch.", "You are competing with cheaper alternatives who make similar claims."],
    whenNotToUse: ["Sharing the evidence would breach client confidentiality.", "The setting is informal and a detailed case would feel like overselling."],
    signals: ["Your materials contain words like 'passionate', 'world-class' or 'results-driven'.", "Prospects ask 'what makes you different?' and you answer with adjectives."],
    preparation: ["Rewrite each adjective you use as a specific fact or example.", "Get permission for any client names or figures you plan to cite."],
    steps: ["Find the three strongest claims you make.", "Replace each with a number, a named result or a one-sentence story.", "Lead with the most relevant one to this counterpart.", "Offer a reference or sample on request."],
    openingLine: "Rather than tell you we're reliable, here's what happened on our last three launches.",
    scripts: {
      default: "On our last three launches we delivered on the agreed date each time, and one client's sign-ups rose 30% in the first month.",
      diplomatic: "I'd rather show than tell — I'm happy to share how our last three launches went, including what we learned when one was tight on time.",
      direct: "Three launches, three on-time deliveries, one with a 30% sign-up lift.",
      firm: "Our record is three on-time launches out of three. That's what our price reflects.",
      written: "Thank you for considering us. A few specifics rather than claims: our last three product launches were delivered on the agreed date, and for one client, first-month sign-ups rose 30%. I can connect you with that client if a reference would help.",
      message: "Last 3 launches on time; one had +30% sign-ups. Can share a reference.",
    },
    reactions: [
      { ifThey: "ask for proof", counter: "Provide the reference or sample promptly; delay undermines the evidence." },
      { ifThey: "say a competitor makes the same claims", counter: "Ask whether the competitor has offered comparable specifics; let them judge." },
    ],
    secondMove: "With credibility established, use Present the Price Without Apology.",
    followUp: "Keep a running evidence file of results, quotes and permissions.",
    mistakes: ["Cherry-picking a single outlier result as typical.", "Citing client results without permission."],
    ethicalBoundary: "Represent results honestly and typically, not just best-case. Disclose when a result was a team effort or involved other factors.",
    risk: "low", walkAway: ["The counterpart dismisses all evidence and decides solely on lowest price."],
    example: "A copywriter replaced 'compelling, conversion-focused copy' on her proposal with 'rewrote a checkout page that lifted completed orders 11%'. Her enquiry-to-client rate rose noticeably within two months.",
    related: ["mv_025", "mv_030", "mv_032"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_028", number: 28, slug: "say-what-you-dont-do", title: "Say What You Don't Do",
    summary: "Define your offer by its edges as well as its centre, so clients understand your specialism and stop expecting you to be everything.",
    category: "positioning", situations: ["client_scope", "pricing", "boundary"],
    goals: ["protect_value", "set_boundary"], channels: ["email", "in_person", "video"],
    relationships: ["client", "partner", "vendor"], urgency: ["exploring", "this_week"],
    principle: "A clear 'not this' makes your 'this' worth more.",
    whyItWorks: "Generalists are compared on price; specialists are chosen for fit. Stating what you do not do signals focus and confidence, pre-empts scope creep, and helps the right clients self-select. It also gives you a ready, non-personal reason to decline requests later.",
    whenToUse: ["Clients keep asking for adjacent services you do not want to provide.", "You are positioning a new offer or rewriting a proposal."],
    whenNotToUse: ["You genuinely need the adjacent work and would accept it.", "The exclusion would leave the client stranded without any referral."],
    signals: ["You often do unpaid 'small extras' outside your core service.", "Prospects are unclear what makes you different from a generalist."],
    preparation: ["List the three requests you most often get that sit outside your focus.", "Decide whether to refer, decline or offer them as a separate paid service."],
    steps: ["State your core service in one sentence.", "List what is explicitly outside it.", "Offer a referral or separate option for the excluded items.", "Repeat the edges in proposals and onboarding."],
    openingLine: "To make sure we're a good fit, here's what I focus on — and what I don't.",
    scripts: {
      default: "I focus on brand identity: logo, type and guidelines. I don't build websites, but I work with a developer I can introduce you to.",
      diplomatic: "So you get the best result, I keep my work focused on brand identity. For the website, I'd love to introduce you to a developer I trust.",
      direct: "I do brand identity. I don't build websites.",
      firm: "Website builds are outside my service. I won't take them on, but I can refer you.",
      written: "Thanks for the brief. To set clear expectations: my service covers brand identity — logo, typography, colour and a guidelines document. Website design and development aren't part of what I offer; I'm happy to introduce you to a developer I've worked with if helpful.",
      message: "I cover brand identity only — not the website. Can intro you to a great dev.",
    },
    reactions: [
      { ifThey: "ask you to make an exception", counter: "Restate the focus kindly and offer the referral or a separately priced option." },
      { ifThey: "seem disappointed", counter: "Acknowledge it and point to the benefit of specialist work in the core area." },
    ],
    secondMove: "If an excluded request appears mid-project, use Name the Scope Change.",
    followUp: "Add the 'not included' list to your proposal template.",
    mistakes: ["Listing exclusions so long that the offer feels defensive.", "Making exceptions quietly, which erodes the positioning."],
    ethicalBoundary: "Be honest about why you exclude things and do not leave clients without a reasonable path for critical needs.",
    risk: "low", walkAway: ["A client repeatedly insists on excluded work as a condition of the core engagement."],
    example: "A photographer added 'Not included: video, retouching beyond colour correction' to proposals. Unpaid video requests stopped, and two clients booked a separately priced retouching package.",
    related: ["mv_040", "mv_037", "mv_050"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_029", number: 29, slug: "move-from-vendor-to-advisor", title: "Move from Vendor to Advisor",
    summary: "Shift the relationship from taking orders to shaping decisions by offering a perspective before you are asked for a quote.",
    category: "positioning", situations: ["client_scope", "pricing", "partnership"],
    goals: ["protect_value", "negotiate_terms"], channels: ["in_person", "video", "email"],
    relationships: ["client", "partner"], urgency: ["exploring"],
    principle: "Vendors are asked for prices; advisors are asked for opinions — and opinions shape the price.",
    whyItWorks: "When you only respond to specifications, you compete on cost against anyone who can meet them. When you help define the problem, you influence the specification itself, build trust earlier and become harder to swap for a cheaper provider who arrives later.",
    whenToUse: ["Clients send you detailed specs and ask only for a number.", "You have expertise that could improve their decision but rarely get to share it."],
    whenNotToUse: ["The client is running a strict procurement process that forbids input.", "Your advice would serve your sales interest more than their outcome."],
    signals: ["You learn about projects only when the RFP arrives.", "Clients treat your expertise as a commodity."],
    preparation: ["Identify one insight about their situation that they may not have considered.", "Prepare a short question that invites them to explore it."],
    steps: ["Ask about the goal behind the request before quoting.", "Share one relevant observation or risk.", "Offer two approaches with trade-offs.", "Quote only after the approach is agreed."],
    openingLine: "Before I quote, can I ask what this needs to achieve? I may have a suggestion.",
    scripts: {
      default: "Before I price the twelve-page site, can I ask what success looks like? In similar projects, a four-page site plus a strong booking flow has produced more enquiries.",
      diplomatic: "Happy to quote as specified. Would it be useful if I also shared an alternative approach that's worked well for similar businesses?",
      direct: "I can quote this. I'd recommend a different approach first — can I explain it?",
      firm: "I'd rather not quote until we've agreed the goal. Quoting the wrong solution helps neither of us.",
      written: "Thanks for the specification. Before I prepare a quote, I'd find it useful to understand the main goal — bookings, credibility, or something else. In projects like this, a smaller site focused on booking often outperforms a larger one. I'd be glad to outline both options on a short call.",
      message: "Can quote this — but first, what's the main goal? May have a better option.",
    },
    reactions: [
      { ifThey: "say they just want a price", counter: "Provide it promptly and include one short note on the alternative." },
      { ifThey: "engage with the question", counter: "Listen fully before proposing; the advisory role depends on understanding first." },
    ],
    secondMove: "Once the approach is shaped, use Lead with the Outcome, Not the Hours.",
    followUp: "Send a short summary of the advice even if they do not hire you; it builds reputation.",
    mistakes: ["Lecturing rather than asking.", "Using 'advice' as a disguised upsell."],
    ethicalBoundary: "Advice must serve the client's goal. Steering them to a larger scope because it pays you more breaches the advisory trust you are building.",
    risk: "low", walkAway: ["The client wants only the lowest bid and will not discuss goals."],
    example: "A contractor asked a café owner why she wanted a full refit. The answer was queue times; he proposed moving the counter instead. She paid him for that and later hired him for a larger second-site project.",
    related: ["mv_003", "mv_025", "mv_007"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_030", number: 30, slug: "document-wins-before-you-need-them", title: "Document Wins Before You Need Them",
    summary: "Keep a dated record of results and praise as they happen, so when you need to make your case, the evidence already exists.",
    category: "positioning", situations: ["promotion", "compensation", "client_scope"],
    goals: ["protect_value"], channels: ["email"],
    relationships: ["employer", "manager", "client"], urgency: ["exploring"],
    principle: "Memory favours the recent and the negative; a written record restores the balance.",
    whyItWorks: "When reviews or renewals arrive, both you and the decision-maker remember recent problems more than earlier successes. A running log with dates, numbers and quotes counters that bias and turns your request into a summary of agreed facts.",
    whenToUse: ["You expect a review, renewal or rate discussion within the year.", "Your work produces results that are easy to forget once they become routine."],
    whenNotToUse: ["The log would include confidential information you are not allowed to retain.", "You would use it mainly to keep score against colleagues."],
    signals: ["You struggle to recall what you achieved six months ago.", "Positive feedback arrives verbally and disappears."],
    preparation: ["Create a simple document with date, result, evidence and who noticed.", "Set a monthly ten-minute reminder to update it."],
    steps: ["Record each meaningful result within a week of it happening.", "Save written praise with the date and source.", "Summarise the log quarterly in three lines.", "Share the summary before reviews or renewals."],
    openingLine: "I keep a short log of results through the year — here are the highlights.",
    scripts: {
      default: "Before our review, here are four results from this year with dates, including the March migration and the client renewal in July.",
      diplomatic: "I've found it helpful to keep notes through the year so nothing gets lost. Here's a short summary that might be useful for the review.",
      direct: "Here's my results log for the year. I'd like it considered in the review.",
      firm: "The record shows consistent delivery. I'd like the review decision to reflect it.",
      written: "Hi Jordan — ahead of our review, I've attached a one-page summary of this year's results: the March system migration (zero downtime), the July renewal (retained at +8%), and two process changes that cut ticket backlog by a third. Happy to discuss any of these.",
      message: "Attached: 1-page summary of this year's results for the review.",
    },
    reactions: [
      { ifThey: "seem surprised by the volume", counter: "Use it as a moment to agree on how results should be shared going forward." },
      { ifThey: "dispute an item", counter: "Clarify with the evidence you saved and drop anything that cannot be supported." },
    ],
    secondMove: "Use the summary as the lead fact in Strengthen Your Position Before Asking.",
    followUp: "Keep the log going after the review; it is a habit, not a one-off.",
    mistakes: ["Waiting until the week before a review to reconstruct the year.", "Logging effort instead of outcomes."],
    ethicalBoundary: "Record accurately and credit others where results were shared. A log that inflates your role will be contradicted by colleagues' memories.",
    risk: "low", walkAway: ["A well-documented record is repeatedly dismissed without explanation."],
    example: "A support lead had saved eleven dated client thank-you emails and a backlog chart. Her manager forwarded the one-page summary to HR unchanged as justification for her promotion.",
    related: ["mv_022", "mv_024", "mv_068"], access: "free", editorial: DRAFT_EDITORIAL,
  },
];
