import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Information Gathering (Moves 7–12). */
export const INFORMATION: MoveInput[] = [
  {
    id: "mv_007", number: 7, slug: "ask-the-calibrated-question", title: "Ask the Open 'How' Question",
    summary: "Replace yes/no questions with open 'how' and 'what' questions that make the other side explain their constraints in their own words.",
    category: "information", situations: ["offer", "pricing", "vendor", "compensation"],
    goals: ["clarity", "negotiate_terms"], channels: ["in_person", "phone", "video", "email"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["today", "this_week"],
    principle: "A closed question gets an answer; an open question gets information.",
    whyItWorks: "Yes/no questions invite reflexive refusals and reveal little. Open questions that begin with 'how' or 'what' ask the other side to work through the problem with you, surfacing constraints you could not see and often softening their position as they explain it.",
    whenToUse: ["You received a flat 'no' without reasons.", "You need to understand limits before proposing anything."],
    whenNotToUse: ["The other person has asked you for a clear answer; answering a question with a question is evasive.", "Time is short and a direct request is clearly more appropriate."],
    signals: ["Your questions keep getting one-word answers.", "You are guessing at their limits."],
    preparation: ["Rewrite your three key questions to start with 'how' or 'what'.", "Remove any question that implies blame."],
    steps: ["Ask one open question.", "Stay silent until they finish.", "Summarise what you heard.", "Ask one follow-up that goes deeper on the most important point."],
    openingLine: "What would need to be true for this to work on your side?",
    scripts: {
      default: "What would need to be true for this to work within your budget this quarter?",
      diplomatic: "I'd really like to find a way to make this work. How do you see us getting there from here?",
      direct: "How am I supposed to deliver this scope at that fee?",
      firm: "What are you able to change, given that I can't change the fee?",
      written: "Thanks for the update. To help me find an option that fits, could you share what would need to be true on your side for this to move forward — in terms of budget, timing or scope?",
      message: "What would need to change for this to work on your end?",
    },
    reactions: [
      { ifThey: "answer vaguely", counter: "Ask 'What does that look like in practice?' to make it concrete." },
      { ifThey: "turn the question back to you", counter: "Give a short, honest answer, then return to your question." },
    ],
    secondMove: "Use their answer to build two options with Offer Two Paths.",
    followUp: "Note their exact words; quoting them later anchors the agreement in their own reasoning.",
    mistakes: ["Stacking several questions at once.", "Using 'why' in a way that sounds accusatory."],
    ethicalBoundary: "Ask questions to understand, not to trap. Do not use answers to embarrass the other person later.",
    risk: "low", walkAway: ["Every open question is met with refusal to engage at all."],
    example: "A freelancer was told 'we can't do that rate'. Instead of lowering it, she asked what would need to be true for it to fit; the client explained the budget reset in April, and they agreed a lower-scope pilot until then.",
    related: ["mv_003", "mv_008", "mv_012"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_008", number: 8, slug: "ask-for-the-constraint", title: "Ask for the Constraint",
    summary: "Find out whether the obstacle is budget, authority, timing or confidence before you offer anything to remove it.",
    category: "information", situations: ["pricing", "offer", "client_scope", "vendor", "follow_up"],
    goals: ["clarity", "negotiate_terms", "protect_value"], channels: ["in_person", "phone", "video", "email"],
    relationships: ["client", "employer", "vendor"], urgency: ["today", "this_week"],
    principle: "You cannot remove an obstacle you have not identified; a discount only solves one of four.",
    whyItWorks: "Objections usually come from one of four constraints — money, authority, timing or confidence. Each needs a different response. Asking which one applies stops you from offering the most expensive fix (price) to a problem that may be about approval or risk.",
    whenToUse: ["A deal has stalled after initial enthusiasm.", "You are tempted to offer a discount to restart momentum."],
    whenNotToUse: ["The constraint is already explicit and confirmed.", "Asking would reveal confidential information you are not entitled to."],
    signals: ["'We love it, but…' with no specific reason.", "Repeated requests for 'a bit more time'."],
    preparation: ["Prepare a matching response for each of the four constraint types.", "Decide which you can address without changing price."],
    steps: ["Name the stall neutrally.", "Offer the four possibilities and ask which applies.", "Confirm the constraint in their words.", "Respond only to that constraint."],
    openingLine: "It sounds like something is in the way. Is it budget, approval, timing, or confidence in the approach?",
    scripts: {
      default: "It feels like we've slowed down. Is the main obstacle budget, getting approval, timing, or confidence in the approach? I'd rather solve the right thing.",
      diplomatic: "I sense some hesitation, and that's completely fine. Could you help me understand what's behind it, so I can be useful rather than pushy?",
      direct: "What specifically is stopping a yes?",
      firm: "Before I change anything in the proposal, I need to know what the actual obstacle is.",
      written: "Hi Priya — I want to make sure I'm addressing the right thing. Is what's holding this back mainly budget, internal approval, timing, or confidence in the approach? Each has a different solution, and some may not require changing the proposal at all.",
      message: "Is the hold-up budget, approval, timing, or something about the approach?",
    },
    reactions: [
      { ifThey: "say budget", counter: "Ask whether the issue is the total, the timing of payment, or the approval threshold before discussing price." },
      { ifThey: "say approval", counter: "Offer materials that help your contact win the internal case." },
      { ifThey: "say confidence", counter: "Offer a smaller first phase or a clear success measure rather than a discount." },
    ],
    secondMove: "Address the named constraint, then use Name the Decision to confirm a date.",
    followUp: "Restate the constraint and your proposed fix in writing.",
    mistakes: ["Assuming budget is the constraint because it is the most common.", "Offering several fixes at once, which looks like panic."],
    ethicalBoundary: "Do not pressure someone to reveal internal politics they are not free to share.",
    risk: "low", walkAway: ["The constraint is permanent — for example, the budget has been cut entirely."],
    example: "A training provider was about to cut price 15% to revive a stalled deal. Asking for the constraint revealed the buyer's director doubted the outcomes, so the provider offered a measured pilot cohort at full rate instead.",
    related: ["mv_003", "mv_055", "mv_013"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_009", number: 9, slug: "summarize-to-confirm", title: "Summarize to Confirm",
    summary: "Play back what you heard in your own words and ask if you got it right, before responding with your own view.",
    category: "information", situations: ["difficult_conversation", "workplace_conflict", "client_scope", "relationship_repair"],
    goals: ["clarity", "de_escalate", "resolve_conflict"], channels: ["in_person", "phone", "video"],
    relationships: ["client", "colleague", "manager", "report", "partner"], urgency: ["today", "this_week"],
    principle: "People stop repeating themselves once they believe they have been understood.",
    whyItWorks: "Accurate playback signals respect, catches misunderstandings early and gives the other side a chance to correct or soften. It also slows a fast-moving conversation so you respond to content rather than tone.",
    whenToUse: ["The other side is frustrated or repeating points.", "A complex request has several parts."],
    whenNotToUse: ["The point was simple; summarising it sounds patronising.", "You are using summary to stall rather than respond."],
    signals: ["They raise the same point a second or third time.", "Their tone sharpens as the conversation continues."],
    preparation: ["Practise summarising without adding judgement words.", "Decide which parts of their message matter most."],
    steps: ["Wait for them to finish.", "Summarise in two or three sentences.", "Ask 'Did I get that right?'", "Only then give your view."],
    openingLine: "Let me make sure I've got this right before I respond.",
    scripts: {
      default: "So what I'm hearing is that the report arrived later than you needed, and that made you look unprepared with your board. Have I got that right?",
      diplomatic: "I want to be sure I understand before I say anything. It sounds like the timing put you in a difficult position with the board — is that fair?",
      direct: "You're saying the late report hurt you with the board. Correct?",
      firm: "I've heard your concern about the report's timing. I'll respond to that, but first let me confirm I understand it accurately.",
      written: "Thank you for explaining. To confirm I understand: the report arrived on Tuesday rather than Monday, and that left you without time to prepare for the board meeting. Please correct anything I've missed — I'll then set out what we'll change.",
    },
    reactions: [
      { ifThey: "correct your summary", counter: "Thank them, restate the corrected version, and confirm again." },
      { ifThey: "say 'exactly'", counter: "Move to your response; the conversation is now on stable ground." },
    ],
    secondMove: "If the summary reveals a real failure on your side, move to Own the Specific Miss.",
    followUp: "Include the confirmed summary in any written follow-up.",
    mistakes: ["Paraphrasing with loaded words they did not use.", "Summarising and then immediately arguing."],
    ethicalBoundary: "Do not summarise in a way that subtly reframes their concern as smaller than it is.",
    risk: "low", walkAway: ["They refuse to engage with any accurate summary and escalate personally."],
    example: "An account manager received an angry call about a delay. After summarising the client's concern and getting a 'yes, that's it', the tone dropped, and the client accepted a revised schedule.",
    related: ["mv_073", "mv_002", "mv_074"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_010", number: 10, slug: "test-the-assumption-cheaply", title: "Test the Assumption Cheaply",
    summary: "Before committing to a big move based on a belief, run the smallest possible test that would prove the belief wrong.",
    category: "information", situations: ["pricing", "offer", "compensation", "partnership"],
    goals: ["clarity", "protect_value"], channels: ["email", "phone", "chat"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["this_week", "exploring"],
    principle: "The cheapest information is the information you get before you commit.",
    whyItWorks: "Big moves built on untested beliefs fail expensively. A small probe — a question, a trial price, a hypothetical — reveals whether the belief holds while it can still be changed, and costs little if it does not.",
    whenToUse: ["Your strategy depends on one belief you have not confirmed.", "You are considering a price change, ultimatum or major proposal."],
    whenNotToUse: ["The test itself would damage trust or reveal your hand prematurely.", "You already have strong evidence."],
    signals: ["You say 'they'll never accept that' without having asked.", "A single assumption decides your whole plan."],
    preparation: ["Write the belief your plan depends on.", "Design one low-cost way it could be disproved."],
    steps: ["State the belief explicitly.", "Choose a test that is reversible.", "Run it and record the result.", "Adjust the plan before the bigger move."],
    openingLine: "Hypothetically, if we structured it differently, would that be worth exploring?",
    scripts: {
      default: "Hypothetically, if we moved to a quarterly retainer instead of per-project billing, is that something your team could consider?",
      diplomatic: "I'm just thinking out loud — would a different structure be interesting to you, or is the current one best?",
      direct: "Would you consider a quarterly retainer?",
      firm: "I'm reviewing how I structure engagements next year. Would a retainer be workable for you, yes or no?",
      written: "Quick question as I plan next year: would a quarterly retainer model be something your team could work with, as an alternative to per-project billing? No decision needed now — I'm gauging interest.",
      message: "Thinking ahead — would a quarterly retainer ever be workable for your team?",
    },
    reactions: [
      { ifThey: "react positively", counter: "Follow with a concrete proposal while the interest is fresh." },
      { ifThey: "react negatively", counter: "Ask what about it doesn't fit; you have learned cheaply." },
    ],
    secondMove: "If the test confirms the belief, proceed with the full move; if not, revisit Define Success Before You Start.",
    followUp: "Record what you learned so the next decision starts from evidence.",
    mistakes: ["Designing a test that cannot fail.", "Running the test so clumsily that it becomes the negotiation."],
    ethicalBoundary: "Do not float hypotheticals you have no intention of honouring if accepted.",
    risk: "low", walkAway: ["The test shows the core of your plan cannot work for the other side."],
    example: "A consultant assumed clients would refuse a price rise. She tested a 10% higher rate on one new proposal; it was accepted without comment, and she applied it to new clients from then on.",
    related: ["mv_002", "mv_031", "mv_022"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_011", number: 11, slug: "listen-for-the-tell", title: "Listen for the Priority Signal",
    summary: "Notice which topics the other side returns to, avoids or emphasises; those patterns show what matters most to them.",
    category: "information", situations: ["offer", "vendor", "partnership", "pricing"],
    goals: ["clarity", "negotiate_terms"], channels: ["in_person", "video", "phone"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["this_week", "exploring"],
    principle: "What people repeat matters to them; what they avoid usually matters more.",
    whyItWorks: "Stated priorities are often polite fictions. Repetition, sudden detail, avoidance and changes in pace are more reliable indicators of what the other side values, letting you trade cheaply on things they care about and protect what they don't.",
    whenToUse: ["Early in a negotiation, while priorities are unclear.", "When stated priorities don't match behaviour."],
    whenNotToUse: ["As a substitute for asking directly when asking is easy.", "To read emotional states you are not equipped to interpret."],
    signals: ["One topic gets three times the airtime of others.", "A topic is changed abruptly when raised."],
    preparation: ["Prepare a short list of topics to observe.", "Bring a way to note emphasis discreetly."],
    steps: ["Raise each key topic once.", "Note which they expand on and which they shorten.", "Check one observation with a direct question.", "Use confirmed priorities in your proposal."],
    openingLine: "You've mentioned the start date a few times — is that the most important piece for you?",
    scripts: {
      default: "You've mentioned the start date a few times. Is timing the most important part of this for you?",
      diplomatic: "I noticed timing keeps coming up, and I want to make sure I'm weighting it properly. How important is it compared with the rest?",
      direct: "Is the start date your top priority?",
      firm: "If the start date matters most, I can work with that — but it will affect other terms.",
      written: "From our conversation, it sounded like the start date is especially important to you. If that's right, I'd like to put together an option built around it. Could you confirm how it ranks against cost and scope?",
    },
    reactions: [
      { ifThey: "confirm the priority", counter: "Build a proposal that meets it and trade other terms in return." },
      { ifThey: "deny it", counter: "Accept their answer and keep observing; do not argue with their self-description." },
    ],
    secondMove: "Use the confirmed priority as currency in Trade, Never Concede.",
    followUp: "Record the priority ranking so later proposals stay consistent.",
    mistakes: ["Treating one observation as certain.", "Telling the other person what they 'really' want."],
    ethicalBoundary: "Observe behaviour, not character. Never claim to diagnose motives or emotions.",
    risk: "low", walkAway: ["Their confirmed top priority is something you cannot offer."],
    example: "A hiring manager kept circling back to start date. The candidate confirmed it was the top priority, offered an earlier start, and in exchange secured an extra week of leave.",
    related: ["mv_008", "mv_055", "mv_007"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_012", number: 12, slug: "ask-what-happens-if-nothing-changes", title: "Ask What Happens If Nothing Changes",
    summary: "Have the other side describe the cost of inaction in their own words, so the status quo stops looking free.",
    category: "information", situations: ["pricing", "vendor", "leadership_alignment", "follow_up"],
    goals: ["clarity", "gain_commitment"], channels: ["in_person", "phone", "video"],
    relationships: ["client", "manager", "partner"], urgency: ["this_week", "exploring"],
    principle: "Delay feels free until someone counts what it costs.",
    whyItWorks: "Decisions stall because doing nothing seems risk-free. When the other side states the cost of inaction themselves, the comparison shifts from 'your proposal versus nothing' to 'your proposal versus a cost they have named', which is far more motivating than any argument you make.",
    whenToUse: ["A decision keeps being deferred without reason.", "The other side treats the status quo as safe."],
    whenNotToUse: ["The status quo genuinely is fine for them; manufacturing urgency is manipulative.", "They are already overwhelmed and need options, not pressure."],
    signals: ["'Let's revisit next quarter' with no clear trigger.", "They agree the problem is real but take no action."],
    preparation: ["Estimate the cost of inaction yourself so you can recognise a realistic answer.", "Prepare a follow-up question about timing."],
    steps: ["Ask what happens if nothing changes for three months.", "Let them quantify it.", "Reflect the cost back.", "Ask whether waiting is still the best option."],
    openingLine: "If we left this as it is for the next three months, what would that mean for you?",
    scripts: {
      default: "If we left the onboarding process as it is for the next three months, what would that mean for your team?",
      diplomatic: "There's no pressure to decide today. I'm curious, though — what does it cost you to keep things as they are?",
      direct: "What does waiting cost you?",
      firm: "Waiting is a decision too. What's the cost of it for you?",
      written: "As you consider timing, it may help to look at the cost of waiting. If onboarding stays as it is for another quarter, roughly how many hours or customers would that affect? I'm happy to work through the numbers with you.",
    },
    reactions: [
      { ifThey: "name a meaningful cost", counter: "Reflect it back and ask what would make starting now feasible." },
      { ifThey: "say there is no cost", counter: "Accept it; the timing may genuinely be wrong. Set a future checkpoint." },
    ],
    secondMove: "If the cost is real, use Name the Decision to fix a date.",
    followUp: "Include their stated cost in the proposal recap — in their words.",
    mistakes: ["Answering the question for them with your own numbers.", "Exaggerating the cost to create pressure."],
    ethicalBoundary: "Never invent or inflate consequences. If inaction is fine for them, say so.",
    risk: "low", walkAway: ["They see no cost in waiting and no future trigger exists."],
    example: "A software vendor asked an operations lead what three more months of manual reporting would cost. She estimated 60 staff hours; the purchase was approved that month.",
    related: ["mv_001", "mv_043", "mv_008"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
];
