import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Anchoring & Pricing (Moves 31–36). */
export const PRICING: MoveInput[] = [
  {
    id: "mv_031", number: 31, slug: "anchor-first-with-a-reason", title: "Anchor First with a Reason",
    summary: "State your number first, attached to a clear rationale, so the negotiation starts from your reference point rather than theirs.",
    category: "pricing", situations: ["pricing", "compensation", "offer", "vendor"],
    goals: ["negotiate_terms", "protect_value"], channels: ["in_person", "phone", "email", "video"],
    relationships: ["client", "employer", "vendor"], urgency: ["today", "this_week"],
    principle: "The first credible number in the room quietly sets the range for every number after it.",
    whyItWorks: "Counteroffers tend to move relative to the first figure stated. A reasoned anchor — tied to scope, market data or results — shapes expectations without seeming arbitrary, and the reason gives the other side something to engage with besides the size of the number.",
    whenToUse: ["You have a good sense of market value and the other side does not.", "You are asked 'what are you looking for?' in a salary or fee discussion."],
    whenNotToUse: ["You lack information and anchoring could leave money on the table; ask questions first.", "The counterpart has already made a fair offer within your range."],
    signals: ["The other side waits for you to name a figure.", "You are tempted to say 'whatever's standard'."],
    preparation: ["Choose an ambitious but defensible number above your floor.", "Write one sentence explaining what the number is based on."],
    steps: ["State the number clearly, without hedging words.", "Give the reason in one sentence.", "Stop and wait for their response.", "Respond to counteroffers by referencing the reason, not by splitting the difference."],
    openingLine: "Based on the scope we discussed, I'd propose the following.",
    scripts: {
      default: "Based on the twelve-week timeline and two rounds of user testing, the fee is 24,000.",
      diplomatic: "I've looked carefully at the scope. Given the twelve-week timeline and the testing rounds, I'd propose 24,000. I'm happy to talk through how I got there.",
      direct: "The fee is 24,000, based on twelve weeks and two testing rounds.",
      firm: "My fee for this scope is 24,000. That reflects the timeline and testing involved.",
      written: "Thank you for the detailed brief. Based on the twelve-week timeline, two rounds of user testing and final handover documentation, my fee for the project is 24,000, payable in three milestones. I'd be glad to discuss the scope if you'd like to adjust it.",
      message: "For 12 weeks + 2 testing rounds, the fee is 24k across 3 milestones.",
    },
    reactions: [
      { ifThey: "react with surprise", counter: "Stay silent for a moment, then restate the reason calmly. Do not lower the number to relieve the tension." },
      { ifThey: "counter with a much lower number", counter: "Ask what their figure is based on, then adjust scope rather than price." },
    ],
    secondMove: "If they push hard, use Offer Tiers, Not Discounts to keep price tied to scope.",
    followUp: "Confirm the agreed number and what it includes in writing the same day.",
    mistakes: ["Softening the anchor with 'around' or 'maybe'.", "Anchoring so high it destroys credibility."],
    ethicalBoundary: "Anchor ambitiously but honestly. A number you cannot justify with real scope or value is a bluff that can damage the relationship.",
    risk: "medium", walkAway: ["Their counter stays below your floor after a scope adjustment is offered."],
    example: "Asked 'what's your budget expectation?', a consultant answered '30,000, based on four workshops and a written strategy'. The client had planned 20,000 but settled at 27,000 with one workshop removed.",
    related: ["mv_019", "mv_032", "mv_034"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_032", number: 32, slug: "present-the-price-without-apology", title: "Present the Price Without Apology",
    summary: "Say your price plainly and stop talking, without nervous discounts, justifications or filler that signal you expect it to be rejected.",
    category: "pricing", situations: ["pricing", "vendor", "client_scope"],
    goals: ["protect_value"], channels: ["in_person", "phone", "video", "email"],
    relationships: ["client", "vendor"], urgency: ["today", "this_week"],
    principle: "A price delivered with an apology invites a discount.",
    whyItWorks: "Hesitation, qualifiers and immediate justifications tell the buyer the price is negotiable before they have said a word. A clean statement followed by silence communicates confidence and gives them space to respond to the value rather than to your discomfort.",
    whenToUse: ["You tend to discount before the client has objected.", "You are quoting a new, higher rate for the first time."],
    whenNotToUse: ["The client is in genuine financial hardship and empathy matters more than firmness.", "You actually have flexibility and want to invite discussion."],
    signals: ["You say 'I know it's a lot, but…' when quoting.", "You offer a discount before being asked."],
    preparation: ["Practise saying the price out loud until it sounds ordinary to you.", "Decide in advance what, if anything, you will trade for a lower price."],
    steps: ["State what is included in one sentence.", "State the price.", "Stop talking and wait.", "Answer questions about value; do not volunteer discounts."],
    openingLine: "Here's what's included and the investment.",
    scripts: {
      default: "The package includes the audit, the action plan and two follow-up sessions. The price is 3,200.",
      diplomatic: "I'm glad this sounds like a fit. The full package — audit, action plan and two follow-ups — is 3,200.",
      direct: "It's 3,200 for the full package.",
      firm: "The price is 3,200. I don't discount the package.",
      written: "Thank you for your interest. The package includes a full audit, a written action plan and two 45-minute follow-up sessions. The investment is 3,200, payable on booking. Let me know if you'd like to go ahead and I'll send the agreement.",
      message: "Audit + plan + 2 follow-ups: 3,200. Want me to send the agreement?",
    },
    reactions: [
      { ifThey: "pause in silence", counter: "Let the silence run. The next useful words are usually theirs." },
      { ifThey: "ask for a discount", counter: "Ask what they would like to remove, or what they could offer in exchange." },
    ],
    secondMove: "If they ask for less, use Trade, Never Concede.",
    followUp: "Send the agreement promptly once they say yes, before second thoughts set in.",
    mistakes: ["Filling the silence with justifications.", "Smiling apologetically while quoting."],
    ethicalBoundary: "Confidence is not pressure. Do not use silence or tone to rush someone into a decision they need time to consider.",
    risk: "low", walkAway: ["The client wants the full package at a price below your floor with nothing traded."],
    example: "A coach who usually added 'but I can do a payment plan' immediately after quoting stopped doing so. In her next five consultations, four paid in full; one asked for a plan, which she offered then.",
    related: ["mv_031", "mv_044", "mv_055"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_033", number: 33, slug: "offer-tiers-not-discounts", title: "Offer Tiers, Not Discounts",
    summary: "When price is a concern, offer a smaller scope at a lower price instead of cutting the price of the same work.",
    category: "pricing", situations: ["pricing", "client_scope", "vendor"],
    goals: ["protect_value", "negotiate_terms"], channels: ["email", "in_person", "video"],
    relationships: ["client", "vendor"], urgency: ["today", "this_week"],
    principle: "Change what they get before you change what it costs.",
    whyItWorks: "A discount on the same work teaches the client that your first price was padded and invites future haggling. Tiers keep your rate intact, let the client choose the value they can afford and often lead them to pick the middle or full option once they compare.",
    whenToUse: ["A client says your proposal is over budget.", "You want to make your offer accessible without lowering your rate."],
    whenNotToUse: ["The scope cannot be meaningfully reduced without failing the goal.", "You have a deliberate, consistent discount policy (e.g. for non-profits)."],
    signals: ["Clients ask 'can you do it for less?' about a fixed scope.", "You often discount and then feel resentful mid-project."],
    preparation: ["Design three options: essential, recommended, complete.", "Make sure each tier delivers a real outcome, not a hobbled version."],
    steps: ["Acknowledge the budget concern.", "Present the tiers with what each includes and excludes.", "Recommend the tier that best fits their goal and explain why.", "Let them choose; do not discount any tier."],
    openingLine: "If budget is the concern, let's adjust the scope rather than the quality.",
    scripts: {
      default: "If 9,000 is above budget, there's a 5,500 option that covers research and the core design, without the prototype and testing.",
      diplomatic: "I'd love to make this work within your budget. Rather than cut corners, could we look at a smaller scope? Here are two options.",
      direct: "I don't discount, but I can reduce the scope. Here are 5,500 and 9,000 options.",
      firm: "The price for this scope is 9,000. If that's too much, the smaller option is 5,500.",
      written: "Thanks for being open about the budget. Rather than reduce the price for the same work, here are three options: Essential (5,500) — research and core designs; Recommended (9,000) — adds a clickable prototype and one testing round; Complete (12,500) — adds a second testing round and developer handover. Based on your launch goals, I'd recommend the 9,000 option.",
      message: "Options: 5.5k (core), 9k (with prototype + test), 12.5k (full). I'd recommend 9k.",
    },
    reactions: [
      { ifThey: "want the full scope at the lower price", counter: "Restate that each price matches its scope and ask which items matter most to them." },
      { ifThey: "pick the smallest tier", counter: "Accept warmly and deliver it well; upgrades often follow good work." },
    ],
    secondMove: "If they choose a smaller tier, use Write the Out-of-Scope List so excluded items stay excluded.",
    followUp: "Keep the tier structure in future proposals so discounts are never the default response.",
    mistakes: ["Creating a deliberately poor bottom tier to push the top one.", "Allowing the smaller tier to quietly expand."],
    ethicalBoundary: "Each tier must be a genuine, useful option. Designing a decoy tier to manipulate choice undermines trust.",
    risk: "low", walkAway: ["The client insists on the complete scope at the essential price."],
    example: "A web studio replaced 15% discounts with three tiers. Average project value rose because most clients chose the middle option, and mid-project scope disputes dropped because exclusions were explicit.",
    related: ["mv_025", "mv_041", "mv_058"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_034", number: 34, slug: "answer-a-lowball-with-a-reason", title: "Answer a Lowball with a Reason",
    summary: "When an offer comes in far below expectations, ask what it is based on before countering, so you respond to their logic rather than their number.",
    category: "pricing", situations: ["offer", "compensation", "pricing"],
    goals: ["negotiate_terms", "clarity"], channels: ["phone", "email", "video", "in_person"],
    relationships: ["employer", "client", "vendor"], urgency: ["today", "this_week"],
    principle: "A lowball is an opening move, not a verdict — find out what it stands on.",
    whyItWorks: "Instant counters turn the negotiation into a tug of war between two numbers. Asking what the offer reflects reveals whether it is based on budget, a misunderstanding of scope, outdated benchmarks or a test of your resolve. Each needs a different response, and the question shows composure.",
    whenToUse: ["You receive an offer well below your range.", "You feel the urge to respond immediately with anger or a counter."],
    whenNotToUse: ["The offer is close to your range and a simple counter would close it.", "You have already decided to decline for other reasons."],
    signals: ["The offer is 20% or more below your expectation.", "No reasoning came with the number."],
    preparation: ["Pause before replying; decide not to counter in the first response.", "Prepare your market data or scope reasoning for the second response."],
    steps: ["Thank them for the offer without accepting it.", "Ask what the figure is based on.", "Listen for budget, scope or benchmark reasons.", "Respond to the reason with data, scope changes or a reasoned counter."],
    openingLine: "Thank you for the offer. Could you help me understand how you arrived at that figure?",
    scripts: {
      default: "Thank you. Before I respond, could you help me understand what the 68,000 is based on? It's below what I've seen for similar roles.",
      diplomatic: "I appreciate the offer and I'm still very interested. It's lower than I expected, so I'd love to understand how the number was put together.",
      direct: "That's well below market for this role. What is it based on?",
      firm: "That figure doesn't work for me. I'd like to understand the basis before we go further.",
      written: "Thank you for the offer — I'm enthusiastic about the role. The base of 68,000 is below the range I've seen for comparable positions in this market, so it would help to understand how it was determined. Once I understand the basis, I'll come back with a considered response.",
      message: "Thanks for the offer. It's below what I expected — how was the number set?",
    },
    reactions: [
      { ifThey: "cite a fixed budget", counter: "Ask which non-salary terms are flexible and whether the role scope could change." },
      { ifThey: "cite internal benchmarks", counter: "Share your external data respectfully and ask whether level or title could be revisited." },
      { ifThey: "say it's their best and final", counter: "Thank them, take time to consider, and decide against your walk-away point." },
    ],
    secondMove: "Once you know the basis, use Anchor First with a Reason for your counter.",
    followUp: "Summarise what you learned and your response in writing within 48 hours.",
    mistakes: ["Countering instantly with your ideal number.", "Treating the lowball as a personal insult."],
    ethicalBoundary: "Ask the question genuinely and listen. Using it as a rhetorical trap to embarrass the other side damages the working relationship.",
    risk: "low", walkAway: ["After discussion, the best offer remains below your floor with no movement on other terms."],
    example: "Offered 15,000 for a project she quoted at 25,000, a consultant asked what it was based on. The client had excluded implementation from their estimate. They agreed 22,000 with a reduced implementation phase.",
    related: ["mv_008", "mv_031", "mv_019"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_035", number: 35, slug: "raise-your-rate-with-notice", title: "Raise Your Rate with Notice",
    summary: "Increase prices for existing clients with clear written notice, a short reason and a date, rather than apologising or surprising them.",
    category: "pricing", situations: ["pricing", "client_scope"],
    goals: ["protect_value"], channels: ["email", "in_person"],
    relationships: ["client"], urgency: ["this_week", "exploring"],
    principle: "Notice turns a price increase from a surprise into a plan.",
    whyItWorks: "Clients rarely resent fair increases; they resent surprises. Giving a defined notice period, a brief rationale and a clear effective date lets them budget, signals professionalism and makes the change feel like normal business rather than opportunism.",
    whenToUse: ["Your rates have not changed in a year or more while costs or demand have risen.", "You are fully booked and want to rebalance your client base."],
    whenNotToUse: ["A current contract fixes the price for its term.", "The client is mid-crisis and the timing would seem exploitative."],
    signals: ["New clients pay more than long-standing ones.", "You feel resentment toward clients on legacy rates."],
    preparation: ["Decide the new rate and the effective date, typically 30–60 days out.", "Check existing agreements for notice requirements."],
    steps: ["Write a short notice with new rate, effective date and one-sentence reason.", "Thank them for the relationship.", "Offer a short call for questions, not negotiation.", "Apply the new rate on the date stated."],
    openingLine: "I'm writing to let you know about an update to my rates, effective from the 1st of next quarter.",
    scripts: {
      default: "From 1 April my monthly retainer will be 2,400, up from 2,100. This reflects expanded reporting and rising costs. Nothing changes in the service you receive.",
      diplomatic: "I've really valued working together this year. I wanted to give you plenty of notice that from 1 April the retainer will move to 2,400. I'm happy to talk through any questions.",
      direct: "From 1 April the retainer will be 2,400.",
      firm: "The new rate of 2,400 applies from 1 April for all retainer clients.",
      written: "Hi Lena — thank you for a great year working together. I'm writing to give you 60 days' notice that from 1 April, the monthly retainer will be 2,400 (currently 2,100). This reflects the expanded monthly reporting we added in the autumn and increased operating costs. The scope of the service stays the same. Happy to jump on a call if you have questions.",
      message: "Heads up: from 1 April the retainer moves to 2,400. Full note in your inbox.",
    },
    reactions: [
      { ifThey: "ask to stay on the old rate", counter: "Thank them, restate the date, and offer a reduced scope at the old rate if appropriate." },
      { ifThey: "accept without comment", counter: "Confirm in writing and continue as usual." },
    ],
    secondMove: "If a client cannot afford the change, use Offer Tiers, Not Discounts to design a smaller retainer.",
    followUp: "Update invoices and agreements on the effective date without reminders that feel like apologies.",
    mistakes: ["Announcing the increase verbally only.", "Backing down at the first sign of displeasure."],
    ethicalBoundary: "Honour existing contractual terms and give reasonable notice. Raising prices mid-contract without agreement may breach the agreement.",
    risk: "medium", walkAway: ["A client will only continue at a rate below your floor."],
    example: "A virtual assistant sent 60-day notice of a 12% increase to six clients. Five accepted; one moved to a smaller package. Her monthly income rose and her schedule became lighter.",
    related: ["mv_032", "mv_033", "mv_022"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_036", number: 36, slug: "price-the-rush", title: "Price the Rush",
    summary: "When a client needs work faster than normal, attach a clear premium to the compressed timeline instead of absorbing the cost yourself.",
    category: "pricing", situations: ["pricing", "client_scope", "boundary"],
    goals: ["protect_value", "set_boundary"], channels: ["email", "phone", "chat"],
    relationships: ["client", "manager"], urgency: ["today"],
    principle: "Urgency is a service with a cost; name it or you will pay it.",
    whyItWorks: "Rush requests displace other work, require overtime and raise error risk. A stated rush premium makes those costs visible, filters out false urgency and compensates you fairly when the deadline is genuine. Clients often find a little more time once speed has a price.",
    whenToUse: ["A client asks for delivery in days instead of the usual weeks.", "Last-minute requests are becoming a pattern."],
    whenNotToUse: ["The rush was caused by your own delay.", "It is a genuine emergency where a premium would seem exploitative."],
    signals: ["Requests arrive with 'ASAP' but no explanation.", "You regularly work weekends for clients who planned late."],
    preparation: ["Define your standard turnaround and your rush premium in advance (for example +30% under five days).", "Know which other work would be displaced."],
    steps: ["Confirm the deadline and why it matters.", "State the standard timeline and the rush option with its premium.", "Let them choose.", "Document the choice before starting."],
    openingLine: "I can meet that date. Here's what the faster timeline involves.",
    scripts: {
      default: "My standard turnaround is two weeks. For delivery by Friday, there's a 30% rush fee, bringing it to 3,900.",
      diplomatic: "I'd really like to help you hit Friday. To make that work I'd need to move other commitments, so the rush rate applies — 3,900 instead of 3,000.",
      direct: "Friday delivery is 3,900. Standard two-week delivery is 3,000.",
      firm: "I can do Friday at the rush rate of 3,900. Otherwise, the standard timeline applies.",
      written: "Thanks for the request. My standard turnaround is two weeks, at 3,000. To deliver by this Friday, I'd need to reschedule other work, so a 30% rush fee applies, for a total of 3,900. Let me know which option works and I'll confirm the schedule today.",
      message: "Friday is doable at the rush rate (3,900). Standard 2-week delivery is 3,000.",
    },
    reactions: [
      { ifThey: "say the rush is urgent but they can't pay more", counter: "Offer a reduced scope by Friday at the standard price." },
      { ifThey: "suddenly find more time", counter: "Agree on the standard timeline and confirm the new date in writing." },
    ],
    secondMove: "If rush requests continue, use Protect Your Availability Hours to set standing expectations.",
    followUp: "Add your rush policy to your terms so it is not negotiated each time.",
    mistakes: ["Charging a rush fee when the delay was yours.", "Agreeing to rush work and then missing the date."],
    ethicalBoundary: "Apply the premium consistently and transparently. Inventing urgency surcharges after work has started is unfair.",
    risk: "low", walkAway: ["Rush work is demanded repeatedly at standard rates with no planning change."],
    example: "A translator introduced a 25% fee for under-48-hour jobs. Rush requests from one agency dropped by half, and the ones that remained were genuinely urgent and better paid.",
    related: ["mv_046", "mv_052", "mv_038"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
];
