import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Scope Control (Moves 37–42). */
export const SCOPE: MoveInput[] = [
  {
    id: "mv_037", number: 37, slug: "name-the-scope-change", title: "Name the Scope Change",
    summary: "Point out, calmly and early, when a request falls outside the agreed work, so the change becomes a decision instead of a silent favour.",
    category: "scope", situations: ["client_scope", "boundary"],
    goals: ["protect_value", "set_boundary"], channels: ["email", "chat", "video"],
    relationships: ["client", "manager"], urgency: ["today", "this_week"],
    principle: "Unnamed scope changes become the new baseline.",
    whyItWorks: "Clients often do not realise a request is extra; they are thinking about their goal, not your contract. Naming it neutrally — 'this is outside what we agreed' — gives them information and choice without accusation, and stops the gradual expansion that makes projects unprofitable.",
    whenToUse: ["A client asks for 'one small thing' not in the agreement.", "Extra work has crept in over several weeks."],
    whenNotToUse: ["The request is trivial and goodwill is worth more than the time.", "The agreement is genuinely ambiguous on this point; clarify the agreement first."],
    signals: ["You feel reluctant to log the time a task is taking.", "The phrase 'while you're at it' appears in requests."],
    preparation: ["Check the agreement and quote the relevant scope line.", "Estimate the time or cost of the request."],
    steps: ["Acknowledge the request and its value to them.", "State that it sits outside the current scope.", "Offer options: add it with a cost, swap it for something else, or defer it.", "Confirm the choice in writing before starting."],
    openingLine: "Happy to help with this — I want to flag that it's outside what we agreed, so we can decide how to handle it.",
    scripts: {
      default: "The social media templates would be useful. They're outside the website scope we agreed, so I can add them for 1,200 or we can plan them for phase two.",
      diplomatic: "Great idea — I can see how the templates would help. Just so we keep things clear, they weren't part of the original scope. Would you like me to quote them?",
      direct: "The templates are outside the agreed scope. It's 1,200 to add them.",
      firm: "I can't add the templates within the current fee. They'd be a separate 1,200 item.",
      written: "Thanks for the note about the social templates. Looking at our agreement, the scope covers the five website pages and the style guide, so the templates would be additional. I can add them for 1,200 and deliver within the current timeline, or we can schedule them as a phase-two item. Which would you prefer?",
      message: "Templates are outside the current scope — 1,200 to add, or we park them for phase 2?",
    },
    reactions: [
      { ifThey: "say it's only small", counter: "Agree it may be quick, then explain small items accumulate and give the cost or a swap option." },
      { ifThey: "insist it was always included", counter: "Share the scope line from the agreement and ask how they read it." },
    ],
    secondMove: "If the client wants it without extra cost, use Swap, Don't Stack.",
    followUp: "Log each agreed change in a running change list shared with the client.",
    mistakes: ["Doing the extra work first and raising it later.", "Using an irritated tone that makes the client defensive."],
    ethicalBoundary: "Base the flag on the actual agreement. Retroactively narrowing scope to charge more is unfair.",
    risk: "low", walkAway: ["The client routinely expects out-of-scope work for free after it has been named."],
    example: "A UX designer received a request to 'quickly' design an admin dashboard. She replied naming it as additional and offering a quote; the client chose to defer it, saving her an estimated 30 unpaid hours.",
    related: ["mv_038", "mv_041", "mv_028"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_038", number: 38, slug: "quote-the-change-before-doing-it", title: "Quote the Change Before Doing It",
    summary: "Give a written price and timeline impact for any change request before starting work on it, so nothing extra happens without agreement.",
    category: "scope", situations: ["client_scope", "pricing", "vendor"],
    goals: ["protect_value", "gain_commitment"], channels: ["email", "chat"],
    relationships: ["client", "vendor"], urgency: ["today", "this_week"],
    principle: "Work started before it is priced is work you will struggle to bill.",
    whyItWorks: "Once a change is delivered, its value to the client drops and their willingness to pay goes with it. A short written quote before starting — cost plus timeline effect — gives a clean yes or no, protects both parties from surprise invoices and creates a record of agreed changes.",
    whenToUse: ["A client sends a change request mid-project.", "You have been surprised by disputed invoices for extras before."],
    whenNotToUse: ["Your contract includes a defined allowance for minor changes and this fits within it.", "The change fixes your own error."],
    signals: ["You start extra tasks to 'save time' and bill later.", "Final invoices often lead to tense conversations."],
    preparation: ["Create a one-paragraph change-quote template: change, cost, timeline impact, approval line.", "Agree with the client at kickoff that changes will be quoted first."],
    steps: ["Acknowledge the change request.", "Send cost and timeline impact in writing within one working day.", "Wait for written approval.", "Start only after approval and log it."],
    openingLine: "I'll send a quick change quote so you can decide before I start.",
    scripts: {
      default: "Adding the French translation is 1,800 and moves launch by four days. Reply 'approved' and I'll begin.",
      diplomatic: "Happy to add the translation. So there are no surprises later, here's the cost and the effect on timing — just confirm and I'll get started.",
      direct: "Translation: 1,800, plus four days. Approve to proceed.",
      firm: "I'll begin the translation once the 1,800 change is approved in writing.",
      written: "Change request: French translation of all pages. Cost: 1,800. Timeline impact: launch moves from the 10th to the 14th. To approve, reply to this email with 'approved' and I'll schedule the work. If you'd rather keep the original launch date, we can schedule the translation after launch instead.",
      message: "Change quote: FR translation 1,800, +4 days. Reply 'approved' to go ahead.",
    },
    reactions: [
      { ifThey: "ask you to start while they get approval", counter: "Offer to hold the slot for 48 hours, but begin only once approved." },
      { ifThey: "reject the cost", counter: "Offer a reduced version or schedule it for a later phase." },
    ],
    secondMove: "If approvals stall the project, use Make the Default Explicit for pending changes.",
    followUp: "Keep a cumulative change log and include it with each invoice.",
    mistakes: ["Quoting verbally only.", "Treating silence as approval."],
    ethicalBoundary: "Quote realistically. Inflating change prices because the client is dependent on you mid-project is opportunistic.",
    risk: "low", walkAway: ["The client refuses to approve or pay for changes but continues to request them."],
    example: "A builder adopted written change quotes. When a homeowner asked for an extra window, the 1,400 quote went out the same day. She approved it, and the final invoice was paid without dispute.",
    related: ["mv_037", "mv_067", "mv_018"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_039", number: 39, slug: "offer-a-phase-two", title: "Offer a Phase Two",
    summary: "Turn new ideas that arrive mid-project into a planned next phase, protecting the current deadline while keeping the client's ambition alive.",
    category: "scope", situations: ["client_scope", "partnership"],
    goals: ["protect_value", "gain_commitment"], channels: ["email", "video", "in_person"],
    relationships: ["client", "partner"], urgency: ["this_week", "exploring"],
    principle: "'Not now' lands better than 'no' when it comes with a date.",
    whyItWorks: "Clients add ideas because they are enthusiastic. Refusing them deflates the relationship; absorbing them breaks the timeline. A phase two acknowledges the value of the idea, protects the current delivery and often creates the next paid engagement.",
    whenToUse: ["New feature requests threaten the current launch date.", "The client is excited and generating ideas faster than you can deliver."],
    whenNotToUse: ["The new item is critical to the current goal and must be included now.", "You do not want further work with this client."],
    signals: ["Every review meeting adds features.", "The launch date has already slipped once."],
    preparation: ["Keep a 'phase two' list visible to the client.", "Estimate roughly what phase two might cost and when it could start."],
    steps: ["Welcome the idea.", "Explain the impact of adding it now.", "Propose adding it to phase two with a target start date.", "Confirm the current scope and date stay unchanged."],
    openingLine: "That's a strong idea. Can we put it in phase two so it doesn't delay the launch?",
    scripts: {
      default: "The loyalty programme is a great idea. If we add it now, launch moves by a month. I'd suggest we make it the centrepiece of phase two, starting in June.",
      diplomatic: "I love where this is going. To protect the launch you're counting on, could we capture the loyalty idea for a phase two? I'll keep a running list.",
      direct: "Adding it now delays launch a month. Let's put it in phase two.",
      firm: "The current scope is fixed to hit the launch. The loyalty programme goes in phase two.",
      written: "Thanks for sharing the loyalty programme idea — I think it could be valuable. Including it in the current build would move launch by about four weeks. I'd recommend we keep the launch date and make it the first item for phase two, which could start in early June. I've added it to the shared phase-two list.",
      message: "Love the loyalty idea — adding to phase 2 so launch stays on track?",
    },
    reactions: [
      { ifThey: "insist it must be in launch", counter: "Ask what else could move out to make room, or agree a new date in writing." },
      { ifThey: "welcome the phase-two idea", counter: "Ask whether they want an outline and estimate for phase two now or after launch." },
    ],
    secondMove: "Near launch, use Propose the Next Step Yourself to schedule the phase-two conversation.",
    followUp: "Share the phase-two list at launch with an outline and estimate.",
    mistakes: ["Promising phase two without any timeline.", "Treating phase two as a way to dismiss ideas permanently."],
    ethicalBoundary: "Only propose phase two items you would genuinely be willing to deliver. Using it as a polite fiction erodes trust.",
    risk: "low", walkAway: ["The client refuses any phasing and demands unlimited additions at a fixed price."],
    example: "An app agency kept a visible phase-two board during a build. At launch the client had nine items on it and signed a second contract worth 40% of the first.",
    related: ["mv_037", "mv_015", "mv_041"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_040", number: 40, slug: "write-the-out-of-scope-list", title: "Write the Out-of-Scope List",
    summary: "Put the things you are not doing into the agreement explicitly, so later disagreements are settled by the document rather than by memory.",
    category: "scope", situations: ["client_scope", "vendor", "partnership"],
    goals: ["clarity", "protect_value"], channels: ["email"],
    relationships: ["client", "vendor", "partner"], urgency: ["this_week", "exploring"],
    principle: "What is left unsaid in an agreement will later be assumed — usually in the other side's favour.",
    whyItWorks: "Scopes describe deliverables, but disputes arise in the grey areas around them. A short list of exclusions removes the most common misunderstandings before they happen, and gives both sides a neutral reference when a request appears.",
    whenToUse: ["You are drafting a proposal or statement of work.", "Previous projects had disputes about what was included."],
    whenNotToUse: ["The engagement is a flexible retainer intended to cover varied requests.", "The list would be so long it signals distrust."],
    signals: ["You have heard 'I assumed that was included' more than once.", "Your proposals list only deliverables."],
    preparation: ["Review past projects for the requests that caused disputes.", "Pick the five most likely exclusions for this engagement."],
    steps: ["Add an 'Not included' section to the proposal.", "List five to eight specific exclusions.", "Mention how excluded items can be added.", "Walk through the list briefly at kickoff."],
    openingLine: "To keep things clear, I've listed what's included and what isn't.",
    scripts: {
      default: "Not included: copywriting, stock photo purchases, hosting setup, and ongoing maintenance after launch. Any of these can be quoted separately.",
      diplomatic: "So we're aligned from the start, I've noted a few things that aren't part of this project. Happy to quote any of them if you'd like them added.",
      direct: "The proposal lists what's excluded: copy, stock photos, hosting and maintenance.",
      firm: "Exclusions are listed in the agreement. Those items require a separate quote.",
      written: "Section 4 — Not included in this project: (a) copywriting and content entry beyond the homepage; (b) purchase of stock imagery or fonts; (c) hosting and domain setup; (d) maintenance or updates after the 30-day post-launch window. Any of these can be added through a written change quote.",
      message: "Just flagging section 4 of the proposal — lists what's not included so nothing surprises us.",
    },
    reactions: [
      { ifThey: "question an exclusion", counter: "Discuss it now and either include it with a price or keep it excluded — both are better than ambiguity." },
      { ifThey: "sign without comment", counter: "Mention the list briefly at kickoff so it is remembered." },
    ],
    secondMove: "When an excluded request arrives, use Name the Scope Change and point to the list.",
    followUp: "Refine your exclusion list after each project based on what came up.",
    mistakes: ["Using vague exclusions like 'other work'.", "Hiding the list in fine print."],
    ethicalBoundary: "Make exclusions visible and plain. Burying them to win later disputes is not good faith.",
    risk: "low", walkAway: ["A client will not sign an agreement with any defined exclusions."],
    example: "A marketing consultant added a five-line exclusions section after losing hours to unpaid copywriting. In her next project the client asked for blog posts, saw the list, and requested a separate quote.",
    related: ["mv_028", "mv_037", "mv_004"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_041", number: 41, slug: "swap-dont-stack", title: "Swap, Don't Stack",
    summary: "When a client wants something added within the same budget or deadline, ask what should come out to make room.",
    category: "scope", situations: ["client_scope", "leadership_alignment"],
    goals: ["protect_value", "negotiate_terms"], channels: ["email", "video", "in_person"],
    relationships: ["client", "manager"], urgency: ["today", "this_week"],
    principle: "Fixed time and money mean every addition is also a subtraction.",
    whyItWorks: "Clients and managers often believe capacity is elastic. Asking 'what should we drop?' makes the trade-off visible and puts the prioritisation decision with the person who owns the budget, rather than leaving you to absorb it through overtime.",
    whenToUse: ["Budget and deadline are fixed but requests keep growing.", "A manager adds priorities without removing any."],
    whenNotToUse: ["There is genuine slack and the addition is easy to absorb.", "Asking would seem petty given the size of the request."],
    signals: ["Your task list grows but deadlines do not move.", "Everything is labelled 'top priority'."],
    preparation: ["List current deliverables with rough effort for each.", "Identify two items that could plausibly be removed or deferred."],
    steps: ["Acknowledge the new request.", "State the fixed constraint: budget or date.", "Ask which existing item should be removed or deferred.", "Confirm the revised list in writing."],
    openingLine: "I can add that. To keep the date, what should we take out?",
    scripts: {
      default: "I can add the pricing calculator. To keep the 30th, we'd need to drop either the FAQ section or the blog setup. Which matters less?",
      diplomatic: "Happy to take on the calculator. Since we're working to the 30th, could you help me decide which existing piece we can move to later?",
      direct: "Adding the calculator means removing something. FAQ or blog setup?",
      firm: "I can't add the calculator without removing something or moving the date. Your call which.",
      written: "Thanks for the calculator request. With the budget and the 30th launch fixed, adding it means removing an item of similar size. The two options I'd suggest are the FAQ section (could follow in week two after launch) or the blog setup. Let me know which you'd prefer to move and I'll update the plan.",
      message: "Can add the calculator — which should move out: FAQ or blog setup?",
    },
    reactions: [
      { ifThey: "say everything must stay", counter: "Present the choice again: more budget, a later date or a swap — it must be one of the three." },
      { ifThey: "choose an item to remove", counter: "Confirm the change in writing and update the plan the same day." },
    ],
    secondMove: "If they refuse all three options, use Name the Decision and escalate the trade-off to the budget owner.",
    followUp: "Keep the revised list visible so the swap is not forgotten later.",
    mistakes: ["Making the swap decision yourself without consulting.", "Accepting the addition and hoping to find time."],
    ethicalBoundary: "Present the trade-off honestly, without exaggerating the effort of the new request to avoid it.",
    risk: "low", walkAway: ["Additions are demanded continuously with no change to time, money or scope."],
    example: "An engineer whose manager added a reporting feature asked which of her two current projects to pause. The manager paused the less urgent one; the new feature shipped on time without weekend work.",
    related: ["mv_033", "mv_037", "mv_013"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_042", number: 42, slug: "reset-after-scope-creep", title: "Reset After Scope Creep",
    summary: "When scope has already drifted, hold one structured conversation that lists what changed and agrees a new baseline going forward.",
    category: "scope", situations: ["client_scope", "relationship_repair", "pricing"],
    goals: ["protect_value", "recover_relationship", "clarity"], channels: ["video", "in_person", "email"],
    relationships: ["client", "partner"], urgency: ["this_week"],
    principle: "You cannot undo creep that has happened, but you can stop it from becoming the contract.",
    whyItWorks: "Accumulated small favours slowly redefine the agreement. A reset meeting acknowledges what has been delivered beyond scope, avoids blame and makes a forward-looking agreement on scope, price or both. Clients usually respect it more than gradual resentment.",
    whenToUse: ["You have absorbed many small extras over weeks or months.", "The project is now unprofitable and resentment is building."],
    whenNotToUse: ["The extras were your own choice and you are happy with the relationship.", "The project ends in days and a reset would not change anything."],
    signals: ["You are doing significantly more than the original agreement for the same fee.", "You dread messages from this client."],
    preparation: ["List the extras delivered with rough time for each.", "Decide what you want: new fee, reduced scope or a return to the original agreement."],
    steps: ["Request a short meeting framed as a check-in on scope.", "Share the list neutrally, as facts.", "Propose the new baseline: revised fee or tighter scope.", "Confirm the reset in writing and apply it from the next period."],
    openingLine: "I'd like to take stock of how the work has evolved, so we can set things up well for the next quarter.",
    scripts: {
      default: "Over the last three months we've added weekly reports and ad management, which weren't in the original retainer. I'd like to either update the fee to 3,200 or return to the original scope from next month.",
      diplomatic: "I've really enjoyed how this work has grown. I want to make sure it stays sustainable, so I've listed what's been added and two ways we could set things up going forward.",
      direct: "The work has grown beyond the retainer. Either the fee goes to 3,200 or we return to the original scope.",
      firm: "From next month, the retainer either reflects the current scope at 3,200 or returns to the original list. I can't continue both at the current fee.",
      written: "Hi Ari — I'd like to suggest a short scope check-in. Since January, the work has expanded to include weekly performance reports and ad campaign management, alongside the original content plan. I've attached a summary. Going forward, I'd propose either (a) updating the retainer to 3,200 to cover the current scope, or (b) returning to the original content-only scope at the current fee. Both work for me; I'd just like us to choose one from next month.",
      message: "Could we do a 20-min scope check-in this week? Work has grown and I'd like to set it up well.",
    },
    reactions: [
      { ifThey: "say they didn't realise", counter: "Accept that sincerely; the goal is the new baseline, not blame for the past." },
      { ifThey: "push back on both options", counter: "Ask which deliverables matter most and build a third option around those." },
    ],
    secondMove: "After the reset, use Write the Out-of-Scope List for the new baseline.",
    followUp: "Send the agreed new scope within 24 hours and apply it from the agreed date.",
    mistakes: ["Demanding back-payment for past favours you agreed to.", "Raising it in anger after a single bad request."],
    ethicalBoundary: "Frame the reset forward. Retroactively billing for extras you never priced is generally unfair unless agreed.",
    risk: "medium", walkAway: ["The client rejects any new baseline and expects the expanded scope at the original fee."],
    example: "A social media manager listed six months of added tasks and offered two options. The client chose a 30% fee increase over losing the reports, and the relationship continued on clearer terms.",
    related: ["mv_037", "mv_078", "mv_035"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
];
