import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Objections, Concessions & Trades (Moves 55–60). */
export const TRADES: MoveInput[] = [
  {
    id: "mv_055", number: 55, slug: "trade-never-concede", title: "Trade, Never Concede",
    summary: "When asked to give something up, ask for something of comparable value in return, so every concession becomes an exchange.",
    category: "trades", situations: ["pricing", "offer", "vendor", "compensation"],
    goals: ["negotiate_terms", "protect_value"], channels: ["in_person", "phone", "email", "video"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["today", "this_week"],
    principle: "A concession given freely teaches the other side to ask for more; a trade teaches them that value has a price.",
    whyItWorks: "Unconditional concessions signal that your position was padded and invite further requests. Pairing every give with a get — 'if you can do X, I can do Y' — keeps the deal balanced, slows down escalating demands, and often reveals what the other side values most.",
    whenToUse: ["The other side asks for a discount, extra feature or better terms.", "You have already made concessions and received nothing back."],
    whenNotToUse: ["A small goodwill gesture would strengthen a valued long-term relationship.", "The request corrects a genuine error on your side."],
    signals: ["Requests escalate after each concession.", "You have been saying 'okay' without asking for anything."],
    preparation: ["List items you can give and their value to you.", "List items you want from them: timing, volume, payment terms, references."],
    steps: ["Listen to the request fully.", "Respond with 'If you can…, then I can…'.", "Choose a get that matters to you and is reasonable for them.", "Confirm the trade explicitly before moving on."],
    openingLine: "That might be possible. If I do that, what can you do on your side?",
    scripts: {
      default: "If you can commit to a twelve-month contract instead of six, I can bring the monthly rate down to 1,850.",
      diplomatic: "I'd like to help with the rate. Would a longer commitment on your side be possible? That would let me offer 1,850.",
      direct: "1,850 is possible with a twelve-month commitment.",
      firm: "The rate stays at 2,000 for six months. 1,850 is only available on twelve months.",
      written: "Thanks for asking about the rate. I can offer 1,850 per month in exchange for a twelve-month agreement with payment on the 1st of each month. On the current six-month term, the rate remains 2,000. Let me know which you'd prefer.",
      message: "Can do 1,850/month on a 12-month term. Six months stays at 2,000.",
    },
    reactions: [
      { ifThey: "want the concession without the trade", counter: "Restate the trade calmly; offer an alternative get if the first is not possible." },
      { ifThey: "accept the trade", counter: "Confirm in writing immediately." },
    ],
    secondMove: "If they keep asking for more, use Concede Small, Slowly, and Last.",
    followUp: "Document each agreed trade so later discussions reference the full exchange.",
    mistakes: ["Asking for a trade so small it is meaningless.", "Making the trade sound like a threat."],
    ethicalBoundary: "Trades should be fair exchanges. Demanding disproportionate returns because the other side is under pressure is exploitation.",
    risk: "low", walkAway: ["The other side refuses any reciprocal commitment and continues to demand concessions."],
    example: "Asked for a 10% discount, a video producer offered it in exchange for upfront payment and permission to use the work in her portfolio. The client agreed, and cash flow improved.",
    related: ["mv_058", "mv_059", "mv_011"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_056", number: 56, slug: "label-the-objection", title: "Label the Objection",
    summary: "Name the concern you think is behind their pushback, so they feel heard and the real issue comes into the open.",
    category: "trades", situations: ["pricing", "difficult_conversation", "offer", "workplace_conflict"],
    goals: ["de_escalate", "clarity", "resolve_conflict"], channels: ["in_person", "phone", "video"],
    relationships: ["client", "manager", "colleague", "vendor"], urgency: ["today"],
    principle: "An objection named aloud loses half its force.",
    whyItWorks: "People repeat objections when they feel unheard. A tentative label — 'it sounds like the timing worries you' — demonstrates understanding, lowers defensiveness and invites correction. Correct labels open the real conversation; wrong ones are corrected, which is also useful.",
    whenToUse: ["The other side keeps raising the same concern in different forms.", "You sense frustration or worry that has not been stated directly."],
    whenNotToUse: ["The objection is already clear and stated; labelling would sound patronising.", "The setting is very formal and emotional labelling would be out of place."],
    signals: ["Repeated 'yes, but' responses.", "Tone shifts without a stated reason."],
    preparation: ["Listen for the emotion or concern behind the words.", "Prepare a tentative phrasing: 'it sounds like…', 'it seems…'."],
    steps: ["Pause your argument.", "Label the concern tentatively.", "Wait for confirmation or correction.", "Address the confirmed concern directly."],
    openingLine: "It sounds like the concern is less about price and more about whether this will work.",
    scripts: {
      default: "It sounds like the main concern is whether the team will actually use the new system, not the cost itself.",
      diplomatic: "I may be wrong, but it seems like there's some worry about the rollout disrupting the team. Is that right?",
      direct: "Sounds like adoption is the real concern. Is it?",
      firm: "It seems the concern is adoption. If so, let's address that directly instead of the price.",
      written: "Thanks for your notes. Reading them, it seems the main concern may be whether the team will adopt the new system during a busy quarter, rather than the cost itself. If that's right, I'd suggest we discuss a phased rollout. If I've misread it, please let me know.",
      message: "Reading your note — is the main worry adoption rather than cost?",
    },
    reactions: [
      { ifThey: "confirm the label", counter: "Thank them and address that specific concern with a concrete proposal." },
      { ifThey: "correct you", counter: "Thank them for clarifying and label the corrected concern back." },
    ],
    secondMove: "Once the concern is clear, use Trade, Never Concede or a targeted proposal to address it.",
    followUp: "Note the real concern in your recap so it is addressed in the plan.",
    mistakes: ["Labelling in a way that accuses ('you're just scared').", "Using labels mechanically without listening."],
    ethicalBoundary: "Label to understand, not to manipulate. Pretending empathy to lower someone's guard while ignoring their concern is dishonest.",
    risk: "low", walkAway: ["Even after concerns are named and addressed, objections keep changing without engagement."],
    example: "A software rep heard 'it's too expensive' three times. She said, 'It sounds like you're worried about justifying this to your board.' The buyer agreed, and she provided a one-page business case that closed the deal.",
    related: ["mv_011", "mv_009", "mv_074"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_057", number: 57, slug: "ask-compared-to-what", title: "Ask 'Compared to What?'",
    summary: "When told your offer is too expensive or too slow, ask what they are comparing it to, so you respond to the real benchmark.",
    category: "trades", situations: ["pricing", "vendor", "offer"],
    goals: ["clarity", "negotiate_terms"], channels: ["in_person", "phone", "email"],
    relationships: ["client", "vendor", "employer"], urgency: ["today", "this_week"],
    principle: "'Too much' always has a hidden comparison; find it before you respond.",
    whyItWorks: "Objections like 'too expensive' are judgements against a reference point — a competitor, a budget, last year's price, a guess. Asking for the comparison turns a vague complaint into specific information, and often reveals that the comparison is not like-for-like.",
    whenToUse: ["You hear 'that's too expensive' or 'that's too long'.", "You suspect a competitor quote is being used as leverage."],
    whenNotToUse: ["The comparison is already obvious and stated.", "Asking would seem combative given the relationship."],
    signals: ["Objections are vague and unexplained.", "Competitors are mentioned without details."],
    preparation: ["Know your main competitors' typical scope and pricing.", "Prepare a neutral phrasing of the question."],
    steps: ["Acknowledge the objection.", "Ask what they are comparing to.", "Compare scope and terms like-for-like.", "Adjust, differentiate or hold based on the comparison."],
    openingLine: "That's helpful to know. What are you comparing it to?",
    scripts: {
      default: "Thanks for being direct. When you say it's high, what are you comparing it to — another quote, or the budget you'd planned?",
      diplomatic: "I'd like to understand so I can help. Is there another proposal or a budget figure you're weighing this against?",
      direct: "Compared to what?",
      firm: "If there's a lower quote, I'd need to see the scope to compare. Otherwise the price reflects the work.",
      written: "Thank you for the feedback on pricing. To respond usefully, could you share what you're comparing it to — for example another proposal or an internal budget? If it's another quote, I'd be happy to compare scopes so you can see the differences clearly.",
      message: "Helpful to know — what are you comparing it against?",
    },
    reactions: [
      { ifThey: "share a cheaper quote", counter: "Compare scope line by line; if equal, decide whether to match; if not, explain the difference." },
      { ifThey: "cite an internal budget", counter: "Offer a tiered option that fits the budget." },
    ],
    secondMove: "If the comparison is a competitor, use Answer 'Your Competitor Is Cheaper'.",
    followUp: "Record common comparisons to refine your positioning.",
    mistakes: ["Asking in a defensive tone.", "Dismissing the comparison without looking at it."],
    ethicalBoundary: "Ask to understand, not to pressure them into revealing confidential competitor information.",
    risk: "low", walkAway: ["A like-for-like comparison shows your price is genuinely uncompetitive and you choose not to match."],
    example: "Told her quote was 'way too high', a caterer asked compared to what. The client was comparing against a drop-off buffet, not a staffed service. Once compared properly, the client booked.",
    related: ["mv_060", "mv_034", "mv_023"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_058", number: 58, slug: "concede-small-slowly-and-last", title: "Concede Small, Slowly, and Last",
    summary: "If you must give ground, make concessions in decreasing sizes, with time between them, and late in the negotiation.",
    category: "trades", situations: ["pricing", "offer", "compensation", "vendor"],
    goals: ["negotiate_terms", "protect_value"], channels: ["in_person", "phone", "email"],
    relationships: ["client", "employer", "vendor"], urgency: ["today", "this_week"],
    principle: "The pattern of your concessions tells the other side where your limit is.",
    whyItWorks: "Large, quick concessions signal there is much more to give. Shrinking concessions — 500, then 200, then 50 — communicate that you are approaching your limit, and spacing them out gives each one weight. Holding them until late keeps early discussion focused on value.",
    whenToUse: ["You are in a multi-round price or salary negotiation.", "You have room to move but want to protect most of it."],
    whenNotToUse: ["A single fair final offer would serve the relationship better.", "The counterpart is acting in clear good faith and gamesmanship would harm trust."],
    signals: ["You have already made one large concession.", "The other side keeps asking for 'a bit more'."],
    preparation: ["Plan your concession steps in advance, decreasing each time.", "Know where you stop: your floor."],
    steps: ["Hold your opening position as long as reasonable.", "Make a first moderate concession, tied to a trade.", "Make each subsequent concession smaller.", "State clearly when you have reached your final position."],
    openingLine: "I've looked again, and I can move a little, but not far.",
    scripts: {
      default: "I can come down to 11,500. That's close to the limit of what works for this scope.",
      diplomatic: "I've gone back over the numbers to find room. I can offer 11,500, and I'd really like that to work.",
      direct: "11,500. There isn't much more room.",
      firm: "11,500 is my final figure for this scope.",
      written: "Thanks for the discussion. Having reviewed the scope again, I can offer 11,500 for the full project, with payment in two instalments. This is close to the lowest price at which I can deliver the work to the standard we've discussed.",
      message: "Reviewed again — can do 11,500. That's close to the floor.",
    },
    reactions: [
      { ifThey: "ask for another round", counter: "Offer a much smaller step, or state that you have reached your final position." },
      { ifThey: "accept", counter: "Confirm immediately in writing." },
    ],
    secondMove: "At your floor, use Know Your Walk-Away Point to decide calmly.",
    followUp: "Record the concession path to learn for future negotiations.",
    mistakes: ["Conceding in equal steps, which suggests no limit.", "Calling a position 'final' and then moving again."],
    ethicalBoundary: "Only call a position final when it is. False finality destroys credibility in future negotiations.",
    risk: "medium", walkAway: ["Further concessions are demanded after your stated final position."],
    example: "A homeowner selling furniture moved from 900 to 800 to 760 to 750 and said 'that's it'. The buyer accepted 750; with equal steps he had previously ended at 600.",
    related: ["mv_055", "mv_019", "mv_031"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_059", number: 59, slug: "bundle-the-issues", title: "Bundle the Issues",
    summary: "Negotiate several terms together as a package rather than one at a time, so you can trade across them instead of losing each separately.",
    category: "trades", situations: ["offer", "vendor", "partnership", "compensation"],
    goals: ["negotiate_terms"], channels: ["in_person", "video", "email"],
    relationships: ["employer", "vendor", "partner", "client"], urgency: ["this_week"],
    principle: "Single issues create winners and losers; packages create trades.",
    whyItWorks: "Negotiating items one by one turns each into a zero-sum contest and lets the other side lock in early wins. Discussing salary, start date, flexibility and title together reveals what each side values most and lets you give on low-priority items to gain on high-priority ones.",
    whenToUse: ["Several terms are open at once (price, timeline, payment, scope).", "The other side wants to settle items one at a time."],
    whenNotToUse: ["Only one issue genuinely matters.", "Bundling would be used to hide an unfavourable term."],
    signals: ["Items are being closed one by one with you giving ground each time.", "You are unsure which terms the other side cares about most."],
    preparation: ["List all open terms and rank them by importance to you.", "Guess their ranking and where trades are possible."],
    steps: ["Propose discussing all terms together.", "Present a complete package.", "Invite them to suggest changes to the package as a whole.", "Adjust across items rather than conceding item by item."],
    openingLine: "Rather than settle each point separately, can we look at the whole package?",
    scripts: {
      default: "Before we agree salary, could we look at the full picture — base, start date, remote days and review timing — together?",
      diplomatic: "I think we'll find a better outcome if we look at all the terms together. Would you be open to that?",
      direct: "Let's agree the whole package, not item by item.",
      firm: "I'm not able to agree salary in isolation. I need to see the full package.",
      written: "Thank you for the updated offer. To make sure we land on terms that work for both sides, I'd suggest we consider the package as a whole: base salary, start date, remote working days and the timing of the first review. I've outlined a proposal below and I'm open to adjusting the balance between these items.",
      message: "Could we look at base, start date, remote days and review timing as one package?",
    },
    reactions: [
      { ifThey: "insist on one item first", counter: "Agree to discuss it first, but say agreement is conditional on the full package." },
      { ifThey: "propose a counter-package", counter: "Compare packages on your priority ranking and trade low-priority items." },
    ],
    secondMove: "Within the package, use Trade, Never Concede on each change.",
    followUp: "Confirm the full agreed package in a single written summary.",
    mistakes: ["Revealing your priority ranking too early.", "Bundling so many items it becomes confusing."],
    ethicalBoundary: "Present packages transparently. Bundling to obscure a bad term that the other side would otherwise reject is deceptive.",
    risk: "low", walkAway: ["No combination of terms meets your floor on your top priority."],
    example: "A candidate accepted a slightly lower base in exchange for two remote days, an earlier review and a better title. Negotiating salary alone, the company had refused to move at all.",
    related: ["mv_055", "mv_004", "mv_011"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_060", number: 60, slug: "answer-your-competitor-is-cheaper", title: "Answer 'Your Competitor Is Cheaper'",
    summary: "Respond to competitor price comparisons by clarifying the difference in what is delivered, rather than reflexively matching the lower number.",
    category: "trades", situations: ["pricing", "vendor"],
    goals: ["protect_value", "negotiate_terms"], channels: ["in_person", "phone", "email"],
    relationships: ["client", "vendor"], urgency: ["today", "this_week"],
    principle: "Matching a price you have not compared is conceding to a ghost.",
    whyItWorks: "Competitor comparisons are often incomplete: different scope, guarantees or quality. Calmly clarifying the difference lets the buyer make a real comparison, positions you as confident, and protects your margin. When the competitor genuinely is equivalent, you can choose to match deliberately.",
    whenToUse: ["A client says another provider is cheaper.", "You are losing deals on price without understanding why."],
    whenNotToUse: ["The competitor's offer is genuinely equivalent and you want the deal enough to match.", "You would need to disparage the competitor to make your case."],
    signals: ["Comparisons cite only a number, not scope.", "You feel pressure to match immediately."],
    preparation: ["Know your three main differentiators.", "Prepare a simple comparison checklist (scope, timeline, guarantees, support)."],
    steps: ["Thank them for sharing.", "Ask what the other quote includes.", "Highlight the differences factually.", "Decide whether to hold, adjust scope or match."],
    openingLine: "Thanks for telling me. Can we compare what each quote actually includes?",
    scripts: {
      default: "That's useful to know. Does their quote include the twelve months of support and on-site training? Ours does, which accounts for most of the difference.",
      diplomatic: "I appreciate you being open about it. I'd like to help you compare fairly — would it be useful to go through what's included in each?",
      direct: "Does their price include support and training? Ours does.",
      firm: "Our price includes support and training. We don't discount to match quotes that don't.",
      written: "Thanks for sharing that you've received a lower quote. To help you compare, our proposal includes: twelve months of support, on-site staff training, and a 90-day performance guarantee. If the other quote includes the same, I'm happy to review our pricing; if not, the difference largely reflects those items.",
      message: "Happy to compare — does their quote include support, training and the guarantee?",
    },
    reactions: [
      { ifThey: "confirm the competitor includes everything", counter: "Decide deliberately whether to match, differentiate further, or let it go." },
      { ifThey: "realise the scope differs", counter: "Ask which elements matter most and whether a tiered option fits." },
    ],
    secondMove: "If price remains the barrier, use Offer Tiers, Not Discounts.",
    followUp: "Track lost deals by reason to see whether a price change is genuinely needed.",
    mistakes: ["Criticising the competitor.", "Matching the price before understanding the scope."],
    ethicalBoundary: "Compare honestly and never misrepresent a competitor's offering. Disparagement is unprofessional and can carry legal risk.",
    risk: "low", walkAway: ["An equivalent competitor offer is cheaper and matching would put you below your floor."],
    example: "A cleaning firm told 'others charge 20% less' walked a facilities manager through supply, insurance and staff vetting included in their price. The manager stayed and later shared the comparison with her CFO.",
    related: ["mv_057", "mv_027", "mv_033"], access: "free", editorial: DRAFT_EDITORIAL,
  },
];
