import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Alignment & Commitment (Moves 61–66). */
export const COMMITMENT: MoveInput[] = [
  {
    id: "mv_061", number: 61, slug: "ask-for-the-specific-yes", title: "Ask for the Specific Yes",
    summary: "Request a concrete commitment — what, who, by when — rather than general agreement, so 'sounds good' turns into action.",
    category: "commitment", situations: ["commitment", "leadership_alignment", "client_scope"],
    goals: ["gain_commitment"], channels: ["in_person", "video", "email"],
    relationships: ["client", "manager", "colleague", "partner"], urgency: ["today", "this_week"],
    principle: "General agreement costs nothing; specific commitments cost something, which is why they matter.",
    whyItWorks: "People readily agree in principle and then do nothing because nothing specific was promised. Asking for a precise action with an owner and date tests whether agreement is real, makes follow-through more likely and surfaces hidden objections while you are still in the room.",
    whenToUse: ["Meetings end with nods but no actions.", "You need someone else to act for your work to progress."],
    whenNotToUse: ["The other side is still exploring and pressing for commitment would feel premature.", "You lack authority to hold them to the commitment and it would create false expectations."],
    signals: ["Responses like 'sounds good', 'let's do it', with no follow-through.", "Next steps are owned by 'we'."],
    preparation: ["Decide the exact action you need from them.", "Choose a realistic date."],
    steps: ["Summarise the agreement.", "Ask who will do the specific action.", "Ask by when.", "Repeat the commitment back and confirm in writing."],
    openingLine: "Great — so who will send the contract, and by when?",
    scripts: {
      default: "Great. So you'll send the signed contract to legal by Wednesday, and I'll schedule kickoff for the following Monday. Is that right?",
      diplomatic: "Wonderful, it sounds like we're aligned. Just so I can plan, could we agree who will send the contract and roughly when?",
      direct: "Who sends the contract, and when?",
      firm: "I need the signed contract by Wednesday to hold the Monday start.",
      written: "Thanks for the call — great to be aligned. To confirm next steps: you'll send the signed contract to legal by Wednesday the 7th; I'll then confirm kickoff for Monday the 12th. Let me know if anything in that timing needs to change.",
      message: "To confirm: you'll send the signed contract by Wed, I'll lock kickoff for Mon the 12th?",
    },
    reactions: [
      { ifThey: "hesitate on the date", counter: "Ask what would make a date realistic and agree on that." },
      { ifThey: "commit clearly", counter: "Thank them and send the written confirmation the same day." },
    ],
    secondMove: "If the commitment slips, use Name the Missed Commitment.",
    followUp: "Send the confirmation within two hours of the conversation.",
    mistakes: ["Assigning the action to 'we'.", "Accepting 'soon' as a date."],
    ethicalBoundary: "Ask for commitments the other person can genuinely make. Pressuring someone to promise beyond their authority sets them up to fail.",
    risk: "low", walkAway: ["Specific commitments are repeatedly avoided while general agreement continues."],
    example: "A partnerships lead ended a call by asking, 'Who will send the data sample, and when?' The partner named an analyst and Friday. It arrived Friday, unlike the three previous 'we'll get that over' promises.",
    related: ["mv_063", "mv_062", "mv_015"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_062", number: 62, slug: "set-the-next-checkpoint", title: "Set the Next Checkpoint",
    summary: "End each conversation by scheduling the next touchpoint with a date and purpose, so momentum does not depend on someone remembering.",
    category: "commitment", situations: ["commitment", "follow_up", "leadership_alignment"],
    goals: ["gain_commitment", "clarity"], channels: ["in_person", "video", "email"],
    relationships: ["client", "manager", "colleague", "partner", "report"], urgency: ["today", "this_week"],
    principle: "Momentum lives in the calendar, not in good intentions.",
    whyItWorks: "Without a scheduled next step, projects stall in the gap between conversations. A checkpoint with a date and a purpose creates a natural deadline for actions, gives a reason to follow up and reveals early when something is slipping.",
    whenToUse: ["Projects lose momentum between meetings.", "A decision is pending and could drift."],
    whenNotToUse: ["The work is complete and further meetings would waste time.", "The other side has asked for space and a checkpoint would feel intrusive."],
    signals: ["Weeks pass between updates with no plan.", "You often ask 'where are we with this?'."],
    preparation: ["Decide what needs to be true by the next checkpoint.", "Have calendar availability ready."],
    steps: ["Before the meeting ends, propose the next checkpoint date.", "State what should be done by then.", "Send the invite during or right after the meeting.", "Start the checkpoint by reviewing those actions."],
    openingLine: "Before we finish, let's put the next check-in in the diary.",
    scripts: {
      default: "Let's check in on the 21st. By then, we'll have the vendor shortlist and your feedback on the budget. Does 10am work?",
      diplomatic: "This has been really helpful. Would it be useful to set a quick check-in for the 21st to keep things moving?",
      direct: "Next check-in: the 21st, 10am. Shortlist and budget feedback by then.",
      firm: "We need a checkpoint on the 21st, otherwise the timeline slips. I'll send the invite now.",
      written: "Thanks for today. I've sent an invite for a 20-minute check-in on Thursday the 21st at 10am. By then: I'll share the vendor shortlist, and you'll send feedback on the draft budget. Let me know if the time doesn't suit.",
      message: "Sent an invite for a 20-min check-in Thu 21st — shortlist and budget feedback by then.",
    },
    reactions: [
      { ifThey: "say they will let you know when ready", counter: "Suggest a tentative date that can move, so it doesn't disappear." },
      { ifThey: "accept the checkpoint", counter: "Send the invite immediately." },
    ],
    secondMove: "If the checkpoint arrives and actions are not done, use Name the Missed Commitment.",
    followUp: "Send a short agenda the day before the checkpoint.",
    mistakes: ["Scheduling checkpoints with no stated purpose.", "Cancelling your own checkpoints."],
    ethicalBoundary: "Use checkpoints to support progress, not to monitor or pressure people excessively.",
    risk: "low", walkAway: ["Checkpoints are repeatedly cancelled with no new date."],
    example: "A consultant whose projects routinely stalled began ending every call by sending a checkpoint invite. Her average project duration dropped by three weeks.",
    related: ["mv_001", "mv_015", "mv_065"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_063", number: 63, slug: "get-the-owners-name", title: "Get the Owner's Name",
    summary: "Identify the single person accountable for each next step, so responsibility does not dissolve across a team or organisation.",
    category: "commitment", situations: ["commitment", "leadership_alignment", "vendor"],
    goals: ["gain_commitment", "clarity"], channels: ["in_person", "video", "email"],
    relationships: ["client", "vendor", "colleague", "partner"], urgency: ["today", "this_week"],
    principle: "If everyone owns it, no one does.",
    whyItWorks: "Group responsibility diffuses accountability; each person assumes someone else will act. A named owner for each action creates clear expectations, a person to follow up with and a natural escalation point if things slip.",
    whenToUse: ["Working with larger organisations where actions get lost.", "Next steps are assigned to 'the team' or 'procurement'."],
    whenNotToUse: ["The other side has a clear and functioning ownership process already.", "Asking would undermine a manager who prefers to assign tasks internally."],
    signals: ["Follow-ups go to group inboxes without response.", "You are unsure who to chase."],
    preparation: ["List the next steps that depend on the other side.", "Prepare to ask politely for a name for each."],
    steps: ["For each action, ask who will own it.", "Get a name and contact.", "Confirm the owner and date in writing.", "Follow up with that person directly."],
    openingLine: "Who's the best person for me to follow up with on this?",
    scripts: {
      default: "Who will own the security review on your side, so I know who to send the documentation to?",
      diplomatic: "I want to make this easy for your team. Could you let me know who'd be best placed to handle the security review?",
      direct: "Who owns the security review?",
      firm: "I need a named owner for the security review to keep the timeline.",
      written: "Thanks for confirming the next steps. To make sure I support the right people, could you let me know who will own (1) the security review and (2) contract sign-off on your side? I'll send each of them the relevant documents directly.",
      message: "Who's the best person for the security review? I'll send docs directly.",
    },
    reactions: [
      { ifThey: "say it's handled by a team", counter: "Ask who leads that team or who you should contact first." },
      { ifThey: "name someone", counter: "Introduce yourself to them directly, copying your main contact." },
    ],
    secondMove: "With an owner named, use Ask for the Specific Yes for their action.",
    followUp: "Send the named owner a short introduction within a day.",
    mistakes: ["Bypassing your main contact entirely.", "Accepting a department name as an owner."],
    ethicalBoundary: "Respect the organisation's structure. Going around your contact without their agreement can damage trust.",
    risk: "low", walkAway: ["No one can be named as accountable for a step that blocks the agreement."],
    example: "A vendor waited six weeks on 'procurement'. Asking for a named owner got her an introduction to a buyer, who approved the purchase order in four days.",
    related: ["mv_005", "mv_061", "mv_016"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_064", number: 64, slug: "confirm-in-their-words", title: "Confirm in Their Words",
    summary: "Ask the other side to state the agreement in their own words, so differences in understanding appear before they become disputes.",
    category: "commitment", situations: ["commitment", "leadership_alignment", "client_scope"],
    goals: ["clarity", "gain_commitment"], channels: ["in_person", "video", "phone"],
    relationships: ["client", "manager", "colleague", "partner"], urgency: ["today"],
    principle: "Agreement is only shared when both sides can describe it the same way.",
    whyItWorks: "People hear what they expect. Asking someone to restate the agreement — rather than you restating it — reveals misunderstandings that a simple 'yes' hides. It also increases their ownership, because people commit more to what they have said themselves.",
    whenToUse: ["Important agreements are reached verbally.", "Past agreements with this counterpart have been remembered differently."],
    whenNotToUse: ["The agreement is simple and asking would feel condescending.", "The setting is very senior and a written recap is more appropriate."],
    signals: ["Different people leave the same meeting with different conclusions.", "Agreements later 'change'."],
    preparation: ["Prepare a non-patronising way to ask, such as for their notes.", "Know the key terms you need to hear."],
    steps: ["Ask them to summarise what was agreed.", "Listen for differences from your understanding.", "Clarify any gaps immediately.", "Follow with a written recap."],
    openingLine: "Just so we're both clear, how would you describe what we've agreed?",
    scripts: {
      default: "Before we wrap up, could you summarise how you'd describe the agreement to your team? I want to make sure we're aligned.",
      diplomatic: "I find it helpful to check we heard the same thing. How would you put what we've agreed?",
      direct: "How would you summarise what we agreed?",
      firm: "Before we close, I need to hear your understanding of the terms.",
      written: "Thanks for today. To make sure we captured the same agreement, could you reply with your summary of the key points — scope, timeline and payment — as you'd describe them to your team? I'll compare with my notes and we can resolve any differences now.",
      message: "Could you send a 2-line summary of what we agreed as you'd tell your team?",
    },
    reactions: [
      { ifThey: "summarise differently", counter: "Thank them and resolve the difference immediately, before ending." },
      { ifThey: "summarise accurately", counter: "Confirm and send the written recap." },
    ],
    secondMove: "After they confirm the agreement in their own words, use Recap in Writing to fix it on the record.",
    followUp: "Send the written recap within 24 hours.",
    mistakes: ["Asking in a tone that implies they weren't listening.", "Ignoring small differences in their summary."],
    ethicalBoundary: "Use this to check understanding, not to trap someone into a commitment they did not intend.",
    risk: "low", walkAway: ["Fundamental differences in understanding cannot be resolved even after clarification."],
    example: "After a negotiation, a contractor asked the client to summarise. The client said 'and you'll handle permits' — not agreed. Catching it then avoided a costly dispute months later.",
    related: ["mv_009", "mv_067", "mv_061"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_065", number: 65, slug: "turn-maybe-into-a-date", title: "Turn Maybe into a Date",
    summary: "When someone says 'maybe later' or 'let's revisit', convert it into a specific date for the decision, so it does not become a permanent maybe.",
    category: "commitment", situations: ["commitment", "follow_up", "compensation", "promotion"],
    goals: ["gain_commitment", "clarity"], channels: ["in_person", "email", "video"],
    relationships: ["manager", "client", "employer", "partner"], urgency: ["this_week"],
    principle: "'Later' without a date usually means 'never'.",
    whyItWorks: "Vague deferrals are comfortable for the person deferring and costly for the person waiting. Asking for a date or condition — 'when would be the right time?' — converts avoidance into a commitment, or reveals that the answer is actually no.",
    whenToUse: ["Your request was met with 'let's revisit next quarter'.", "A client keeps saying 'maybe' to a proposal."],
    whenNotToUse: ["The other side has given a clear, reasoned timeline already.", "Pressing for a date would be insensitive given their circumstances."],
    signals: ["The same 'later' has been repeated across multiple conversations.", "No date or condition was attached to a deferral."],
    preparation: ["Decide what date or condition would be acceptable to you.", "Prepare to ask what would need to be true."],
    steps: ["Acknowledge the deferral.", "Ask for a specific date or the condition that would trigger the decision.", "Agree it explicitly.", "Put it in the calendar and confirm in writing."],
    openingLine: "I understand it's not the right moment. When would be?",
    scripts: {
      default: "I understand it's not possible this quarter. Can we agree to revisit on 15 January, after budgets are set?",
      diplomatic: "That makes sense given everything going on. Would it be all right to put a date in the diary so it doesn't get lost?",
      direct: "When exactly should we revisit this?",
      firm: "I'm happy to wait, but I need a date. Can we agree 15 January?",
      written: "Thanks for considering my request. I understand the timing isn't right this quarter. To make sure we come back to it, could we agree to revisit on 15 January, after budgets are finalised? I'll send a calendar invite.",
      message: "Understood on timing — can we lock in 15 Jan to revisit?",
    },
    reactions: [
      { ifThey: "won't commit to a date", counter: "Ask what would need to happen first; agree that condition as the trigger." },
      { ifThey: "agree a date", counter: "Send the invite immediately and prepare evidence for the revisit." },
    ],
    secondMove: "If the date passes without action, use Name the Missed Commitment.",
    followUp: "Send a short reminder a week before the agreed date.",
    mistakes: ["Accepting 'later' without a date.", "Reacting with visible frustration to the deferral."],
    ethicalBoundary: "Respect genuine reasons for delay. The aim is clarity, not to force a decision before the other side is able to make it.",
    risk: "low", walkAway: ["Repeated agreed dates pass without action or explanation."],
    example: "Told 'we'll discuss your promotion later in the year', an associate asked for a specific month and condition. They agreed October after the client audit. She was promoted in October.",
    related: ["mv_062", "mv_045", "mv_012"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_066", number: 66, slug: "close-the-loop-on-verbal-agreement", title: "Close the Loop on Verbal Agreement",
    summary: "Convert a verbal yes into a signed or written commitment quickly, before memories fade or circumstances change.",
    category: "commitment", situations: ["commitment", "offer", "vendor", "partnership"],
    goals: ["gain_commitment"], channels: ["email"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["today"],
    principle: "The gap between a spoken yes and a signed one is where deals die.",
    whyItWorks: "Verbal agreements are vulnerable to second thoughts, changed priorities and different recollections. Sending the formal document or confirmation while enthusiasm is high reduces friction, and a prompt process signals professionalism and seriousness.",
    whenToUse: ["A client or employer has said yes verbally.", "Deals have previously stalled between agreement and paperwork."],
    whenNotToUse: ["The other side has asked for time to review with advisors.", "Rushing paperwork would seem pushy in a sensitive situation."],
    signals: ["A verbal yes has not been followed by documents for days.", "You are waiting for them to send the paperwork."],
    preparation: ["Have the agreement template ready before the final conversation.", "Know exactly which terms were agreed."],
    steps: ["Thank them for the agreement.", "Send the written document within hours, not days.", "Make signing easy (e-signature, clear instructions).", "Follow up once if not signed within the agreed time."],
    openingLine: "Thank you — I'll send the agreement over this afternoon so we can get started.",
    scripts: {
      default: "Thanks for the yes! I'll send the agreement by 4pm today; it takes about two minutes to sign electronically.",
      diplomatic: "I'm really pleased we're going ahead. To make it easy, I'll send the agreement later today — let me know if anything needs adjusting.",
      direct: "Agreement coming today. Please sign by Friday so we can start Monday.",
      firm: "The start date depends on the signed agreement by Friday.",
      written: "Hi Nadia — thank you for confirming you'd like to go ahead. Attached is the agreement reflecting what we discussed: the full website project at 14,000, starting Monday the 3rd. You can sign electronically via the link below. Once signed, I'll send the kickoff schedule.",
      message: "Thanks! Agreement's in your inbox — e-sign link included. Starting Mon the 3rd once signed.",
    },
    reactions: [
      { ifThey: "request changes", counter: "Address them promptly and resend the same day if possible." },
      { ifThey: "go quiet after the verbal yes", counter: "Follow up once with a simple reminder and the link." },
    ],
    secondMove: "If signing stalls, use Follow Up After Silence.",
    followUp: "Send kickoff details immediately after signature.",
    mistakes: ["Waiting a week to send paperwork.", "Changing terms in the written version without flagging it."],
    ethicalBoundary: "The written document must match what was agreed verbally. Slipping in new terms exploits the other side's trust.",
    risk: "low", walkAway: ["A verbal yes is repeatedly not followed by any written commitment."],
    example: "A photographer used to send contracts 'within the week'. She switched to sending them within an hour of verbal agreement; her booking conversion rose and ghosting after verbal yeses almost disappeared.",
    related: ["mv_067", "mv_061", "mv_064"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
];
