import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Escalation (Moves 79–84). */
export const ESCALATION: MoveInput[] = [
  {
    id: "mv_079", number: 79, slug: "escalate-the-issue-not-the-person", title: "Escalate the Issue, Not the Person",
    summary: "When you must involve someone senior, frame the escalation around the problem and its impact, not around the other person's character.",
    category: "escalation", situations: ["escalation", "workplace_conflict", "vendor", "client_scope"],
    goals: ["prepare_escalation", "resolve_conflict"], channels: ["email", "in_person", "video"],
    relationships: ["manager", "colleague", "vendor", "client"], urgency: ["today", "this_week"],
    principle: "Escalate a problem and you get help; escalate a person and you get a fight.",
    whyItWorks: "Escalations that criticise people make the senior person defend or judge individuals. Framing around the issue, impact and options invites problem-solving, protects your reputation as fair, and makes it easier for the other party to cooperate afterward.",
    whenToUse: ["Direct attempts to resolve an issue have failed.", "The issue is significant enough to need senior attention."],
    whenNotToUse: ["You have not yet tried to resolve it directly.", "The matter involves misconduct that requires formal reporting channels."],
    signals: ["You are drafting a message about what someone 'always' does.", "The issue is blocking work and direct conversation has not helped."],
    preparation: ["Summarise the issue, impact and what you have tried.", "Prepare two possible solutions."],
    steps: ["Tell the other person you plan to escalate (where safe).", "Describe the issue and impact factually.", "Show what you have tried.", "Ask for a specific decision or support."],
    openingLine: "I'd like your help with an issue that's blocking the launch.",
    scripts: {
      default: "I need your help with the data access issue. It's delayed testing by two weeks. I've raised it with IT twice. Could you help prioritise it, or should we change the test plan?",
      diplomatic: "I'd appreciate your guidance on something that's affecting the launch. I've tried a few routes and I think it needs a decision above my level.",
      direct: "Data access is blocking testing. I need a decision on priority.",
      firm: "This has blocked testing for two weeks despite two requests. It needs your decision this week.",
      written: "Hi Morgan — I'd like your help with an issue affecting launch. Testing has been blocked for two weeks because the team doesn't have access to the staging data. I raised it with IT on the 2nd and 9th. Options: (a) prioritise the access request, or (b) test with synthetic data and accept a one-week delay in final validation. Could we decide by Friday?",
      message: "Could I get 10 minutes on the staging access issue? It's blocking testing.",
    },
    reactions: [
      { ifThey: "ask who is at fault", counter: "Stay factual about actions and timelines rather than character." },
      { ifThey: "make a decision", counter: "Confirm it in writing and inform those affected." },
    ],
    secondMove: "If the escalation stalls, use Escalate in Writing with a Timeline.",
    followUp: "Close the loop with everyone involved once resolved.",
    mistakes: ["Escalating without telling the other party first.", "Bringing a problem without options."],
    ethicalBoundary: "Escalate fairly and accurately. For harassment, discrimination or safety issues, use formal reporting channels and seek qualified advice.",
    risk: "medium", walkAway: ["Escalation produces no response and the issue continues to cause significant harm."],
    example: "A project lead escalated 'vendor delays' instead of 'the vendor manager is incompetent', with two options attached. Her director called the vendor's account head, and the delays were fixed within a week.",
    related: ["mv_080", "mv_081", "mv_082"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_080", number: 80, slug: "give-notice-before-escalating", title: "Give Notice Before Escalating",
    summary: "Tell the other party you intend to escalate and why, giving them a final chance to resolve the issue and avoiding the sense of ambush.",
    category: "escalation", situations: ["escalation", "workplace_conflict", "vendor"],
    goals: ["prepare_escalation", "resolve_conflict"], channels: ["email", "in_person", "phone"],
    relationships: ["colleague", "vendor", "client", "manager"], urgency: ["this_week"],
    principle: "Notice turns escalation from a betrayal into a process.",
    whyItWorks: "Going over someone's head without warning damages trust and invites retaliation. Advance notice shows fairness, often prompts resolution before escalation is needed, and if escalation does follow, the other party is less likely to feel ambushed or to dispute your account.",
    whenToUse: ["You have tried to resolve an issue and are about to involve someone senior.", "The relationship with the other party will continue."],
    whenNotToUse: ["Notice would create a risk to you or others, such as with misconduct.", "The issue is urgent and harm is immediate."],
    signals: ["You have raised the issue directly at least twice.", "You feel tempted to escalate quietly."],
    preparation: ["Decide who you will escalate to and when.", "Write a calm notice sentence."],
    steps: ["Remind them of the issue and previous attempts.", "State that you intend to escalate and to whom.", "Offer a final window for resolution.", "Escalate as stated if unresolved."],
    openingLine: "I wanted to let you know before I raise this with Jordan.",
    scripts: {
      default: "We've discussed the invoice delays twice. If we can't resolve it by Friday, I'll raise it with your finance director. I'd rather we fix it together.",
      diplomatic: "I'd really prefer to sort this out between us. If we can't by Friday, I think I'll need to involve your finance director, and I wanted you to hear that from me.",
      direct: "If this isn't resolved by Friday, I'll escalate to your finance director.",
      firm: "I'm escalating this to your finance director on Friday unless it's resolved.",
      written: "Hi Ellis — following our calls on the 3rd and 10th about the delayed invoices, I wanted to let you know that if the outstanding payments aren't resolved by Friday the 21st, I'll raise the matter with your finance director. I'd much prefer to resolve it with you directly, so please let me know if there's anything I can do to help.",
      message: "Heads up: if we can't fix the invoice delay by Fri, I'll need to loop in your finance director.",
    },
    reactions: [
      { ifThey: "resolve it quickly", counter: "Thank them and confirm the resolution in writing." },
      { ifThey: "react angrily", counter: "Stay calm, restate the reason and the timeline." },
    ],
    secondMove: "If unresolved, use Escalate the Issue, Not the Person.",
    followUp: "Inform them when you have escalated, as promised.",
    mistakes: ["Using notice as a threat in an aggressive tone.", "Giving notice and then not following through."],
    ethicalBoundary: "Do not give notice where it would put anyone at risk, such as in reports of misconduct or safety concerns.",
    risk: "medium", walkAway: ["Notice and escalation both fail to change a situation that seriously harms your interests."],
    example: "A freelancer told a client's project manager she would contact the finance director if a 60-day invoice remained unpaid by Friday. Payment arrived Thursday, and the relationship continued.",
    related: ["mv_079", "mv_084", "mv_053"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_081", number: 81, slug: "bring-options-upward", title: "Bring Options Upward",
    summary: "When escalating, present the senior decision-maker with two or three clear options and your recommendation, not just a problem.",
    category: "escalation", situations: ["escalation", "leadership_alignment"],
    goals: ["prepare_escalation", "gain_commitment"], channels: ["email", "in_person", "video"],
    relationships: ["manager", "employer", "client"], urgency: ["today", "this_week"],
    principle: "Leaders decide faster between options than they solve open problems.",
    whyItWorks: "Senior people are busy and often lack the detail to define solutions themselves. Bringing defined options with trade-offs and a recommendation makes the decision quick, shows judgement and keeps the solution grounded in your knowledge of the situation.",
    whenToUse: ["You need a decision from someone more senior.", "The issue has several possible solutions with trade-offs."],
    whenNotToUse: ["You genuinely do not know the options and need their input to define them.", "Only one option is viable; present it as a recommendation."],
    signals: ["Your escalations come back as 'what do you suggest?'.", "Decisions take weeks because leaders lack clear choices."],
    preparation: ["Define two or three realistic options.", "Note cost, risk and timing for each and choose a recommendation."],
    steps: ["State the problem in one sentence.", "Present the options with trade-offs.", "Give your recommendation and why.", "Ask for a decision by a specific date."],
    openingLine: "I need a decision on the launch, and I've set out three options.",
    scripts: {
      default: "The supplier can't deliver by the 1st. Options: delay launch two weeks, launch with the old packaging, or pay 3,000 for express production. I recommend the old packaging. Can you decide by Wednesday?",
      diplomatic: "I'd value your decision on a supplier issue. I've outlined three paths and my recommendation, but I'm keen to hear your view.",
      direct: "Three options for the supplier delay. I recommend option B. Decision needed Wednesday.",
      firm: "We must choose an option by Wednesday to keep any launch date. I recommend B.",
      written: "Hi Dev — the packaging supplier can't deliver before the 15th. Options: (A) delay launch two weeks — no extra cost, lost launch-week promotion; (B) launch with existing packaging — no delay, minor brand inconsistency; (C) express production — 3,000, launch on time. Recommendation: B, as it protects the promotion with minimal risk. Could you confirm a decision by Wednesday?",
      message: "Supplier delay: 3 options + my recommendation in your inbox. Need a call by Wed.",
    },
    reactions: [
      { ifThey: "choose a different option", counter: "Accept it, confirm the decision and implement fully." },
      { ifThey: "ask for more information", counter: "Provide it quickly and reconfirm the decision date." },
    ],
    secondMove: "After the decision, use Recap in Writing to inform everyone affected.",
    followUp: "Log the decision and rationale.",
    mistakes: ["Presenting too many options.", "Hiding your recommendation."],
    ethicalBoundary: "Present options honestly, including risks of your recommendation. Framing other options as worse than they are distorts the decision.",
    risk: "low", walkAway: ["Decisions are repeatedly deferred despite clear options."],
    example: "An operations manager facing a staffing gap brought three options and a recommendation to her director. The decision was made in five minutes; previous open-ended escalations had taken weeks.",
    related: ["mv_013", "mv_079", "mv_068"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_082", number: 82, slug: "escalate-in-writing-with-a-timeline", title: "Escalate in Writing with a Timeline",
    summary: "Put a significant escalation in writing with a factual timeline of events, so the issue is clear, documented and difficult to dismiss.",
    category: "escalation", situations: ["escalation", "workplace_conflict", "vendor", "client_scope"],
    goals: ["prepare_escalation"], channels: ["email"],
    relationships: ["manager", "employer", "vendor", "client"], urgency: ["this_week"],
    principle: "A dated timeline speaks more clearly than any summary of your frustration.",
    whyItWorks: "Verbal escalations are easily forgotten or misremembered. A written timeline of dated, factual events gives the decision-maker a clear picture, demonstrates your attempts to resolve the issue and creates a record if the matter progresses to formal processes.",
    whenToUse: ["Verbal escalation has not resolved a significant issue.", "The matter may need a formal record later."],
    whenNotToUse: ["The issue is minor and a written escalation would be disproportionate.", "The matter involves legal disputes where you should seek qualified advice first."],
    signals: ["You have raised an issue several times without resolution.", "There is disagreement about what happened when."],
    preparation: ["Assemble dated events from emails, logs and recaps.", "Keep each entry factual: date, event, impact."],
    steps: ["State the issue and what you are asking for at the top.", "List the timeline of dated events.", "Note what you have already tried.", "Request a specific response by a date."],
    openingLine: "I'd like to formally raise an issue and have set out the timeline below.",
    scripts: {
      default: "I'd like to formally raise the repeated delivery delays. Timeline below, with dates and impact. I'm asking for a recovery plan by the 30th.",
      diplomatic: "I want to make sure the delivery delays get the attention they need, so I've set out the timeline clearly. I'd welcome a conversation about a plan.",
      direct: "Formal escalation: delivery delays. Timeline attached. Recovery plan requested by the 30th.",
      firm: "This is a formal escalation of the delivery delays. I need a written recovery plan by the 30th.",
      written: "Subject: Escalation — repeated delivery delays (Order #4471). I'm raising the following formally and requesting a written recovery plan by 30 June. Timeline: 2 May — delivery due, not received; 5 May — raised with account manager, new date 12 May; 12 May — partial delivery (40%); 20 May — raised again, no new date given; 3 June — remaining 60% still outstanding. Impact: two customer launches delayed. I'd welcome a call this week to discuss.",
      message: "I've sent a formal escalation on the delivery delays with a full timeline by email.",
    },
    reactions: [
      { ifThey: "respond with a plan", counter: "Agree checkpoints to monitor it." },
      { ifThey: "dispute the timeline", counter: "Ask which entries differ and share the source emails." },
    ],
    secondMove: "If no adequate response arrives, use Use a Formal Deadline.",
    followUp: "Keep the timeline updated as events continue.",
    mistakes: ["Including opinions or adjectives in the timeline.", "Copying in too many people."],
    ethicalBoundary: "Keep the record accurate and complete, including your own delays. For legal or employment disputes, consult a qualified professional.",
    risk: "medium", walkAway: ["A documented escalation receives no meaningful response by the requested date."],
    example: "After three verbal complaints, a retailer sent her supplier's head of sales a dated timeline. A recovery plan arrived in three days, along with a discount on the delayed order.",
    related: ["mv_068", "mv_070", "mv_084"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_083", number: 83, slug: "involve-a-neutral-third-party", title: "Involve a Neutral Third Party",
    summary: "When two sides are stuck, propose bringing in someone neutral to facilitate, so the conversation moves forward without either side backing down.",
    category: "escalation", situations: ["workplace_conflict", "partnership", "escalation", "relationship_repair"],
    goals: ["resolve_conflict", "de_escalate"], channels: ["in_person", "video"],
    relationships: ["colleague", "partner", "manager", "client"], urgency: ["this_week", "exploring"],
    principle: "When two people can't move, a third person can move the conversation.",
    whyItWorks: "Deadlocks often persist because neither side wants to concede in front of the other. A neutral facilitator — a mutual manager, HR, a mediator or trusted peer — structures the conversation, ensures both are heard and lets people adjust positions without losing face.",
    whenToUse: ["Direct conversations have repeatedly failed.", "Both sides want resolution but are stuck."],
    whenNotToUse: ["The issue is simple and a third party would escalate it unnecessarily.", "The third party is not genuinely neutral."],
    signals: ["Conversations go in circles.", "Both sides feel unheard."],
    preparation: ["Identify a candidate both sides would trust.", "Agree what the third party's role will be: facilitate, not decide."],
    steps: ["Propose a facilitator as a way to help, not as a threat.", "Agree on who and the format together.", "Prepare a short summary of your view.", "Commit to the facilitated process."],
    openingLine: "I think we both want to fix this. Would it help to have someone neutral facilitate?",
    scripts: {
      default: "We've talked about this three times and we're still stuck. Would you be open to asking Sam to facilitate a conversation? Not to decide — just to help us both get heard.",
      diplomatic: "I really value working with you, and I think we've got stuck. Would it help to bring someone neutral in to facilitate?",
      direct: "Let's ask Sam to facilitate. We're stuck.",
      firm: "We need a facilitator to move forward. I'd like to arrange that this week.",
      written: "Hi Jamie — I think we both want to resolve the territory issue, and our conversations so far haven't got us there. Would you be open to a facilitated session with someone we both trust, such as Sam from Operations? Their role would be to help structure the conversation, not to decide. Let me know your thoughts.",
      message: "Would you be open to asking Sam to facilitate a chat about the territory issue?",
    },
    reactions: [
      { ifThey: "agree", counter: "Arrange it promptly and brief the facilitator jointly." },
      { ifThey: "refuse", counter: "Ask what would help instead, and keep the offer open." },
    ],
    secondMove: "After facilitation, use Reset the Working Agreement.",
    followUp: "Send a joint summary of what was agreed.",
    mistakes: ["Choosing a facilitator aligned with you.", "Framing the suggestion as 'you're the problem'."],
    ethicalBoundary: "Choose a genuinely neutral party. For formal disputes, use established processes and qualified mediators.",
    risk: "low", walkAway: ["Even facilitated conversations fail and the conflict continues to cause harm."],
    example: "Two co-founders deadlocked on hiring asked their lead investor to facilitate a two-hour session. They agreed a hiring plan neither had proposed and avoided a split.",
    related: ["mv_076", "mv_078", "mv_006"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_084", number: 84, slug: "use-a-formal-deadline", title: "Use a Formal Deadline",
    summary: "When informal efforts have failed, set a formal written deadline stating the action required and the consequence that will follow.",
    category: "escalation", situations: ["escalation", "vendor", "client_scope", "walk_away"],
    goals: ["prepare_escalation", "protect_value", "decide_walk_away"], channels: ["email"],
    relationships: ["vendor", "client", "partner"], urgency: ["this_week"],
    principle: "A deadline is only formal when the consequence is stated and real.",
    whyItWorks: "After repeated informal requests, a written deadline with a clear consequence signals the matter has changed status. It focuses the other side on a decision, gives them a final fair chance and creates a record if you need to act on the consequence.",
    whenToUse: ["Informal reminders and escalation have not worked.", "You are prepared to act on the consequence."],
    whenNotToUse: ["You are not willing or able to follow through.", "The matter has legal implications; consult a qualified professional first."],
    signals: ["Repeated requests have been ignored.", "The cost of waiting is rising."],
    preparation: ["Decide the action required, the date and the consequence.", "Confirm you can and will apply the consequence."],
    steps: ["Summarise the issue and previous attempts.", "State the action required and the date.", "State the consequence if not met.", "Apply the consequence as stated."],
    openingLine: "I'm writing to set a formal deadline for resolving this.",
    scripts: {
      default: "Despite our requests on 5, 12 and 19 May, invoice #312 remains unpaid. Please pay by 2 June. If it is not received, work on the next phase will stop and I will pursue the outstanding amount formally.",
      diplomatic: "I've really valued our work and I want to resolve this fairly. I do need to set a clear deadline: payment by 2 June. After that, I'll have to pause the next phase.",
      direct: "Payment by 2 June, or work stops.",
      firm: "This is a formal notice: payment by 2 June, or I will stop work and pursue the amount owed.",
      written: "Subject: Formal notice — overdue invoice #312. Invoice #312 for 6,800 was due on 30 April. I requested payment on 5, 12 and 19 May. Please arrange payment in full by 2 June. If payment is not received by that date, I will pause all work on phase two and take steps to recover the outstanding amount. I would prefer to resolve this directly, so please contact me if there's an issue.",
      message: "I've sent a formal notice by email: payment of #312 needed by 2 June.",
    },
    reactions: [
      { ifThey: "pay or resolve", counter: "Confirm and resume normally, without lingering resentment." },
      { ifThey: "miss the deadline", counter: "Apply the stated consequence promptly and notify them." },
    ],
    secondMove: "If the consequence is applied, use Step Back Without Burning the Bridge or Hand Over Cleanly.",
    followUp: "Record the notice and outcome.",
    mistakes: ["Stating consequences you won't enforce.", "Making threats that exceed your rights."],
    ethicalBoundary: "State only consequences you are entitled to apply. For debt recovery or contract termination, check your rights with a qualified professional.",
    risk: "high", walkAway: ["The formal deadline passes without resolution."],
    example: "A subcontractor owed 6,800 sent a formal notice with a work-stop consequence. Payment arrived the day before the deadline, after three months of informal reminders.",
    related: ["mv_080", "mv_082", "mv_086"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
];
