import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Decision Control (Moves 13–18). */
export const DECISION: MoveInput[] = [
  {
    id: "mv_013", number: 13, slug: "offer-two-paths", title: "Offer Two Paths",
    summary: "Present two acceptable options instead of one proposal, so the conversation becomes a choice rather than a yes-or-no verdict.",
    category: "decision", situations: ["client_scope", "pricing", "vendor", "boundary"],
    goals: ["protect_value", "negotiate_terms", "gain_commitment"], channels: ["in_person", "email", "video"],
    relationships: ["client", "vendor", "manager"], urgency: ["today", "this_week"],
    principle: "A single proposal invites rejection; two good options invite selection.",
    whyItWorks: "A lone proposal is judged against 'no'. Two options you can both live with shift the question to 'which', give the other side genuine control, and make the trade-off between them — usually scope versus price, or speed versus cost — visible without you having to argue it.",
    whenToUse: ["Scope has grown without an agreed change in price.", "The other side tends to reject first and think later."],
    whenNotToUse: ["You would be unhappy with either option.", "Options would confuse a decision that is genuinely binary."],
    signals: ["A 'small' addition keeps being requested.", "Previous single proposals were declined without counter-offers."],
    preparation: ["Design two options you would accept, differing on one clear axis.", "Price or schedule each option precisely."],
    steps: ["Acknowledge the request.", "Present Option A and Option B with the trade-off between them.", "Ask which serves them better.", "Confirm the choice in writing."],
    openingLine: "There are two good ways to do this — let me lay them out.",
    scripts: {
      default: "I'm glad to include the workshop. We can either keep the current fee and the original deliverables, or add the workshop and weekly reporting for an additional $3,200 and two more weeks. Which works better for you?",
      diplomatic: "I'd love to help with the workshop. To keep things fair on both sides, I see two ways we could do it — happy to walk through both and you can choose.",
      direct: "Two options: original scope at the current fee, or the expanded scope at $3,200 more. Which do you want?",
      firm: "The workshop isn't in the current scope. I can add it at $3,200, or we keep to the original plan. Those are the options.",
      written: "Thanks for asking about the workshop. Here are two options:\n\nOption A — Original scope (as agreed), current fee, delivery on the 28th.\nOption B — Original scope plus workshop and weekly reporting, +$3,200, delivery on the 11th.\n\nLet me know which you prefer and I'll update the agreement.",
      message: "Two ways to do it: keep current scope + fee, or add the workshop for +$3,200. Which do you prefer?",
    },
    reactions: [
      { ifThey: "ask for Option B at Option A's price", counter: "Restate that the difference reflects real work; offer to phase B if budget timing is the issue." },
      { ifThey: "ask for a third option", counter: "Consider it if it trades something real; otherwise re-present the two." },
      { ifThey: "choose an option", counter: "Thank them and confirm in writing the same day." },
    ],
    secondMove: "If they push for both, move to Trade, Never Concede and ask what they can give in return.",
    followUp: "Send a written confirmation of the option chosen and the revised terms.",
    mistakes: ["Making one option deliberately unattractive.", "Offering three or more options and creating paralysis."],
    ethicalBoundary: "Both options must be real and honestly priced. A decoy option is a manipulation, not a choice.",
    risk: "low", walkAway: ["They refuse both options and insist on the expanded scope at the original fee."],
    example: "A brand strategist was asked to 'also run a quick workshop'. She sent two options with prices; the client chose the original scope and booked the workshop as a separate engagement the next quarter.",
    related: ["mv_055", "mv_037", "mv_001"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_014", number: 14, slug: "set-the-decision-criteria-first", title: "Set the Decision Criteria First",
    summary: "Agree how a decision will be judged before discussing options, so the outcome rests on shared standards rather than persuasion.",
    category: "decision", situations: ["leadership_alignment", "vendor", "partnership", "promotion"],
    goals: ["clarity", "resolve_conflict", "gain_commitment"], channels: ["in_person", "video", "email"],
    relationships: ["manager", "colleague", "partner", "vendor"], urgency: ["this_week", "exploring"],
    principle: "Agree on the measuring stick before anyone holds up their option.",
    whyItWorks: "Once options are on the table, people defend their favourite and treat criteria as weapons. Agreeing criteria first — cost, risk, speed, fit — depersonalises the decision and lets options be compared on ground everyone has accepted.",
    whenToUse: ["A group is choosing between competing proposals.", "A promotion or evaluation lacks clear standards."],
    whenNotToUse: ["The decision is small and criteria-setting would be bureaucratic.", "Criteria are imposed by policy and not open to discussion."],
    signals: ["Debate focuses on who proposed what.", "People reject options for reasons that shift each meeting."],
    preparation: ["Draft three to five candidate criteria.", "Propose a rough weight for each."],
    steps: ["Pause discussion of options.", "Propose criteria and invite edits.", "Agree weights or a priority order.", "Score options against the agreed criteria."],
    openingLine: "Before we compare options, can we agree what a good decision looks like?",
    scripts: {
      default: "Before we compare vendors, can we agree on what matters most? I'd suggest total cost, implementation time and support quality — in that order. What would you change?",
      diplomatic: "Everyone has good options in mind. It might help to agree first on how we'll judge them, so it's not about whose idea it is.",
      direct: "Let's agree the criteria first, then compare.",
      firm: "I won't keep debating options without agreed criteria. Let's fix those now.",
      written: "Ahead of Thursday's decision, I'd like to propose criteria: (1) total three-year cost, (2) time to go live, (3) support quality. Please reply with any changes by Wednesday so we can compare options on the same basis.",
    },
    reactions: [
      { ifThey: "add criteria that favour their option", counter: "Accept reasonable ones and ask the group to rank them openly." },
      { ifThey: "want to skip straight to options", counter: "Ask for five minutes on criteria; it will save time later." },
    ],
    secondMove: "Once criteria are agreed, use Name the Decision with a date.",
    followUp: "Circulate the agreed criteria so later debates can refer to them.",
    mistakes: ["Choosing criteria designed to favour your preferred option.", "Leaving criteria unweighted."],
    ethicalBoundary: "Propose criteria you would accept even if your option lost.",
    risk: "low", walkAway: ["Agreed criteria are ignored when the outcome is decided."],
    example: "A director's team was split between two CRM vendors. Agreeing three weighted criteria first took fifteen minutes; scoring took another ten, and the losing side accepted the result.",
    related: ["mv_001", "mv_016", "mv_006"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_015", number: 15, slug: "propose-the-next-step-yourself", title: "Propose the Next Step Yourself",
    summary: "End every exchange by proposing the specific next action, owner and date, rather than waiting for the other side to define it.",
    category: "decision", situations: ["follow_up", "commitment", "client_scope", "offer"],
    goals: ["gain_commitment", "clarity"], channels: ["in_person", "phone", "video", "email"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["today", "this_week"],
    principle: "Whoever proposes the next step usually shapes it.",
    whyItWorks: "Conversations often end with vague goodwill. The first concrete proposal for what happens next tends to be accepted because it removes effort for everyone. It also prevents the other side from defining a slower or less favourable path by default.",
    whenToUse: ["Closing a meeting, call or email thread.", "A process has no clear next milestone."],
    whenNotToUse: ["The other side is formally responsible for setting the process.", "Proposing a step would feel presumptuous in a hierarchical setting — offer it as a suggestion instead."],
    signals: ["Meetings end with 'let's be in touch'.", "You are unsure what happens after today."],
    preparation: ["Know the next step you want before the meeting.", "Have two date options ready."],
    steps: ["Summarise the outcome of the conversation.", "Propose a specific next step.", "Name an owner and a date.", "Confirm in writing."],
    openingLine: "Shall I suggest a next step?",
    scripts: {
      default: "I suggest I send the revised proposal by Wednesday, and we meet Friday at 10 to confirm. Does that work?",
      diplomatic: "Would it help if I proposed a next step? I can send a revised draft by Wednesday, and we could find thirty minutes on Friday.",
      direct: "Next step: I send the proposal Wednesday, we decide Friday.",
      firm: "To keep this moving I'll send the proposal on Wednesday and I'll need a decision by Friday.",
      written: "Thanks for today. As next steps, I'll send the revised proposal by Wednesday the 9th, and I've suggested Friday the 11th at 10:00 to confirm. If another time suits better, just reply with it.",
      message: "Next step from me: proposal by Wed. Can we confirm Fri 10am?",
    },
    reactions: [
      { ifThey: "propose a later date", counter: "Ask what the later date depends on, and accept it if the reason is real." },
      { ifThey: "agree", counter: "Send a calendar invitation immediately." },
    ],
    secondMove: "If the agreed step slips, use Set the Next Checkpoint to re-anchor.",
    followUp: "Send the written confirmation within the hour.",
    mistakes: ["Proposing a step without an owner.", "Proposing a date that you cannot meet."],
    ethicalBoundary: "Propose steps you will actually take; do not use false deadlines.",
    risk: "low", walkAway: ["Every proposed next step is declined without an alternative."],
    example: "A job candidate ended a final interview by proposing she send references by Tuesday and that they speak Thursday. The recruiter agreed, and an offer arrived Thursday afternoon.",
    related: ["mv_062", "mv_001", "mv_067"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_016", number: 16, slug: "pre-wire-the-decision", title: "Pre-Wire the Decision",
    summary: "Brief key stakeholders individually before the formal meeting, so the meeting confirms a decision rather than starting a debate.",
    category: "decision", situations: ["leadership_alignment", "promotion", "partnership", "escalation"],
    goals: ["gain_commitment", "clarity"], channels: ["in_person", "phone", "video"],
    relationships: ["manager", "colleague", "partner"], urgency: ["this_week", "exploring"],
    principle: "Important decisions are rarely made in the meeting; they are confirmed there.",
    whyItWorks: "People resist surprises in public. Private conversations beforehand let stakeholders raise concerns without losing face, give you time to adjust the proposal, and let you know where support stands before the room convenes.",
    whenToUse: ["A proposal needs approval from a group.", "One stakeholder could derail the meeting."],
    whenNotToUse: ["Organisational norms treat pre-meeting lobbying as inappropriate.", "Pre-wiring would exclude people who are entitled to equal information."],
    signals: ["Previous proposals were derailed by an unexpected objection.", "You do not know where key people stand."],
    preparation: ["Use your stakeholder map to choose who to pre-wire.", "Prepare a one-page summary and the main question for each person."],
    steps: ["Meet each key person briefly before the meeting.", "Share the proposal and ask for concerns.", "Adjust the proposal where concerns are valid.", "Open the meeting by noting the input already received."],
    openingLine: "Before Thursday, I'd value your view on this so I don't miss anything.",
    scripts: {
      default: "Before Thursday's review, I wanted to walk you through the proposal and hear any concerns. I'd rather adjust it now than surprise anyone in the room.",
      diplomatic: "Your perspective on this matters a lot, and I'd like to hear it before the meeting rather than during it. Do you have fifteen minutes?",
      direct: "Can I get your view on the proposal before Thursday?",
      firm: "I'm taking this proposal to Thursday's meeting. I'd like your concerns now so we can address them.",
      written: "Hi Marcus — ahead of Thursday's review, I've attached a one-page summary of the proposal. I'd value fifteen minutes this week to hear any concerns so I can address them before the meeting. Would Tuesday or Wednesday afternoon work?",
    },
    reactions: [
      { ifThey: "raise a strong objection", counter: "Thank them, explore it, and decide whether to adjust or address it openly in the meeting." },
      { ifThey: "decline to engage", counter: "Respect it, and make sure the meeting materials address their likely concerns." },
    ],
    secondMove: "In the meeting, use Set the Decision Criteria First if debate reopens.",
    followUp: "Thank each person afterwards and note how their input changed the proposal.",
    mistakes: ["Presenting different versions of the proposal to different people.", "Pre-wiring allies only."],
    ethicalBoundary: "Give everyone the same facts. Pre-wiring is consultation, not secret deal-making.",
    risk: "medium", walkAway: ["A key stakeholder privately signals a firm veto you cannot address."],
    example: "A manager proposing a team restructure spoke with each of four peers individually. Two concerns led to changes; the meeting approved the plan in twenty minutes.",
    related: ["mv_005", "mv_014", "mv_064"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_017", number: 17, slug: "separate-deciding-from-discussing", title: "Separate Deciding from Discussing",
    summary: "Make it explicit whether a conversation is for exploring ideas or for making a decision, so no one leaves with mismatched expectations.",
    category: "decision", situations: ["leadership_alignment", "partnership", "workplace_conflict", "client_scope"],
    goals: ["clarity", "resolve_conflict"], channels: ["in_person", "video", "email"],
    relationships: ["manager", "colleague", "partner", "client"], urgency: ["today", "this_week"],
    principle: "Mixing exploration and commitment makes people either hold back ideas or mistake ideas for promises.",
    whyItWorks: "When participants don't know which mode they're in, some treat brainstorming as commitments and others treat decisions as suggestions. Naming the mode protects open thinking and makes commitments unmistakable.",
    whenToUse: ["People later disagree about what was 'decided'.", "Brainstorming sessions turn into arguments."],
    whenNotToUse: ["The meeting purpose is already clear and shared.", "Formality would stifle a quick, informal exchange."],
    signals: ["'I thought we agreed…' disputes after meetings.", "Ideas are shot down before they are fully described."],
    preparation: ["Decide in advance which mode the conversation is in.", "Plan a clear transition if moving from one to the other."],
    steps: ["State the mode at the start.", "Hold the mode during the conversation.", "Mark the transition explicitly if switching.", "Record decisions separately from ideas."],
    openingLine: "Just so we're aligned, today is for exploring options, not deciding.",
    scripts: {
      default: "To be clear about today: we're exploring options, not deciding. On Thursday we'll pick one. Does that work for everyone?",
      diplomatic: "I'd love us to think freely today without anyone feeling committed. Shall we treat this as exploration and save the decision for Thursday?",
      direct: "This meeting is for options. Decision is Thursday.",
      firm: "Nothing said today is a commitment. Decisions happen Thursday, in writing.",
      written: "Summary of today's discussion (exploratory — no decisions made): the options raised were A, B and C. We'll decide on Thursday the 14th. Decisions from that meeting will be recorded separately.",
    },
    reactions: [
      { ifThey: "try to lock in a decision during exploration", counter: "Note the proposal and add it to the decision agenda." },
      { ifThey: "agree", counter: "Keep the mode and enforce the transition later." },
    ],
    secondMove: "In the decision meeting, use Set the Decision Criteria First.",
    followUp: "Send separate notes for ideas and decisions.",
    mistakes: ["Announcing exploration mode and then holding people to things they said.", "Never actually holding the decision meeting."],
    ethicalBoundary: "Respect the mode you declared. Using exploratory comments as commitments breaks trust.",
    risk: "low", walkAway: ["Participants repeatedly reopen decisions that were explicitly made."],
    example: "Two co-founders kept fighting over 'decisions' neither remembered making. Labelling meetings as explore or decide, with written decision logs, ended the disputes within a month.",
    related: ["mv_014", "mv_067", "mv_001"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_018", number: 18, slug: "make-the-default-explicit", title: "Make the Default Explicit",
    summary: "State what will happen if no decision is made by a date, so silence produces a known result instead of indefinite drift.",
    category: "decision", situations: ["follow_up", "client_scope", "vendor", "commitment"],
    goals: ["gain_commitment", "protect_value"], channels: ["email", "chat", "phone"],
    relationships: ["client", "vendor", "partner"], urgency: ["today", "this_week"],
    principle: "When no one decides, the default decides — so choose the default openly.",
    whyItWorks: "Indefinite waiting usually costs the party that keeps working or holding capacity. Stating a reasonable default — 'if I don't hear by Friday, I'll proceed with Option A' — turns silence into a decision while still giving the other side full control to choose differently.",
    whenToUse: ["Approvals keep slipping.", "You are holding capacity or resources for someone."],
    whenNotToUse: ["The default would harm the other side if they simply missed the message.", "Contract terms require explicit approval for the action."],
    signals: ["Reminders are acknowledged but not answered.", "Your schedule is blocked by someone else's indecision."],
    preparation: ["Choose a default that is reasonable and reversible.", "Check that acting on it is permitted under your agreement."],
    steps: ["State the decision needed.", "Name the date.", "State the default action if no decision arrives.", "Follow through on the date."],
    openingLine: "If I don't hear back by Friday, here's what I'll do by default.",
    scripts: {
      default: "To keep things moving, if I don't hear from you by Friday I'll proceed with Option A as drafted. If you'd prefer Option B, just let me know before then.",
      diplomatic: "I know things are busy. So you don't have to worry about this, I'll go ahead with Option A on Friday unless you'd like something different.",
      direct: "No reply by Friday means I proceed with Option A.",
      firm: "I can only hold this slot until Friday. After that I'll release it to another project.",
      written: "Hi Lee — I'm holding the week of the 20th for your project. If I haven't heard by end of day Friday the 10th, I'll release the slot and we can look at the next available dates (currently mid-March). If you'd like to keep it, a quick 'yes' is all I need.",
      message: "Holding the 20th for you until Fri. No reply = I'll release it. Want to keep it?",
    },
    reactions: [
      { ifThey: "object to the default", counter: "Invite them to choose a different option now." },
      { ifThey: "stay silent", counter: "Act on the default as stated and inform them calmly." },
    ],
    secondMove: "After acting on the default, use Recap in Writing to confirm what happened.",
    followUp: "On the date, send a one-line note confirming the default was applied.",
    mistakes: ["Stating a default and then not following through.", "Choosing a default designed to punish."],
    ethicalBoundary: "Defaults must be reasonable, reversible where possible, and permitted by any agreement in place.",
    risk: "medium", walkAway: ["Silence continues after the default is applied, and the relationship has no further value."],
    example: "A photographer held a shoot date for a client who kept saying 'soon'. She stated she would release it Friday at 5pm; the client confirmed at 3pm with the deposit.",
    related: ["mv_043", "mv_015", "mv_067"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
];
