import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Leverage & Alternatives (Moves 19–24). */
export const LEVERAGE: MoveInput[] = [
  {
    id: "mv_019", number: 19, slug: "know-your-walk-away-point", title: "Know Your Walk-Away Point",
    summary: "Decide in advance the specific terms below which you will say no, so pressure in the moment cannot move you further than you meant to go.",
    category: "leverage", situations: ["offer", "compensation", "pricing", "walk_away"],
    goals: ["protect_value", "decide_walk_away"], channels: ["in_person", "phone", "video", "email"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["today", "this_week", "exploring"],
    principle: "A limit chosen calmly beforehand is worth more than any argument invented under pressure.",
    whyItWorks: "People concede most when they have not decided what they will refuse. A written walk-away point turns a vague discomfort into a rule, which stops gradual erosion through many small concessions and lets you stay warm in tone while remaining fixed on substance.",
    whenToUse: ["You are about to negotiate a fee, salary or contract term that matters to you.", "You have conceded more than intended in previous rounds with this counterpart."],
    whenNotToUse: ["You genuinely lack the information to set a sensible floor; learn it first.", "The relationship is purely exploratory and no terms are on the table yet."],
    signals: ["You cannot say, in one number, what deal you would decline.", "You notice yourself hoping they will not ask you to go lower."],
    preparation: ["Write your floor as a number or term plus the reason it is your floor.", "List what you will do instead if the floor is not met, so the limit is credible to you."],
    steps: ["Set the floor before any conversation begins and do not revise it mid-meeting.", "Open above the floor with a reasoned position.", "When an offer lands below the floor, say so plainly and restate what would work.", "If they stay below, end the round politely and take the alternative you prepared."],
    openingLine: "Let me be clear about what would and wouldn't work for me, so we don't waste each other's time.",
    scripts: {
      default: "I've thought carefully about this, and I can't take the role below 92,000. Above that, I'm flexible on how we structure it.",
      diplomatic: "I really want to find a way to make this work. To be transparent, there's a level below which I couldn't commit fully, and for me that's 92,000. Is there room to get there?",
      direct: "My floor is 92,000. Below that I'd have to decline.",
      firm: "I won't accept below 92,000. If that isn't possible, I'd rather we part on good terms now.",
      written: "Thank you for the offer. I've considered it carefully. To accept, I'd need a base salary of at least 92,000; I'm open on start date and on how the bonus is structured. If that's workable, I'd be glad to move forward quickly.",
      message: "Thanks — I'd need at least 92k base to say yes. Flexible on the rest.",
    },
    reactions: [
      { ifThey: "ask whether you'd consider slightly less", counter: "Repeat the floor without new justification and ask what else they can move instead." },
      { ifThey: "say the budget is fixed", counter: "Ask what is not fixed — start date, review timing, title — and trade on those, not the floor." },
      { ifThey: "meet the floor exactly", counter: "Accept cleanly. Do not reopen other points as a reflex once your real limit is met." },
    ],
    secondMove: "If they come in below the floor and will not move, use Step Back Without Burning the Bridge.",
    followUp: "After the negotiation, note whether your floor was realistic; adjust it for next time with evidence, not mood.",
    mistakes: ["Setting the floor during the conversation, under pressure.", "Revealing the floor as your opening number, leaving no room."],
    ethicalBoundary: "Do not claim a floor you do not actually hold or invent competing offers to justify it. A bluffed limit that gets called damages trust and leverage.",
    risk: "medium", walkAway: ["The final offer remains below your written floor after one honest restatement."],
    example: "A designer wrote 'no less than 6,500 for the brand package' on a card before a call. When the client offered 5,000 with 'exposure', she restated the 6,500 calmly and offered a smaller scope at 5,000 instead. They chose the full package at 6,500.",
    related: ["mv_020", "mv_085", "mv_086"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_020", number: 20, slug: "build-a-real-alternative", title: "Build a Real Alternative",
    summary: "Create a genuine option you could take if this deal fails, because leverage comes from what you can do without them, not from what you say.",
    category: "leverage", situations: ["offer", "vendor", "client_scope", "walk_away"],
    goals: ["protect_value", "negotiate_terms"], channels: ["in_person", "phone", "email"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["this_week", "exploring"],
    principle: "Your strength at the table is set by the quality of your next-best option away from it.",
    whyItWorks: "Counterparts sense dependence even when it is unspoken. When you hold a real alternative — another client, another supplier, another role — your tone, patience and willingness to ask all change. You stop negotiating from need and start negotiating from choice.",
    whenToUse: ["You feel you have to accept whatever this counterpart offers.", "A major negotiation is weeks away and you have time to prepare."],
    whenNotToUse: ["The alternative would require deceiving the counterpart or breaching an agreement.", "You are already committed and seeking alternatives would break a promise you made."],
    signals: ["Your income or project depends on a single counterpart.", "You avoid asking for anything because losing them would be catastrophic."],
    preparation: ["List three concrete alternatives and the realistic value of each.", "Take one practical step toward the strongest alternative this week."],
    steps: ["Identify your single best alternative and its actual terms.", "Improve it until it is credible to you, not just theoretical.", "Enter the negotiation knowing exactly when you would switch to it.", "Mention it only if needed, factually and without threat."],
    openingLine: "I want to make this work with you, and I also want to be honest that I have other options I'm weighing.",
    scripts: {
      default: "I'd prefer to work with you on this. I'm also talking with another supplier, so it would help to understand whether you can meet the delivery date.",
      diplomatic: "You're my first choice and I'd like to keep it that way. To be transparent, I have another option in progress, so I want to make sure we can align on terms.",
      direct: "I have another viable option. Can you match the delivery date?",
      firm: "If we can't agree on the delivery date this week, I'll go with the other supplier.",
      written: "Thank you for the proposal. You remain my preferred partner. I do have a second option under consideration that meets our 30-day delivery requirement, so I'd be grateful to know whether you can commit to the same date by Thursday.",
      message: "Still keen to go with you — is the 30-day delivery doable? Weighing another option.",
    },
    reactions: [
      { ifThey: "dismiss the alternative as inferior", counter: "Do not argue its merits. Say it meets your requirements and return to the open term." },
      { ifThey: "ask who the alternative is", counter: "Decline to name it politely; the details of other negotiations are not part of this one." },
    ],
    secondMove: "With a stronger alternative in hand, use Anchor First with a Reason on the terms that matter most.",
    followUp: "Keep the alternative warm even after you agree, so you are not fully dependent next time.",
    mistakes: ["Inventing an alternative you do not have.", "Mentioning the alternative as a threat in the first minute."],
    ethicalBoundary: "Only reference alternatives that exist. Fabricated offers are deception and can carry real professional and contractual consequences.",
    risk: "medium", walkAway: ["Your alternative clearly beats the best terms this counterpart will offer."],
    example: "A freelance developer earning 80% of income from one agency spent two weeks reconnecting with former clients and secured a smaller contract. At renewal she asked the agency for a 12% rate increase for the first time and got 8%.",
    related: ["mv_019", "mv_022", "mv_023"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_021", number: 21, slug: "mention-the-option-without-threat", title: "Mention the Option Without Threat",
    summary: "Let the other side know you have choices in a calm, factual sentence that informs rather than intimidates.",
    category: "leverage", situations: ["offer", "compensation", "vendor"],
    goals: ["negotiate_terms", "protect_value"], channels: ["in_person", "phone", "email"],
    relationships: ["employer", "vendor", "client"], urgency: ["today", "this_week"],
    principle: "Information about your options moves people; ultimatums about them harden people.",
    whyItWorks: "An alternative only helps if the other side knows it exists, but a threat triggers defence and pride. Stating the option as context — paired with a clear preference for them — gives them a reason to improve terms while leaving them a dignified way to do it.",
    whenToUse: ["You have a real alternative and the counterpart appears to assume you do not.", "An offer is close but not quite workable."],
    whenNotToUse: ["The counterpart has been fair and generous; mentioning options may sound ungrateful.", "Your alternative is weak and they could easily call it."],
    signals: ["They behave as if you have nowhere else to go.", "Terms have stalled and they see no reason to move."],
    preparation: ["Write one neutral sentence describing the option without names or figures you cannot share.", "Pair it with a sentence stating your preference for this deal."],
    steps: ["State your preference for working with them.", "Mention the option in one factual sentence.", "Name the specific term that would let you choose them.", "Stop talking and let them respond."],
    openingLine: "I'd genuinely rather work with you, so I want to share where things stand.",
    scripts: {
      default: "I'd much rather join your team. I do have another offer with a higher base, so if there's any flexibility on salary, it would make this an easy decision.",
      diplomatic: "This role is my first choice, and I want to be open with you: I've received another offer. I'd love to find a way to make this one work.",
      direct: "I have another offer at a higher base. Can you improve the salary?",
      firm: "I have a competing offer. I need the base to be closer to it to accept.",
      written: "Thank you again for the offer — I'm excited about the team and the work. In the interest of transparency, I have received another offer with a higher base salary. This role remains my preference, so if there is flexibility on base, I'd be glad to accept quickly.",
      message: "Really want to say yes — I do have another offer with a higher base. Any room?",
    },
    reactions: [
      { ifThey: "tell you to take the other offer", counter: "Thank them, reaffirm interest, and ask whether any non-salary terms could move." },
      { ifThey: "ask to see the other offer", counter: "Share the headline figure if comfortable, but not documents, and keep the focus on their terms." },
    ],
    secondMove: "If they improve terms partially, use Trade, Never Concede to close the remaining gap.",
    followUp: "Confirm any improved terms in writing before declining the other option.",
    mistakes: ["Exaggerating the other option's value.", "Repeating the mention several times, which turns information into pressure."],
    ethicalBoundary: "Describe the alternative accurately. Overstating it to extract concessions is misrepresentation.",
    risk: "medium", walkAway: ["They decline to move and the alternative is clearly better for you."],
    example: "A product manager told the hiring lead she preferred their company but had an offer 10% higher. She did not repeat it. Two days later the company raised the base by 6% and added an earlier review.",
    related: ["mv_020", "mv_055", "mv_019"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_022", number: 22, slug: "strengthen-your-position-before-asking", title: "Strengthen Your Position Before Asking",
    summary: "Improve the facts on your side — results, timing, options — before you make the request, instead of hoping persuasion will cover the gap.",
    category: "leverage", situations: ["compensation", "promotion", "pricing", "partnership"],
    goals: ["protect_value", "negotiate_terms"], channels: ["in_person", "video", "email"],
    relationships: ["employer", "manager", "client", "partner"], urgency: ["this_week", "exploring"],
    principle: "The best time to strengthen your hand is before anyone knows you are about to play it.",
    whyItWorks: "Requests succeed mostly on what is already true when they are made. A short preparation period — finishing a visible win, documenting results, aligning timing with budgets — raises the baseline so the conversation becomes a confirmation rather than a debate.",
    whenToUse: ["You plan to ask for a raise, promotion or rate change in the coming weeks.", "Your current case relies on effort rather than evidence."],
    whenNotToUse: ["The request is urgent and waiting would cause harm.", "Delaying is a way of avoiding the conversation indefinitely."],
    signals: ["You would struggle to name two concrete results to support your ask.", "Budget decisions are about to be made and you have not positioned yourself."],
    preparation: ["List the three facts that would make your request obviously reasonable.", "Identify which of those you can create or document within two weeks."],
    steps: ["Choose a target date for the request aligned to the decision calendar.", "Complete or document the strongest supporting result.", "Gather one external benchmark if relevant.", "Make the request with the evidence leading, not the need."],
    openingLine: "Before our review, I'd like to share a few results from this quarter that I think are relevant.",
    scripts: {
      default: "Over the last two quarters I've taken on the vendor portfolio and cut renewal costs by 14%. I'd like to discuss moving to senior level in this review cycle.",
      diplomatic: "I've really valued the chance to take on the vendor work. I've pulled together the results so far and would welcome your view on whether they support a move to senior.",
      direct: "I cut vendor costs 14% and lead the portfolio. I'm asking for a senior title this cycle.",
      firm: "The results justify a senior title. I'd like it addressed in this cycle rather than the next.",
      written: "Hi Priya — ahead of our review on the 20th, I've attached a one-page summary of the vendor portfolio work: a 14% reduction in renewal costs and two contracts consolidated. I'd like to use part of the review to discuss moving to senior level this cycle.",
      message: "Sending a 1-page summary of the vendor results before our review — want to discuss senior level.",
    },
    reactions: [
      { ifThey: "say the timing is wrong", counter: "Ask when the right time is and what evidence they would need by then." },
      { ifThey: "question one of the results", counter: "Thank them, clarify the measurement, and offer the source data." },
    ],
    secondMove: "If they agree in principle but stall, use Turn Maybe into a Date.",
    followUp: "Keep a running record of results so the next request needs less preparation.",
    mistakes: ["Preparing so long that the decision window closes.", "Leading with personal financial need instead of contribution."],
    ethicalBoundary: "Present results accurately, including shared credit. Claiming a team's work as solely yours undermines both trust and the case.",
    risk: "low", walkAway: ["Strong documented results are repeatedly acknowledged but never acted on."],
    example: "An analyst planned to ask for a raise in March. She waited three weeks to finish a pricing model the CFO used in a board deck, then made the request citing it. The raise was approved in the same budget round.",
    related: ["mv_030", "mv_004", "mv_020"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_023", number: 23, slug: "estimate-their-alternative", title: "Estimate Their Alternative",
    summary: "Work out what the other side will do if they do not agree with you, because their options set the real limits of the deal.",
    category: "leverage", situations: ["vendor", "pricing", "offer", "partnership"],
    goals: ["negotiate_terms", "clarity"], channels: ["in_person", "email", "phone"],
    relationships: ["client", "vendor", "employer", "partner"], urgency: ["this_week", "exploring"],
    principle: "You cannot price a deal well until you know what saying no would cost them.",
    whyItWorks: "Negotiators often overestimate the other side's options and underprice themselves. Researching what replacing you would actually involve — cost, delay, risk, switching effort — usually reveals more room than fear suggests, and occasionally warns you that your ask is unrealistic.",
    whenToUse: ["You are setting a price or salary and unsure how far you can go.", "The counterpart claims they have many easy alternatives."],
    whenNotToUse: ["Researching their alternatives would require confidential information you should not access.", "Terms are already agreed and the analysis would only fuel regret."],
    signals: ["They mention competitors frequently but vaguely.", "You have no idea what it would cost them to start again with someone else."],
    preparation: ["List what replacing you would require: time, onboarding, risk, money.", "Find one public data point on market rates or competitor pricing."],
    steps: ["Estimate their realistic alternative and its full cost.", "Compare it to your proposal.", "Position your terms just inside the value they would lose by switching.", "If asked, describe switching costs factually rather than as warnings."],
    openingLine: "Can I ask what you'd do if we couldn't reach an agreement here?",
    scripts: {
      default: "If we don't renew, what would the transition look like on your side? I want to make sure our proposal reflects the full picture.",
      diplomatic: "I'd love to understand your options so our proposal is genuinely competitive. If you moved to another provider, what would matter most in that change?",
      direct: "What is your alternative if we don't agree?",
      firm: "Switching now would mean a six-week migration during your busiest season. Our terms reflect that continuity.",
      written: "Thanks for sharing the renewal concerns. As you weigh options, it may help to factor in the migration effort: our records indicate roughly six weeks of data transfer and retraining. We've priced the renewal to make continuity the lower-risk choice, and I'm happy to walk through it.",
      message: "Happy to talk renewal — what would a switch look like on your end timing-wise?",
    },
    reactions: [
      { ifThey: "claim switching is easy", counter: "Ask what the transition plan would be; vague answers suggest the alternative is weaker than stated." },
      { ifThey: "share a real competitor quote", counter: "Compare like-for-like scope, then decide whether to match, differentiate or step back." },
    ],
    secondMove: "If their alternative is weak, use Present the Price Without Apology on your proposed terms.",
    followUp: "Record what you learned about their alternatives; it informs the next renewal.",
    mistakes: ["Assuming their alternative is as costly as you hope.", "Using switching costs as a threat rather than a fact."],
    ethicalBoundary: "Estimate from legitimate sources. Do not obtain competitor or counterpart confidential information through deception.",
    risk: "low", walkAway: ["Their realistic alternative is clearly cheaper and better for them than any terms you can sustain."],
    example: "A small agency facing a 'we can get it cheaper' renewal mapped the client's switching costs: rebuilding twelve integrations and retraining staff. They held their price and offered a two-year lock; the client renewed.",
    related: ["mv_020", "mv_060", "mv_031"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_024", number: 24, slug: "make-your-value-hard-to-replace", title: "Make Your Value Hard to Replace",
    summary: "Build specific, visible contributions that would be costly to lose, so your leverage rests on real dependence rather than personal charm.",
    category: "leverage", situations: ["client_scope", "compensation", "partnership", "promotion"],
    goals: ["protect_value"], channels: ["in_person", "email", "video"],
    relationships: ["client", "employer", "manager", "partner"], urgency: ["exploring"],
    principle: "Leverage is quiet until the day someone imagines working without you.",
    whyItWorks: "People rarely value general effort, but they notice specific losses: the person who knows the system, holds the key relationship or produces a result nobody else can. Making those contributions visible and documented converts invisible effort into recognised value.",
    whenToUse: ["You feel interchangeable in a client relationship or role.", "You plan to negotiate terms within the next several months."],
    whenNotToUse: ["You would need to withhold information or hoard knowledge to create dependence.", "Your goal is to leave soon and a clean handover matters more."],
    signals: ["Your work is described in generic terms by others.", "Nobody would notice for a week if you stopped a key task."],
    preparation: ["Identify the one result you deliver that is hardest for someone else to reproduce.", "Decide how to make it visible: a report, a demo, a regular update."],
    steps: ["Pick one distinctive contribution to deepen.", "Make it visible with a short, regular summary to the decision-maker.", "Link it to an outcome they care about.", "Reference it naturally when terms come up."],
    openingLine: "I wanted to share a quick update on the onboarding system, since it now touches every new client.",
    scripts: {
      default: "Quick update: the onboarding process I rebuilt now handles all new accounts and has cut setup time from ten days to four.",
      diplomatic: "I thought you'd find this useful — the onboarding rebuild is now used for every new account, and setup time has dropped from ten days to four.",
      direct: "Onboarding now takes four days instead of ten. I own that process.",
      firm: "The onboarding process I run is now central to every account. I'd like that reflected when we discuss the renewal.",
      written: "Hi Marco — a short monthly update. The onboarding system now covers all new accounts; average setup time is four days, down from ten. I've documented it so the team can follow it, and I'll keep improving the steps that still cause delays.",
      message: "Monthly note: onboarding at 4 days vs 10 before. Doc's in the shared drive.",
    },
    reactions: [
      { ifThey: "take the contribution for granted", counter: "Keep reporting the outcome, not the effort, until it is linked to your name." },
      { ifThey: "ask you to train others on it", counter: "Agree generously; being the source of expertise is itself valuable and ethical." },
    ],
    secondMove: "When terms are discussed, use Strengthen Your Position Before Asking with this contribution as the lead fact.",
    followUp: "Update the summary monthly so the record exists before it is needed.",
    mistakes: ["Hoarding knowledge to create artificial dependence.", "Describing effort instead of the outcome it produces."],
    ethicalBoundary: "Value should come from what you contribute, not from withholding. Never make yourself 'irreplaceable' by hiding information others need.",
    risk: "low", walkAway: ["A clearly valuable contribution is consistently acknowledged but never reflected in terms."],
    example: "An operations lead sent a three-line monthly note on the reporting system she maintained. When contract renewal came, the client's VP quoted her notes in arguing to keep her team at the existing rate.",
    related: ["mv_030", "mv_022", "mv_025"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
];
