import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Boundaries (Moves 49–54). */
export const BOUNDARIES: MoveInput[] = [
  {
    id: "mv_049", number: 49, slug: "state-the-limit-once-clearly", title: "State the Limit Once, Clearly",
    summary: "Express your boundary in one plain sentence, without lengthy justification, so it is understood as a decision rather than an opening bid.",
    category: "boundaries", situations: ["boundary", "workplace_conflict", "client_scope"],
    goals: ["set_boundary"], channels: ["in_person", "email", "chat"],
    relationships: ["client", "manager", "colleague", "partner"], urgency: ["today", "this_week"],
    principle: "A boundary explained at length sounds like a request for permission.",
    whyItWorks: "Long justifications invite debate about each reason. A short, calm statement of what you will and will not do is easier to respect and harder to argue with. Clarity reduces the chance the boundary is misunderstood and spares both sides repeated negotiation.",
    whenToUse: ["Someone repeatedly asks for something you are not willing to give.", "You find yourself over-explaining a decision."],
    whenNotToUse: ["The other side genuinely needs context to adapt, such as a teammate planning around you.", "The issue is still open and you have not decided your limit."],
    signals: ["Your messages include multiple reasons and apologies.", "The same request returns after each explanation."],
    preparation: ["Write the boundary in one sentence of under 20 words.", "Decide what you will do if it is crossed."],
    steps: ["State the boundary once, calmly.", "Offer one alternative if appropriate.", "Do not add further reasons if challenged.", "Act consistently with the boundary afterwards."],
    openingLine: "I want to be clear about this so there's no confusion.",
    scripts: {
      default: "I don't take client calls after 6pm. I'm happy to schedule anything urgent for 8:30 the next morning.",
      diplomatic: "I want to be helpful and also sustainable, so I keep calls to before 6pm. I can always make time first thing the next day.",
      direct: "I don't take calls after 6pm.",
      firm: "Calls after 6pm aren't something I do. That won't change.",
      written: "Thanks for understanding — I keep client calls between 9am and 6pm. For anything that comes up in the evening, send me a note and I'll prioritise it first thing the next morning.",
      message: "I don't take calls after 6 — will pick this up first thing tomorrow.",
    },
    reactions: [
      { ifThey: "ask for an exception", counter: "Repeat the boundary in the same words, kindly. Restating without new reasons signals it is settled." },
      { ifThey: "accept it", counter: "Thank them and keep to it yourself; inconsistency undoes the boundary." },
    ],
    secondMove: "If the boundary is crossed again, use Hold the Boundary on Repeat.",
    followUp: "Make the boundary visible where relevant: email signature, onboarding notes.",
    mistakes: ["Apologising repeatedly while stating the boundary.", "Making exceptions immediately after stating it."],
    ethicalBoundary: "Boundaries protect your limits; they are not tools to control others' behaviour beyond your relationship with them.",
    risk: "low", walkAway: ["A clearly stated boundary is repeatedly disregarded despite consistent enforcement."],
    example: "A project manager replaced a three-paragraph explanation with 'I don't work weekends; I'll handle this Monday at 9.' The weekend messages from one stakeholder stopped within two weeks.",
    related: ["mv_053", "mv_054", "mv_052"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_050", number: 50, slug: "say-no-with-a-path", title: "Say No with a Path",
    summary: "Decline the request clearly while offering one concrete alternative, so the other person leaves with a way forward rather than a dead end.",
    category: "boundaries", situations: ["boundary", "client_scope", "workplace_conflict"],
    goals: ["set_boundary", "recover_relationship"], channels: ["email", "in_person", "chat"],
    relationships: ["client", "manager", "colleague"], urgency: ["today", "this_week"],
    principle: "A refusal with a route forward protects both the boundary and the relationship.",
    whyItWorks: "Bare refusals can feel like rejection of the person. Pairing the no with a specific alternative — a later date, a smaller version, a referral — shows you care about their goal while keeping your limit. It moves the conversation from conflict to problem-solving.",
    whenToUse: ["You need to refuse a request from someone you want to keep working with.", "You have a genuine alternative that serves part of their need."],
    whenNotToUse: ["Any alternative would undermine the boundary itself.", "The request is inappropriate and should be declined without options."],
    signals: ["You avoid saying no because it feels too harsh.", "You say yes and later regret it."],
    preparation: ["Identify what the person actually needs behind the request.", "Choose one alternative you are genuinely willing to offer."],
    steps: ["Say no in the first sentence.", "Acknowledge their goal.", "Offer the single alternative.", "Let them choose whether to take it."],
    openingLine: "I can't take that on, but here's what I can do.",
    scripts: {
      default: "I can't lead the offsite planning this quarter. I could review the agenda draft by Thursday if someone else leads it.",
      diplomatic: "I really want the offsite to go well, and I can't take on leading it this quarter. Would it help if I reviewed the agenda once it's drafted?",
      direct: "No, I can't lead it. I can review the agenda.",
      firm: "I'm not able to lead the offsite. The agenda review is what I can offer.",
      written: "Thanks for thinking of me for the offsite. I'm not able to lead the planning this quarter given the launch. I'd be glad to review the draft agenda by Thursday the 12th if that would help whoever takes it on.",
      message: "Can't lead the offsite this quarter, but happy to review the agenda draft by Thu.",
    },
    reactions: [
      { ifThey: "push for the original request", counter: "Restate the no and the alternative once more; do not add new concessions." },
      { ifThey: "accept the alternative", counter: "Deliver it promptly and well; reliability supports future boundaries." },
    ],
    secondMove: "If they continue pressing, use Decline Without Over-Explaining.",
    followUp: "Deliver the alternative on time and confirm completion.",
    mistakes: ["Offering several alternatives that add up to the original request.", "Offering an alternative you resent."],
    ethicalBoundary: "Offer only alternatives you will honour. A token offer meant to look cooperative while doing nothing is disingenuous.",
    risk: "low", walkAway: ["Every no, even with a path, is treated as unacceptable."],
    example: "A senior developer was asked to mentor three new hires. She declined but offered a weekly 30-minute group Q&A. The manager accepted, and the format was later adopted across the team.",
    related: ["mv_049", "mv_028", "mv_039"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_051", number: 51, slug: "separate-the-person-from-the-request", title: "Separate the Person from the Request",
    summary: "Make it clear you value the person while refusing the specific request, so the boundary is not heard as a rejection of the relationship.",
    category: "boundaries", situations: ["boundary", "relationship_repair", "workplace_conflict"],
    goals: ["set_boundary", "recover_relationship"], channels: ["in_person", "video", "phone"],
    relationships: ["client", "colleague", "manager", "partner"], urgency: ["today", "this_week"],
    principle: "You can be warm toward the person and firm about the request at the same time.",
    whyItWorks: "People often hear 'no' as 'I don't value you'. Explicitly affirming the relationship before or after the refusal lowers defensiveness and makes the boundary easier to accept, especially with long-standing colleagues or clients who feel entitled by familiarity.",
    whenToUse: ["The request comes from someone you like or depend on.", "A previous refusal damaged the relationship."],
    whenNotToUse: ["The person has acted in bad faith and warmth would be misread.", "Affirming the relationship would be insincere."],
    signals: ["You fear saying no will hurt the relationship.", "The person frames requests as personal favours."],
    preparation: ["Identify something genuine you value about the person or relationship.", "Write the boundary separately from the affirmation."],
    steps: ["Affirm the relationship honestly.", "State the boundary clearly.", "Avoid 'but', which cancels the affirmation; use 'and'.", "Close with something forward-looking."],
    openingLine: "I value working with you, and I need to say no to this one.",
    scripts: {
      default: "I really value our partnership, and I can't extend payment terms to 90 days. I'm happy to look at a 45-day option.",
      diplomatic: "You've been one of our best clients for years, and that matters to me. I'm not able to move to 90-day terms, and I want to find something that works for both of us.",
      direct: "I value the relationship, and the answer on 90 days is no.",
      firm: "This isn't about our relationship. 90-day terms aren't possible.",
      written: "Hi Raj — I really appreciate the years we've worked together, and I want to keep that going. I'm not able to move to 90-day payment terms, as it would affect our cash flow significantly. I could offer 45 days for the next two quarters if that would help.",
      message: "Really value working with you — and I can't do 90-day terms. Could 45 work?",
    },
    reactions: [
      { ifThey: "say they thought the relationship meant more", counter: "Agree the relationship matters and restate the boundary calmly, without new reasons." },
      { ifThey: "appreciate the honesty", counter: "Move to the alternative or the next topic promptly." },
    ],
    secondMove: "If tension rises, use Lower the Temperature.",
    followUp: "Keep the relationship visibly warm in other interactions after the refusal.",
    mistakes: ["Using flattery to soften a no.", "Saying 'but' immediately after the affirmation."],
    ethicalBoundary: "Affirm only what you genuinely feel. Insincere warmth used as a sweetener is manipulation.",
    risk: "low", walkAway: ["The person repeatedly uses the relationship to pressure you after clear refusals."],
    example: "A supplier was asked by a decade-long client for steep payment extensions. By opening with genuine appreciation and offering 45 days, she kept the client and avoided a cash-flow crisis.",
    related: ["mv_050", "mv_075", "mv_006"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_052", number: 52, slug: "protect-your-availability-hours", title: "Protect Your Availability Hours",
    summary: "Publish clear response times and working hours, so clients and colleagues know when to expect you instead of testing your limits.",
    category: "boundaries", situations: ["boundary", "client_scope", "workplace_conflict"],
    goals: ["set_boundary", "clarity"], channels: ["email", "chat", "text"],
    relationships: ["client", "manager", "colleague"], urgency: ["exploring", "this_week"],
    principle: "Unstated availability becomes infinite availability.",
    whyItWorks: "When response expectations are vague, the fastest past reply becomes the standard. Stating hours and typical response times up front resets expectations collectively, reduces anxiety on both sides and makes out-of-hours requests clearly exceptional.",
    whenToUse: ["You feel pressure to reply instantly at all hours.", "You are onboarding a new client or joining a new team."],
    whenNotToUse: ["Your role genuinely requires on-call availability by agreement.", "A short-term crisis needs extra availability you have chosen to give."],
    signals: ["Messages arrive late at night expecting quick replies.", "You check messages constantly out of worry."],
    preparation: ["Decide your working hours and response window (for example within one business day).", "Define what counts as an emergency and how to reach you for one."],
    steps: ["Write a short availability statement.", "Share it at onboarding or in your signature.", "Respond within the stated window, not faster by habit.", "Point back to the statement if expectations drift."],
    openingLine: "So you know what to expect, here's how I handle messages.",
    scripts: {
      default: "I'm available 9am to 5:30pm, Monday to Friday, and reply to messages within one business day. For urgent production issues, call the support line.",
      diplomatic: "To give your project my best focus, I work set hours and reply within a business day. If something is genuinely urgent, here's how to reach me.",
      direct: "Hours: 9–5:30 weekdays. Replies within one business day.",
      firm: "Messages outside 9–5:30 are answered the next business day. That's consistent for all clients.",
      written: "Working hours: Monday–Friday, 9:00–17:30. I respond to emails and messages within one business day. For urgent issues affecting the live site, please use the support number in your onboarding pack. Thank you for helping me keep focus on your work.",
      message: "Just a note: I reply within 1 business day, 9–5:30 weekdays.",
    },
    reactions: [
      { ifThey: "expect an instant reply anyway", counter: "Reply within your window and briefly reference your hours." },
      { ifThey: "have a genuine emergency", counter: "Honour the emergency route you defined; that keeps the system credible." },
    ],
    secondMove: "If someone persistently ignores the hours, use Hold the Boundary on Repeat.",
    followUp: "Revisit the statement when your role or capacity changes.",
    mistakes: ["Stating hours and then replying at midnight.", "Defining 'urgent' so loosely that everything qualifies."],
    ethicalBoundary: "Respect contractual availability obligations you have agreed to; this Move is for expectations, not for breaking commitments.",
    risk: "low", walkAway: ["A client requires constant out-of-hours availability beyond what you agreed or are paid for."],
    example: "A bookkeeper added hours and a one-day response promise to her email signature. Late-night 'urgent' requests dropped sharply, and no client complained.",
    related: ["mv_049", "mv_036", "mv_053"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_053", number: 53, slug: "hold-the-boundary-on-repeat", title: "Hold the Boundary on Repeat",
    summary: "When the same boundary is tested again, restate it calmly and consistently, without escalating emotion or adding new reasons.",
    category: "boundaries", situations: ["boundary", "workplace_conflict", "client_scope"],
    goals: ["set_boundary"], channels: ["in_person", "email", "chat"],
    relationships: ["client", "manager", "colleague", "partner"], urgency: ["today"],
    principle: "Consistency, not volume, is what makes a boundary real.",
    whyItWorks: "Repeated testing is often a check on whether a boundary is real. Responding with the same calm words each time shows it is settled; escalating emotion or offering new reasons reopens debate. Over time, consistency makes testing unrewarding.",
    whenToUse: ["Someone keeps asking for something you have declined.", "You notice yourself becoming more irritated with each repeat request."],
    whenNotToUse: ["The repeated request comes with genuinely new information worth considering.", "The boundary itself was unreasonable and should be revised."],
    signals: ["The same request reappears in slightly different wording.", "You are tempted to give in just to stop the asking."],
    preparation: ["Write your standard boundary sentence and use it each time.", "Decide on a consequence if the testing continues."],
    steps: ["Recognise the request as a repeat.", "Restate the boundary using the same words.", "Do not add reasons or apologies.", "If it continues, name the pattern and the consequence."],
    openingLine: "As I mentioned before, that's not something I can do.",
    scripts: {
      default: "As I said last week, I don't share draft files before final payment. That's still the case.",
      diplomatic: "I understand why you're asking again. My answer is the same: draft files are shared after final payment.",
      direct: "Same answer as before: drafts after final payment.",
      firm: "This is the third request. The answer remains no, and I'd ask that we stop revisiting it.",
      written: "Thanks for your message. As mentioned on the 4th and the 11th, I share working files after final payment. That policy applies to all clients. Once the final invoice is settled, I'll send the files the same day.",
      message: "Still the same — files go out once the final invoice is paid.",
    },
    reactions: [
      { ifThey: "become frustrated", counter: "Acknowledge the frustration without changing the boundary." },
      { ifThey: "stop asking", counter: "Let it go without comment; no need to reference the past." },
    ],
    secondMove: "If repeated testing continues, use Escalate the Issue, Not the Person.",
    followUp: "Keep a note of repeat requests in case escalation becomes necessary.",
    mistakes: ["Giving in on the fourth request, teaching that persistence works.", "Letting irritation enter your tone."],
    ethicalBoundary: "Hold boundaries without hostility. Repeating a limit is fine; punishing someone for asking is not.",
    risk: "medium", walkAway: ["Persistent testing continues after you have named the pattern and its consequence."],
    example: "A landlord kept asking a contractor to start before the deposit cleared. She used the same sentence three times. The deposit arrived the next day and the requests stopped.",
    related: ["mv_049", "mv_079", "mv_054"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_054", number: 54, slug: "decline-without-over-explaining", title: "Decline Without Over-Explaining",
    summary: "Turn down requests with a brief, polite reason at most, avoiding detailed justifications that invite the other side to solve each objection.",
    category: "boundaries", situations: ["boundary", "partnership", "client_scope"],
    goals: ["set_boundary"], channels: ["email", "chat", "text"],
    relationships: ["client", "colleague", "partner", "vendor"], urgency: ["today", "this_week"],
    principle: "Each extra reason is a door the other side can try to open.",
    whyItWorks: "Detailed explanations feel polite but often backfire: the other person addresses each reason in turn, and your no starts to look negotiable. A brief, courteous decline signals that the decision is made while still respecting the person who asked.",
    whenToUse: ["You receive invitations or requests you do not want to accept.", "You tend to write long explanations when declining."],
    whenNotToUse: ["The relationship depends on mutual transparency, such as a close collaborator who must plan around you.", "Declining without explanation could seem dismissive in a formal process requiring reasons."],
    signals: ["Your decline emails are longer than the original request.", "People respond to your no by solving your excuses."],
    preparation: ["Draft a two-sentence decline template.", "Choose one honest reason, or none, before replying."],
    steps: ["Thank them for the request.", "Decline in one clear sentence.", "Optionally give one brief honest reason.", "Close warmly and do not reopen."],
    openingLine: "Thank you for thinking of me — I'm going to pass on this one.",
    scripts: {
      default: "Thanks for the invitation to speak at the conference. I'm going to decline this year, but I appreciate you thinking of me.",
      diplomatic: "I'm genuinely grateful for the invitation. It isn't something I can take on this year, and I hope it goes wonderfully.",
      direct: "Thank you, but I'll pass this year.",
      firm: "I won't be able to take part. Thank you for understanding.",
      written: "Hi Mei — thank you for the invitation to join the advisory panel. I'm going to decline, as I'm keeping my commitments focused this year. I appreciate you thinking of me and wish the panel every success.",
      message: "Thanks so much for asking — I'll pass on this one, but appreciate it.",
    },
    reactions: [
      { ifThey: "ask why", counter: "Give one brief honest reason or say it simply isn't a fit right now." },
      { ifThey: "try to solve your reason", counter: "Thank them and restate the decline without a new reason." },
    ],
    secondMove: "If the request returns, use Hold the Boundary on Repeat.",
    followUp: "No follow-up needed; avoid sending a second apology email.",
    mistakes: ["Inventing elaborate excuses.", "Apologising repeatedly in the same message."],
    ethicalBoundary: "Brevity is fine; dishonesty is not. Give a true reason or none, rather than a fabricated one.",
    risk: "low", walkAway: ["Brief, courteous declines are consistently met with pressure or guilt-tripping."],
    example: "A researcher used to send long explanations when declining review requests, often getting counter-proposals. Switching to two-sentence declines cut back-and-forth almost entirely.",
    related: ["mv_049", "mv_050", "mv_053"], access: "free", editorial: DRAFT_EDITORIAL,
  },
];
