import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Framing & Clarity (Moves 1–6). */
export const FRAMING: MoveInput[] = [
  {
    id: "mv_001", number: 1, slug: "name-the-decision", title: "Name the Decision",
    summary: "Reduce a tangled situation to one written sentence: the choice to be made, who makes it, and by when.",
    category: "framing", situations: ["leadership_alignment", "client_scope", "commitment", "difficult_conversation"],
    goals: ["clarity", "gain_commitment"], channels: ["in_person", "video", "email"],
    relationships: ["client", "manager", "colleague", "partner"], urgency: ["today", "this_week"],
    principle: "A conversation without a named decision drifts toward whoever is most comfortable waiting.",
    whyItWorks: "Most stalled situations are not disagreements about the answer; nobody has stated the question. Naming the decision converts ambient tension into something concrete that can be accepted, declined or delegated, and it exposes when the real decision-maker is absent.",
    whenToUse: ["Meetings keep ending with 'let's keep thinking about it'.", "Several issues are being argued at once and none is being resolved."],
    whenNotToUse: ["The other side is still describing a problem they have not finished explaining.", "Forcing a decision now would lock in an answer before key facts arrive."],
    signals: ["Repeated meetings on the same topic with no change in status.", "People agree in the room and do nothing afterward."],
    preparation: ["Write the decision in one sentence of under 25 words.", "Identify who has authority to make it and what date it actually matters by."],
    steps: ["Summarise what has been discussed in two sentences, without judgement.", "State the decision sentence and ask whether it is the right question.", "Confirm who owns the answer and the date.", "Send the agreed sentence in writing the same day."],
    openingLine: "Before we go further, can I try to name the decision we're actually making?",
    scripts: {
      default: "I think the decision in front of us is whether to extend the project to include the launch phase, and it needs an answer by the 14th. Is that the right question, and who should make the call?",
      diplomatic: "We've covered a lot of good ground. To make sure I'm helping rather than adding noise, could we agree on the one decision this conversation needs to produce, and who will make it?",
      direct: "We need one decision: extend to the launch phase or not. Who decides, and can we have it by the 14th?",
      firm: "I can't keep planning around an open question. I need a decision on the launch phase by the 14th, and I need to know who is making it.",
      written: "Hi Dana — following today's call, here is the decision as I understand it: whether to extend the engagement to include the launch phase. To keep the schedule intact we'd need an answer by Friday the 14th. Could you confirm that's the right question and who will make the final call?",
      message: "Quick check: the open decision is whether we extend to launch. Who's making that call, and can we land it by the 14th?",
    },
    reactions: [
      { ifThey: "say it is more complicated than one decision", counter: "Ask them to name the decisions and agree on the order. Several named decisions beat one unnamed fog." },
      { ifThey: "name someone else as the decision-maker", counter: "Ask how that person prefers to receive the question and offer a one-paragraph summary they can forward." },
      { ifThey: "push back on the date", counter: "Ask what the date depends on, then agree a date tied to that dependency." },
    ],
    secondMove: "If the decision is confirmed but not made by the date, move to Set the Next Checkpoint and ask what is blocking it.",
    followUp: "Send a two-line written recap of the decision sentence, owner and date within 24 hours.",
    mistakes: ["Writing the decision in a way that presumes your preferred answer.", "Naming the decision but never confirming who owns it."],
    ethicalBoundary: "Name the decision honestly. Framing a question so the only acceptable answer is yours is steering, not clarifying.",
    risk: "low", walkAway: ["After the decision is named, the counterpart repeatedly refuses to own it or name who does."],
    example: "A consultant had three status meetings in which the client praised the work but never approved phase two. She opened the fourth by naming the decision and date; the client admitted procurement needed a cost breakdown, which she sent that afternoon.",
    related: ["mv_013", "mv_062", "mv_004"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_002", number: 2, slug: "separate-facts-from-assumptions", title: "Separate Facts from Assumptions",
    summary: "Sort what you know from what you suspect before you act on either, so your response matches reality instead of your fear.",
    category: "framing", situations: ["client_scope", "workplace_conflict", "follow_up", "difficult_conversation"],
    goals: ["clarity", "de_escalate"], channels: ["in_person", "email", "chat"],
    relationships: ["client", "manager", "colleague", "vendor"], urgency: ["today", "this_week", "exploring"],
    principle: "You can only negotiate with what happened; you will mostly react to what you imagine happened.",
    whyItWorks: "Under pressure people merge observations with interpretations, then respond to the interpretation. A visible split between 'observed' and 'assumed' lowers the emotional temperature and shows which assumptions are cheap to test before you commit to a move.",
    whenToUse: ["You feel a strong reaction to a short or ambiguous message.", "You are about to send a reply that assumes intent."],
    whenNotToUse: ["Facts are clear and the delay of further analysis would itself cause harm.", "You are using analysis to avoid a conversation you already know you need to have."],
    signals: ["You are explaining their motives to yourself in detail.", "Your planned reply contains words like 'obviously' or 'clearly they'."],
    preparation: ["Write two columns: what was said or done, and what you believe it means.", "Mark each assumption with how you could test it."],
    steps: ["List only observable events with dates.", "List your interpretations separately.", "Choose the one assumption that would most change your move if wrong.", "Test it with a neutral question before acting."],
    openingLine: "I want to make sure I'm responding to what actually happened, so let me check one thing.",
    scripts: {
      default: "I noticed the review was moved twice this month. I don't want to read too much into that — is the timing still working on your side?",
      diplomatic: "I may be reading this wrong, so I'd rather ask than guess: the review has moved twice. Has anything changed in priorities that I should know about?",
      direct: "The review has moved twice. Is the project still a priority for you?",
      firm: "The review has moved twice and I'm planning resources around it. I need to know whether it's happening this month.",
      written: "Hi Sam — the review has been rescheduled twice this month (the 3rd and the 17th). I don't want to assume anything, so I'm checking directly: is the project still on the same timeline, or has something shifted that I should plan around?",
      message: "The review has moved twice — is the timeline still the same on your side?",
    },
    reactions: [
      { ifThey: "confirm nothing has changed", counter: "Accept it, propose a fixed date, and note it in writing." },
      { ifThey: "reveal a change you did not know about", counter: "Thank them and switch to Ask for the Constraint before proposing anything." },
    ],
    secondMove: "If the test confirms your concern, choose a move that addresses the confirmed fact, not the original fear.",
    followUp: "Record which assumptions were wrong. Patterns in your wrong assumptions are useful later.",
    mistakes: ["Treating a single data point as a trend.", "Asking a 'neutral' question in an accusing tone."],
    ethicalBoundary: "Do not present your assumptions to others as facts, including when describing the counterpart to colleagues.",
    risk: "low", walkAway: ["The facts, once tested, show a pattern of broken commitments rather than a misunderstanding."],
    example: "An employee read a one-word 'noted' from her manager as anger. Splitting fact from assumption, she asked whether the plan needed changes; the manager had been typing from an airport and approved it the next morning.",
    related: ["mv_007", "mv_005", "mv_073"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_003", number: 3, slug: "find-the-real-question", title: "Find the Real Question",
    summary: "Identify the concern underneath the stated request so you answer what actually matters to the other side.",
    category: "framing", situations: ["pricing", "offer", "client_scope", "vendor"],
    goals: ["clarity", "negotiate_terms"], channels: ["in_person", "phone", "video"],
    relationships: ["client", "employer", "vendor", "partner"], urgency: ["this_week", "exploring"],
    principle: "The stated request is often a proposed solution to a problem that has not been said aloud.",
    whyItWorks: "Requests like 'can you do it cheaper?' bundle a concern (budget, risk, internal optics) with a solution (lower price). If you answer only the solution, you trade value for nothing. If you find the concern, more options appear, many of which cost you less.",
    whenToUse: ["A request seems disproportionate to the situation.", "The same objection keeps returning after you have answered it."],
    whenNotToUse: ["The request is simple and clearly stated; probing would feel evasive.", "Trust is too low for questions to be heard as anything but stalling."],
    signals: ["They ask for one specific concession without explaining why.", "Their urgency does not match the business stakes you can see."],
    preparation: ["List three possible concerns that could produce this request.", "Prepare one open question for each."],
    steps: ["Acknowledge the request without agreeing to it.", "Ask what the request would solve for them.", "Listen for the concern and restate it.", "Offer options that address the concern, including but not limited to the original request."],
    openingLine: "I can look at that. Help me understand what it would solve on your end?",
    scripts: {
      default: "I can look at the price. Before I do, can you tell me what a lower number would solve for you — is it the total budget, the approval threshold, or something else?",
      diplomatic: "That's a fair thing to ask. I want to make sure I solve the right problem, so could you walk me through what's driving it?",
      direct: "What would the lower price solve for you?",
      firm: "I'm not going to adjust the price without understanding the reason. What's driving the request?",
      written: "Thanks for raising the price question. So I can respond properly, could you share what's behind it — for example, a budget ceiling, an approval threshold, or a comparison you're weighing? There may be ways to address it that work better for both of us than a straight reduction.",
    },
    reactions: [
      { ifThey: "name an approval threshold", counter: "Explore phasing or splitting the purchase rather than discounting." },
      { ifThey: "refuse to explain", counter: "Offer two concrete options and ask which is closer; their choice reveals the concern." },
      { ifThey: "mention a competitor quote", counter: "Ask what is included in the comparison before responding on price." },
    ],
    secondMove: "Once the concern is named, use Trade, Never Concede to address it with a matched exchange.",
    followUp: "Confirm the concern in writing so later proposals can reference it.",
    mistakes: ["Asking 'why?' in a way that sounds like a challenge.", "Hearing the concern and then offering the discount anyway."],
    ethicalBoundary: "Use what you learn to solve their problem, not to exploit a vulnerability they disclosed in good faith.",
    risk: "low", walkAway: ["The real concern is one you cannot address without compromising quality or safety."],
    example: "A buyer asked a design studio for 20% off. The studio asked what it would solve; the buyer's sign-off limit was $25,000. The studio split the work into two purchase orders at the original rate.",
    related: ["mv_008", "mv_055", "mv_011"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_004", number: 4, slug: "define-success-before-you-start", title: "Define Success Before You Start",
    summary: "Decide your target, acceptable range and minimum before a conversation, so pressure in the moment cannot move them.",
    category: "framing", situations: ["compensation", "offer", "pricing", "vendor", "promotion"],
    goals: ["protect_value", "negotiate_terms"], channels: ["in_person", "phone", "video", "email"],
    relationships: ["employer", "client", "vendor", "manager"], urgency: ["this_week", "exploring"],
    principle: "If you decide what success looks like during the conversation, the other side decides it for you.",
    whyItWorks: "Live negotiation produces anchoring, social pressure and fatigue. A target, range and floor set in advance give you a stable reference so each proposal can be judged quickly against something other than your nerves.",
    whenToUse: ["Before any conversation involving money, terms or role scope.", "When you have been 'talked down' in a past similar conversation."],
    whenNotToUse: ["You lack the information to set a sensible range; gather it first.", "The conversation is exploratory and fixing numbers early would close options."],
    signals: ["You cannot state your minimum acceptable outcome in one sentence.", "You expect to be surprised by their first number."],
    preparation: ["Write a target, an acceptable range and a walk-away floor.", "Note two non-price terms that would change your floor."],
    steps: ["Research comparable outcomes.", "Set target, range and floor in writing.", "Decide in advance what you will say if they go below the floor.", "Review the page just before the conversation."],
    openingLine: "I've thought carefully about what would make this work, and I'd like to share where I am.",
    scripts: {
      default: "Based on the scope and the market for this role, I'm looking for a base in the range of $118,000 to $124,000.",
      diplomatic: "I'm excited about the role, and I've done some homework so I can be specific. A base between $118,000 and $124,000 would make this an easy yes for me.",
      direct: "My target base is $124,000.",
      firm: "I've set a clear range for this. Below $112,000 I wouldn't be able to accept, so I'd rather say that now.",
      written: "Thank you for the offer. Having reviewed the scope and comparable roles, I'd be glad to accept at a base salary in the range of $118,000–$124,000. I'm flexible on how we structure the rest of the package and happy to talk through options.",
    },
    reactions: [
      { ifThey: "come in below your floor", counter: "Restate the floor calmly and ask whether there is flexibility elsewhere that changes the picture." },
      { ifThey: "ask you to name a number first", counter: "Give your target, not your floor, with the reason behind it." },
    ],
    secondMove: "If the gap remains after one exchange, use Ask for the Constraint to locate what is fixed and what is not.",
    followUp: "Afterward, compare the outcome with your written range and note what moved you.",
    mistakes: ["Revealing your floor as your opening position.", "Changing your floor mid-conversation without a new fact to justify it."],
    ethicalBoundary: "Do not misrepresent competing offers or current pay to support your range.",
    risk: "low", walkAway: ["The final offer is below your floor and no non-price term compensates."],
    example: "A product designer wrote target, range and floor before an offer call. When the recruiter opened $9,000 below her range, she stated the range once; the second offer landed inside it.",
    related: ["mv_022", "mv_031", "mv_087"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_005", number: 5, slug: "map-the-stakeholders", title: "Map the Stakeholders",
    summary: "List everyone who can influence, approve or block the outcome before you decide who to talk to and in what order.",
    category: "framing", situations: ["leadership_alignment", "promotion", "partnership", "vendor"],
    goals: ["clarity", "gain_commitment"], channels: ["in_person", "video", "email"],
    relationships: ["manager", "colleague", "client", "partner"], urgency: ["this_week", "exploring"],
    principle: "The person in front of you is rarely the only person deciding.",
    whyItWorks: "Outcomes stall when an unseen approver, budget owner or skeptic surfaces late. Mapping who matters early lets you shape the message for each, sequence conversations and avoid being blindsided by a veto.",
    whenToUse: ["The decision crosses teams or budgets.", "A previous yes was later reversed by someone you did not meet."],
    whenNotToUse: ["The decision is plainly owned by one person who has said so.", "Mapping would become a reason to delay a simple ask."],
    signals: ["Your contact says 'I'll need to run it by…'.", "Approvals take longer than the person you deal with suggests."],
    preparation: ["List each stakeholder with their interest, influence and likely position.", "Mark who you can reach directly and who you cannot."],
    steps: ["Ask your contact who else will weigh in.", "Place each person by influence and support.", "Decide the order of conversations.", "Tailor one key point for each stakeholder."],
    openingLine: "So I can make this easy for everyone involved, who else will weigh in on the decision?",
    scripts: {
      default: "Besides you, who else will have a view on this before it's approved? I'd like to make sure each of them has what they need.",
      diplomatic: "I'd like to make your life easier when this goes for sign-off. Is there anyone whose questions I should anticipate?",
      direct: "Who else needs to approve this?",
      firm: "I need to know who signs off. I've lost time before when a late approver appeared.",
      written: "Thanks for today. To help this move smoothly, could you let me know who else will be involved in the decision and what each will care about most? I'm happy to prepare a short summary for anyone who wasn't in the room.",
    },
    reactions: [
      { ifThey: "say they decide alone", counter: "Accept it and ask, 'If someone did ask questions later, who would it be?'" },
      { ifThey: "name a skeptical stakeholder", counter: "Offer to address that person's concern in a short note your contact can forward." },
    ],
    secondMove: "Use Pre-Wire the Decision with the most influential undecided stakeholder before the formal meeting.",
    followUp: "Keep the map updated as people's positions shift.",
    mistakes: ["Going around your contact in a way that embarrasses them.", "Treating titles as a proxy for actual influence."],
    ethicalBoundary: "Mapping is for clarity, not manipulation. Do not play stakeholders against each other.",
    risk: "low", walkAway: ["The real decision-maker is permanently unreachable and your contact cannot represent you."],
    example: "A vendor kept winning verbal approval from an operations lead, then losing at finance. After mapping, it sent a cost-per-site summary to the finance director before the next review and the contract was signed.",
    related: ["mv_016", "mv_001", "mv_064"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_006", number: 6, slug: "reframe-the-problem-as-shared", title: "Reframe the Problem as Shared",
    summary: "Move the conversation from 'me against you' to 'us against the problem' by naming a goal both sides already hold.",
    category: "framing", situations: ["workplace_conflict", "partnership", "relationship_repair", "client_scope"],
    goals: ["resolve_conflict", "de_escalate"], channels: ["in_person", "video", "phone"],
    relationships: ["colleague", "partner", "client", "manager"], urgency: ["today", "this_week"],
    principle: "People defend positions; they collaborate on problems they recognise as their own.",
    whyItWorks: "Positional standoffs harden when each side feels attacked. Naming a goal both sides genuinely share — a launch date, a customer, a budget — gives each party a reason to solve rather than to win, without either side conceding first.",
    whenToUse: ["Discussion has become a contest of positions.", "Both sides depend on the same outcome but are arguing about method."],
    whenNotToUse: ["There is no genuinely shared goal; inventing one sounds manipulative.", "The other side has acted in bad faith and needs a boundary, not collaboration."],
    signals: ["Both sides keep repeating their position more forcefully.", "The disagreement is about 'how', not 'whether'."],
    preparation: ["Identify one goal both sides would state publicly.", "Prepare a neutral description of the problem that blames no one."],
    steps: ["Pause the debate.", "State the shared goal plainly.", "Describe the problem as an obstacle to that goal.", "Invite joint options before evaluating any."],
    openingLine: "We both need this launch to land on the 30th. Can we look at the problem from there?",
    scripts: {
      default: "We both want the launch on the 30th. The problem is that QA and design are competing for the same week. What options do we have to solve that together?",
      diplomatic: "I think we're actually after the same thing — a clean launch on the 30th. Could we step back from whose plan is right and look at what's in the way?",
      direct: "We share the same deadline. Let's solve the scheduling conflict, not argue about whose fault it is.",
      firm: "Arguing about blame won't get us to the 30th. I'm going to focus on the conflict in the schedule; I'd like you to work on it with me.",
      written: "Following our discussion: we're both committed to launching on the 30th. The obstacle is that QA and design both need the week of the 18th. I've listed three possible ways through below. Could you add any you see, and we'll pick one on Thursday?",
    },
    reactions: [
      { ifThey: "insist the problem is your fault", counter: "Acknowledge any part that is yours briefly, then return to the shared goal." },
      { ifThey: "agree and propose an option", counter: "Build on it before offering your own." },
    ],
    secondMove: "Once options are on the table, use Name the Decision to agree which one and by when.",
    followUp: "Write down the joint option chosen and who owns each step.",
    mistakes: ["Naming a 'shared goal' that is really your goal.", "Using shared language while still pushing a fixed position."],
    ethicalBoundary: "Only claim a goal is shared if it is. Fake collaboration erodes trust faster than open disagreement.",
    risk: "low", walkAway: ["After reframing, the other party still treats every option as a contest to win."],
    example: "Two team leads were deadlocked over a release schedule. One opened with the date both had promised the customer; within twenty minutes they agreed to split QA into two shorter passes.",
    related: ["mv_073", "mv_076", "mv_001"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
];
