import { DRAFT_EDITORIAL, type MoveInput } from "./schema";

/** Category: Accountability & Documentation (Moves 67–72). */
export const ACCOUNTABILITY: MoveInput[] = [
  {
    id: "mv_067", number: 67, slug: "recap-in-writing", title: "Recap in Writing",
    summary: "Send a short written summary of decisions, owners and dates after every important conversation, creating a shared record both sides can rely on.",
    category: "accountability", situations: ["commitment", "client_scope", "leadership_alignment", "follow_up"],
    goals: ["clarity", "gain_commitment"], channels: ["email", "chat"],
    relationships: ["client", "manager", "colleague", "vendor", "partner"], urgency: ["today"],
    principle: "What is written down survives; what is only said is renegotiated.",
    whyItWorks: "Memory is selective and changes over time. A prompt written recap fixes the agreement, gives the other side a chance to correct it, and becomes a neutral reference later. It also signals professionalism without implying distrust.",
    whenToUse: ["After any meeting where decisions or commitments were made.", "When agreements with this counterpart have been disputed before."],
    whenNotToUse: ["The conversation was purely social or exploratory.", "A written record would breach confidentiality requirements."],
    signals: ["People remember meetings differently.", "Follow-up actions are frequently forgotten."],
    preparation: ["Take brief notes during the meeting on decisions, owners and dates.", "Use a consistent recap format."],
    steps: ["Send within 24 hours.", "List decisions, actions with owners, and dates.", "Invite corrections by a specific time.", "File it where both sides can find it."],
    openingLine: "Thanks for today — here's a quick recap of what we agreed.",
    scripts: {
      default: "Recap: we agreed to launch on 2 May. You'll provide final copy by 18 April; I'll deliver the staging site by 25 April. Let me know by Friday if anything's off.",
      diplomatic: "Thanks for a productive meeting. I've jotted down what I understood we agreed — please add or correct anything I've missed.",
      direct: "Decisions: launch 2 May. Copy from you by 18 April. Staging from me by 25 April.",
      firm: "Recap of agreed dates below. Unless corrected by Friday, these stand.",
      written: "Hi team — thanks for today. Recap: (1) Launch date: 2 May. (2) Final copy: Jamie, by 18 April. (3) Staging site: me, by 25 April. (4) Open question: hosting provider, to decide at next check-in on 22 April. Please reply by Friday with any corrections.",
      message: "Recap sent by email — launch 2 May, copy 18 Apr, staging 25 Apr. Shout if anything's off.",
    },
    reactions: [
      { ifThey: "correct the recap", counter: "Thank them, update it, and resend the corrected version." },
      { ifThey: "don't respond", counter: "Treat the recap as the record, as stated, and refer to it later." },
    ],
    secondMove: "If an item in the recap is missed, use Reference the Agreement, Not the Feeling.",
    followUp: "Keep recaps in one shared thread or folder.",
    mistakes: ["Writing long narrative minutes nobody reads.", "Recapping only your interpretation without inviting corrections."],
    ethicalBoundary: "Recap accurately. Writing a recap that shifts terms in your favour damages trust and may be disputed.",
    risk: "low", walkAway: ["The other side consistently disputes written recaps after the fact without having corrected them."],
    example: "A product manager began sending three-line recaps after every client call. When the client later claimed a feature was promised, the recap showed it was deferred; the conversation took two minutes.",
    related: ["mv_064", "mv_068", "mv_009"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_068", number: 68, slug: "keep-a-decision-log", title: "Keep a Decision Log",
    summary: "Maintain a simple running record of key decisions, who made them and why, so later questions are answered by evidence rather than memory.",
    category: "accountability", situations: ["leadership_alignment", "client_scope", "partnership"],
    goals: ["clarity", "prepare_escalation"], channels: ["email", "chat"],
    relationships: ["client", "manager", "colleague", "partner"], urgency: ["exploring"],
    principle: "A decision without a record will eventually be remembered as someone else's.",
    whyItWorks: "Over long projects, the reasons behind decisions fade and are later questioned. A shared log with date, decision, owner and rationale prevents re-litigation, protects people from blame for decisions they did not make, and helps new team members understand context.",
    whenToUse: ["Long projects with many stakeholders.", "Decisions have been reversed or disputed before."],
    whenNotToUse: ["Short, simple tasks where the overhead outweighs benefit.", "The log would be used mainly to assign blame."],
    signals: ["People ask 'why did we decide that?' repeatedly.", "Decisions are reversed without acknowledging earlier reasons."],
    preparation: ["Create a shared document with columns: date, decision, owner, reason.", "Agree with stakeholders that it will be the record."],
    steps: ["Log each significant decision within a day.", "Include the reason and who decided.", "Share the log link in recaps.", "Refer to it when decisions are questioned."],
    openingLine: "I've added that to the decision log so we have it for later.",
    scripts: {
      default: "I've logged today's decision: we're using the existing payment provider for launch, decided by Maria, to reduce integration risk.",
      diplomatic: "To help everyone keep track, I keep a simple log of decisions. I've added today's — let me know if I've captured the reasoning correctly.",
      direct: "Logged: existing payment provider for launch, decided by Maria.",
      firm: "This was decided on 3 March by Maria and logged. Reversing it now affects the timeline.",
      written: "Decision log update — 3 March: Payment provider for launch: continue with the existing provider. Owner: Maria (Head of Ops). Rationale: lower integration risk before launch; revisit in Q3. Log link: [shared doc].",
      message: "Added today's payment-provider decision to the log (link in thread).",
    },
    reactions: [
      { ifThey: "dispute an entry", counter: "Correct it if wrong; if accurate, refer to the original recap." },
      { ifThey: "want to reverse a decision", counter: "Log the new decision with its rationale and impact, rather than deleting the old." },
    ],
    secondMove: "If a reversal causes problems, use Escalate in Writing with a Timeline using the log.",
    followUp: "Review the log at major milestones.",
    mistakes: ["Logging inconsistently.", "Keeping the log private, which makes it look like a blame file."],
    ethicalBoundary: "Keep the log transparent and shared. A secret record of others' decisions damages trust.",
    risk: "low", walkAway: ["Logged decisions are repeatedly overturned without acknowledgement or accountability."],
    example: "When a new director questioned why a feature was cut, the project lead shared the decision log showing the previous director's rationale. The discussion moved on to what to do next.",
    related: ["mv_067", "mv_030", "mv_082"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_069", number: 69, slug: "reference-the-agreement-not-the-feeling", title: "Reference the Agreement, Not the Feeling",
    summary: "When a commitment is broken, point to the specific agreement and its terms, rather than how let down or frustrated you feel.",
    category: "accountability", situations: ["client_scope", "vendor", "workplace_conflict", "escalation"],
    goals: ["resolve_conflict", "protect_value"], channels: ["email", "in_person", "video"],
    relationships: ["client", "vendor", "colleague", "manager"], urgency: ["today", "this_week"],
    principle: "Agreements can be discussed calmly; disappointment invites defensiveness.",
    whyItWorks: "Emotional framing ('I'm really frustrated') puts people on the defensive and turns the issue into a debate about feelings. Referring to the documented agreement — date, term, what happened — keeps the conversation factual, shared and focused on remedy.",
    whenToUse: ["A payment, deliverable or deadline was missed.", "You feel angry and want to stay professional."],
    whenNotToUse: ["There is no clear agreement; first establish one.", "The relationship needs an emotional repair conversation more than a contractual one."],
    signals: ["You are drafting a message full of adjectives.", "You want to say 'as I've said many times'."],
    preparation: ["Find the exact agreement text or recap.", "List what was agreed and what happened, with dates."],
    steps: ["Quote or summarise the agreement.", "State what happened factually.", "Ask what will happen next or propose a remedy.", "Confirm the remedy in writing."],
    openingLine: "Our agreement was payment within 30 days of invoice; the invoice is now 45 days old.",
    scripts: {
      default: "Our agreement specifies payment within 30 days. Invoice #204 was issued on 1 March and is now overdue. Can you confirm when it will be paid?",
      diplomatic: "I wanted to check in on invoice #204. Our agreement was for 30-day payment, and it's now a couple of weeks past that — is something holding it up?",
      direct: "Invoice #204 is 15 days past the agreed 30-day terms. When will it be paid?",
      firm: "Invoice #204 is overdue under our 30-day terms. Work on the next phase will pause until it's settled.",
      written: "Hi Chris — per our agreement (section 5), invoices are payable within 30 days. Invoice #204 for 4,200 was issued on 1 March and remains unpaid. Could you confirm the expected payment date? If there's an issue with the invoice, please let me know so we can resolve it.",
      message: "Hi Chris — invoice #204 is past the agreed 30 days. Can you confirm a payment date?",
    },
    reactions: [
      { ifThey: "apologise and give a date", counter: "Thank them and confirm the date in writing." },
      { ifThey: "dispute the agreement", counter: "Share the relevant text calmly and ask which part they read differently." },
    ],
    secondMove: "If the agreement continues to be broken, use Agree on What Happens If It Slips or Escalate the Issue, Not the Person.",
    followUp: "Log the breach and the agreed remedy.",
    mistakes: ["Opening with how disappointed you are.", "Quoting the agreement in a sarcastic tone."],
    ethicalBoundary: "Make sure the agreement says what you claim. Overstating contractual terms is a legal and ethical risk; seek qualified advice where stakes are high.",
    risk: "medium", walkAway: ["Agreed terms are repeatedly broken despite factual reminders."],
    example: "A supplier stopped sending 'I'm really frustrated' emails and started quoting payment terms and invoice dates. Average days-to-payment from her slowest client dropped from 62 to 38.",
    related: ["mv_067", "mv_071", "mv_079"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_070", number: 70, slug: "track-the-pattern-before-raising-it", title: "Track the Pattern Before Raising It",
    summary: "Record dated examples of a recurring problem before addressing it, so the conversation is about a documented pattern rather than one incident.",
    category: "accountability", situations: ["workplace_conflict", "client_scope", "escalation"],
    goals: ["prepare_escalation", "resolve_conflict"], channels: ["email", "in_person"],
    relationships: ["manager", "colleague", "client", "vendor", "report"], urgency: ["exploring", "this_week"],
    principle: "One incident is an anecdote; five dated incidents are a pattern.",
    whyItWorks: "Raising a single incident invites the answer 'that was a one-off'. A short record of dated examples makes a pattern undeniable, keeps the conversation factual and helps you judge whether the issue is real or a perception shaped by one bad day.",
    whenToUse: ["A recurring behaviour is affecting your work.", "You suspect a pattern but have only vague impressions."],
    whenNotToUse: ["The issue is serious and immediate, such as harassment or safety; report it now through appropriate channels.", "Tracking would amount to surveillance beyond your role."],
    signals: ["You feel the same frustration repeatedly with the same person.", "Your examples are vague when you try to describe the problem."],
    preparation: ["Create a private log: date, what happened, impact.", "Record only observable facts, not interpretations."],
    steps: ["Log each occurrence briefly as it happens.", "After several entries, review whether a pattern exists.", "Raise it with two or three representative examples.", "Focus on impact and the change you need."],
    openingLine: "I've noticed a pattern over the last month that I'd like to talk about.",
    scripts: {
      default: "Over the last month, the weekly report has arrived after the Thursday deadline four times — on the 3rd, 10th, 17th and 24th. It's delaying the client update. Can we talk about what's getting in the way?",
      diplomatic: "I wanted to raise something gently. The Thursday report has been late a few times recently, and I'd like to understand if there's something I can help with.",
      direct: "The report has been late four Thursdays in a row. What's causing it?",
      firm: "Four late reports in a month is a pattern. It needs to change from next week.",
      written: "Hi Sam — I'd like to discuss the weekly report timing. It arrived after the Thursday 5pm deadline on the 3rd, 10th, 17th and 24th, which delayed the client update each time. Could we meet this week to understand what's getting in the way and agree a fix?",
      message: "Could we chat about the Thursday report timing? It's been late a few weeks running.",
    },
    reactions: [
      { ifThey: "explain a cause", counter: "Work together on a fix and agree how you will both know it is resolved." },
      { ifThey: "deny the pattern", counter: "Share the dates calmly and ask how they see it." },
    ],
    secondMove: "If the pattern continues, use Agree on What Happens If It Slips.",
    followUp: "Keep tracking briefly for a few weeks after to confirm improvement.",
    mistakes: ["Waiting months while resentment builds.", "Presenting a long list as an ambush."],
    ethicalBoundary: "Track only what is relevant to work and observable. Covertly monitoring someone's personal life or communications is inappropriate.",
    risk: "medium", walkAway: ["A documented pattern continues after a clear conversation and agreed fix."],
    example: "A team lead felt a colleague 'always' missed handoffs. Logging for three weeks showed two misses, both on Mondays after on-call weekends. They moved handoffs to Tuesday and the issue disappeared.",
    related: ["mv_002", "mv_071", "mv_082"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_071", number: 71, slug: "name-the-missed-commitment", title: "Name the Missed Commitment",
    summary: "When someone misses a promised action, raise it promptly and specifically, without blame, and agree a new date.",
    category: "accountability", situations: ["commitment", "follow_up", "workplace_conflict"],
    goals: ["gain_commitment", "resolve_conflict"], channels: ["email", "chat", "in_person"],
    relationships: ["client", "colleague", "manager", "vendor", "report"], urgency: ["today"],
    principle: "A missed commitment ignored becomes a commitment cancelled.",
    whyItWorks: "Letting a missed deadline pass silently teaches that deadlines are optional. Naming it quickly and neutrally — what was promised, when, and asking for a new date — maintains accountability without damaging the relationship and often uncovers obstacles you can help remove.",
    whenToUse: ["An agreed deliverable or response did not arrive.", "Small misses are starting to accumulate."],
    whenNotToUse: ["The miss was caused by your own delay upstream.", "You know of a serious personal circumstance that warrants patience."],
    signals: ["A promised item is a day or more overdue.", "You are adjusting your plans silently around someone else's misses."],
    preparation: ["Confirm the original commitment and date.", "Decide what new date you need."],
    steps: ["Reference the commitment and the date.", "Ask whether something got in the way.", "Agree a new specific date.", "Note it in writing."],
    openingLine: "We'd planned to have the feedback by Tuesday — is it still coming?",
    scripts: {
      default: "We'd agreed you'd send the feedback by Tuesday. I haven't seen it yet — is it still coming, and could you get it to me by Friday?",
      diplomatic: "Just checking in on the feedback we'd planned for Tuesday. I know things get busy — is there anything I can do to help it along?",
      direct: "The feedback was due Tuesday. Can you send it by Friday?",
      firm: "The feedback is three days late, which affects launch. I need it by Friday.",
      written: "Hi Lee — in our recap from the 1st, you'd planned to send feedback on the draft by Tuesday the 6th. I haven't received it yet. Is everything okay? If you can send it by Friday the 9th, we can still hold the launch date.",
      message: "Hi Lee — the draft feedback was due Tue. Any chance by Friday?",
    },
    reactions: [
      { ifThey: "explain and give a new date", counter: "Accept, confirm in writing and check in at the new date." },
      { ifThey: "seem defensive", counter: "Acknowledge their workload and keep the focus on the new date." },
    ],
    secondMove: "If misses keep happening, use Track the Pattern Before Raising It.",
    followUp: "Check in on the new date without waiting for it to slip again.",
    mistakes: ["Waiting a week before saying anything.", "Raising it publicly in a group setting."],
    ethicalBoundary: "Address the miss privately and fairly. Public shaming for a missed task is disproportionate.",
    risk: "low", walkAway: ["Commitments are missed repeatedly even after new dates are agreed."],
    example: "A designer used to wait silently when client feedback was late. She began sending a same-day note after any miss; average delay fell from eight days to two.",
    related: ["mv_062", "mv_069", "mv_065"], access: "free", editorial: DRAFT_EDITORIAL,
  },
  {
    id: "mv_072", number: 72, slug: "agree-what-happens-if-it-slips", title: "Agree on What Happens If It Slips",
    summary: "Decide in advance, together, what will happen if a deadline or commitment is missed, so consequences are expected rather than punitive.",
    category: "accountability", situations: ["commitment", "client_scope", "vendor", "partnership"],
    goals: ["clarity", "protect_value", "prepare_escalation"], channels: ["email", "in_person", "video"],
    relationships: ["client", "vendor", "partner", "colleague"], urgency: ["this_week", "exploring"],
    principle: "Consequences agreed in calm are accepted in conflict.",
    whyItWorks: "Consequences announced after a failure feel like punishment and spark disputes. Agreeing beforehand — 'if feedback is more than five days late, the launch moves by the same amount' — makes outcomes predictable, fair and less personal, and motivates both sides to keep commitments.",
    whenToUse: ["Starting a project with interdependent deadlines.", "After a first missed commitment, to prevent a second."],
    whenNotToUse: ["The relationship is informal and formal consequences would feel heavy.", "You have no realistic way to apply the consequence."],
    signals: ["Your deadlines depend on the other side delivering inputs.", "Previous slips caused arguments about who absorbs the impact."],
    preparation: ["Identify dependencies where their delay affects your delivery.", "Propose a proportionate, mutual consequence for each."],
    steps: ["Raise it at kickoff as normal planning.", "Propose specific consequences that apply to both sides.", "Agree and document them.", "Apply them consistently and without drama."],
    openingLine: "Let's agree now what happens to the timeline if either of us runs late.",
    scripts: {
      default: "If content arrives more than five working days after the 10th, launch moves by the same number of days. And if I'm late on design, I'll absorb the extra work to hold the date.",
      diplomatic: "To keep things fair for both of us, could we agree how we'll handle any delays — on either side — before we start?",
      direct: "If content is more than five days late, launch moves accordingly.",
      firm: "Late content moves the launch. That's part of the agreement.",
      written: "Proposed timeline terms: (1) If client content is delivered more than five working days after 10 May, the launch date moves by the same number of working days. (2) If design delivery is late on our side, we'll add resources at no cost to protect the launch date. Please confirm you're happy with these terms.",
      message: "Proposal: late content moves launch day-for-day; late design is on us to recover. OK?",
    },
    reactions: [
      { ifThey: "push back on consequences", counter: "Ask what consequence they would consider fair; agree on something proportionate." },
      { ifThey: "agree", counter: "Include it in the written agreement and refer to it if needed." },
    ],
    secondMove: "If a slip occurs, use Reference the Agreement, Not the Feeling to apply it.",
    followUp: "Remind both sides of the terms at key milestones.",
    mistakes: ["Making consequences one-sided.", "Agreeing consequences and then not applying them."],
    ethicalBoundary: "Keep consequences proportionate and mutual. Penalty terms with legal effect may need qualified advice.",
    risk: "low", walkAway: ["The counterpart refuses any accountability terms while requiring them from you."],
    example: "A web agency added a 'content delay moves launch' clause. When the client was nine days late, the launch moved nine days without argument, because the term had been agreed in advance.",
    related: ["mv_018", "mv_069", "mv_084"], access: "pro", editorial: DRAFT_EDITORIAL,
  },
];
