import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/power/shell";
import { supabase } from "@/integrations/supabase/client";
import { useAuthUser } from "@/hooks/use-auth-user";
import { getAccountSummary } from "@/lib/moveiq.functions";
export const Route=createFileRoute("/account")({head:()=>({meta:[{title:"Account — Power Move IQ"},{name:"description",content:"Manage your Power Move IQ account, plan, and preferences."},{property:"og:title",content:"Your Power Move IQ Account"},{property:"og:description",content:"Manage plan, preferences, and strategic history."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Account});
type S=Awaited<ReturnType<typeof getAccountSummary>>;
const FOCUS=["Negotiation & clients","Career & compensation","Pricing & business"];
function Account(){const {user}=useAuthUser();const nav=useNavigate();const summaryFn=useServerFn(getAccountSummary);const [s,setS]=useState<S|null>(null);const [name,setName]=useState("");const [focus,setFocus]=useState(FOCUS[0]);const [saved,setSaved]=useState("");
useEffect(()=>{if(!user)return;void (async()=>{await supabase.from("profiles").upsert({id:user.id,email:user.email??"",display_name:String(user.user_metadata?.['display_name']??user.user_metadata?.['full_name']??"")},{onConflict:"id",ignoreDuplicates:true});await supabase.from("user_roles").upsert({user_id:user.id,role:"user"},{onConflict:"user_id,role",ignoreDuplicates:true});await supabase.from("streaks").upsert({user_id:user.id},{onConflict:"user_id",ignoreDuplicates:true});const r=await summaryFn();setS(r);setName(r.displayName);if(r.preferences.focus)setFocus(r.preferences.focus)})().catch(()=>setSaved("Account details could not be loaded."))},[user,summaryFn]);
async function savePrefs(){if(!user)return;const {error}=await supabase.from("profiles").update({display_name:name.trim().slice(0,80),preferences:{focus},updated_at:new Date().toISOString()}).eq("id",user.id);setSaved(error?"Preferences could not be saved.":"Preferences saved.")}
async function signOut(){await supabase.auth.signOut();await nav({to:"/auth"})}
const email=user?.email??"";const pro=s?.tier==="pro";
return <div className="page-shell"><PageHeader eyebrow="PROFILE & PREFERENCES" title="Account" intro={email?`Signed in as ${email}`:"Sign in to sync your cases and Outcome Memory across devices."}/><div className="account-grid"><section className="account-panel"><p className="eyebrow">YOUR PLAN</p><h2>{!email?"Guest access":pro?"Power Move IQ Pro":"Free"}</h2><p className="text-sm leading-7 text-muted-foreground">{pro?"Full analyses, saved cases, Outcome Memory, follow-ups, and Weekly IQ are active.":"Daily Move and limited MOVE IQ analyses are included. Upgrade for the complete decision system."}</p>{!pro&&<Button asChild className="mt-5"><Link to="/pricing">VIEW PRO</Link></Button>}</section><section className="account-panel"><p className="eyebrow">YOUR PRACTICE</p><div className="metric-row"><div><strong>{s?.streak??0}</strong><span>Day streak</span></div><div><strong>{s?.cases??0}</strong><span>Cases</span></div><div><strong>{s?.favorites??0}</strong><span>Saved moves</span></div></div><div className="mt-7 flex flex-wrap gap-2">{email?<Button variant="outline" onClick={signOut}>SIGN OUT</Button>:<Button asChild><Link to="/auth">SIGN IN / CREATE ACCOUNT</Link></Button>}</div></section>{email&&<section className="account-panel"><p className="eyebrow">PREFERENCES</p><h2>Decision focus</h2><label className="block text-xs text-muted-foreground mb-2" htmlFor="focus">Primary focus</label><select id="focus" className="field w-full" value={focus} onChange={e=>setFocus(e.target.value)}>{FOCUS.map(f=><option key={f}>{f}</option>)}</select><label className="mt-5 block text-xs text-muted-foreground mb-2" htmlFor="name">Display name</label><input id="name" className="field w-full" placeholder="Your name" value={name} maxLength={80} onChange={e=>setName(e.target.value)}/><Button className="mt-5" variant="editorial" onClick={savePrefs}>SAVE PREFERENCES</Button>{saved&&<p className="mt-3 text-xs text-muted-foreground" role="status">{saved}</p>}</section>}<section className="account-panel"><p className="eyebrow">OUTCOME MEMORY</p><h2>{s?.outcomes?`${s.outcomes} recorded outcome${s.outcomes===1?"":"s"}`:"Build pattern recognition."}</h2><p className="text-sm leading-7 text-muted-foreground">Every recorded result makes future decisions more grounded in your lived experience.</p><Button asChild variant="editorial" className="mt-5"><Link to="/outcomes">VIEW OUTCOMES</Link></Button></section></div></div>}
