import { createFileRoute } from "@tanstack/react-router";
export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms — Power Move IQ" },
      { name: "description", content: "Power Move IQ terms of use and subscription terms." },
      { property: "og:title", content: "Power Move IQ Terms" },
      {
        property: "og:description",
        content: "Educational use, subscriptions, cancellation, and service boundaries.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Terms,
});
function Terms() {
  return (
    <div className="page-shell article">
      <p className="eyebrow">TERMS OF USE</p>
      <h1>Terms</h1>
      <p className="lead">
        Power Move IQ provides educational decision-support, not professional advice or guaranteed
        outcomes.
      </p>
      <h2>Use of the service</h2>
      <p>
        Analyses are generated by AI from what you describe and may be incomplete or wrong. You
        remain responsible for your decisions and actions. Do not use Power Move IQ as a substitute
        for legal, financial, tax, employment, or other qualified professional advice.
      </p>
      <h2>Subscriptions and cancellation</h2>
      <p>
        Pro costs $14.99 per month or $99 per year, billed through Stripe. Subscriptions renew
        automatically at the same interval until cancelled. Cancelling stops future renewals, and
        Pro access continues until the end of the period already paid for.
      </p>
      <h2>Changes</h2>
      <p>
        We may update features, prices, or these terms. Price changes will not apply to a billing
        period you have already paid for.
      </p>
      <h2>Support</h2>
      <p>
        Questions, billing help, or account deletion requests: email{" "}
        <a href="mailto:powermoveiq@gmail.com">powermoveiq@gmail.com</a>. Subscriptions can be
        cancelled from Account → Manage subscription. Account deletion is handled manually on
        request and confirmed by email.
      </p>
      <h2>Independence</h2>
      <p>
        Power Move IQ is an independent project and is not affiliated with Donald J. Trump, the
        Trump Organization, any campaign, or Robert Greene. No endorsement is stated or implied.
      </p>
    </div>
  );
}
