CREATE TYPE public.subscription_tier AS ENUM ('free', 'pro');
CREATE TYPE public.app_role AS ENUM ('user', 'admin');
CREATE TYPE public.analysis_status AS ENUM ('draft', 'complete', 'archived');
CREATE TYPE public.outcome_type AS ENUM ('accepted', 'negotiated', 'declined', 'ghosted', 'other');

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY,
  display_name text NOT NULL DEFAULT '',
  avatar_url text,
  email text NOT NULL DEFAULT '',
  subscription_tier public.subscription_tier NOT NULL DEFAULT 'free',
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own profile" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Users create own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id AND subscription_tier = 'free');
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role public.app_role NOT NULL DEFAULT 'user',
  UNIQUE (user_id, role)
);
GRANT SELECT, INSERT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own roles" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users create default role" ON public.user_roles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id AND role = 'user');

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;

CREATE TABLE public.moves (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  move_number integer NOT NULL UNIQUE CHECK (move_number BETWEEN 1 AND 90),
  title text NOT NULL,
  category text NOT NULL,
  principle text NOT NULL,
  field_note text NOT NULL,
  action_prompt text NOT NULL,
  is_pro boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.moves TO anon, authenticated;
GRANT ALL ON public.moves TO service_role;
ALTER TABLE public.moves ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Moves are public" ON public.moves FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.weekly_lenses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_number integer NOT NULL UNIQUE CHECK (week_number BETWEEN 1 AND 52),
  title text NOT NULL,
  thesis text NOT NULL,
  questions jsonb NOT NULL DEFAULT '[]'::jsonb,
  exercise text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.weekly_lenses TO anon, authenticated;
GRANT ALL ON public.weekly_lenses TO service_role;
ALTER TABLE public.weekly_lenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Weekly lenses are public" ON public.weekly_lenses FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.analyses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  situation text NOT NULL,
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  result jsonb NOT NULL DEFAULT '{}'::jsonb,
  chosen_move text,
  status public.analysis_status NOT NULL DEFAULT 'complete',
  is_saved boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.analyses TO authenticated;
GRANT ALL ON public.analyses TO service_role;
ALTER TABLE public.analyses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own analyses" ON public.analyses FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users create own analyses" ON public.analyses FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own analyses" ON public.analyses FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own analyses" ON public.analyses FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE INDEX analyses_user_created_idx ON public.analyses (user_id, created_at DESC);

CREATE TABLE public.outcomes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  analysis_id uuid NOT NULL REFERENCES public.analyses(id) ON DELETE CASCADE,
  outcome public.outcome_type NOT NULL,
  chosen_move text,
  result_note text NOT NULL DEFAULT '',
  recorded_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.outcomes TO authenticated;
GRANT ALL ON public.outcomes TO service_role;
ALTER TABLE public.outcomes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own outcomes" ON public.outcomes FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users create own outcomes" ON public.outcomes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own outcomes" ON public.outcomes FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own outcomes" ON public.outcomes FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE INDEX outcomes_user_recorded_idx ON public.outcomes (user_id, recorded_at DESC);

CREATE TABLE public.favorite_moves (
  user_id uuid NOT NULL,
  move_id integer NOT NULL REFERENCES public.moves(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, move_id)
);
GRANT SELECT, INSERT, DELETE ON public.favorite_moves TO authenticated;
GRANT ALL ON public.favorite_moves TO service_role;
ALTER TABLE public.favorite_moves ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own favorites" ON public.favorite_moves FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users create own favorites" ON public.favorite_moves FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own favorites" ON public.favorite_moves FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE TABLE public.streaks (
  user_id uuid PRIMARY KEY,
  current_streak integer NOT NULL DEFAULT 0 CHECK (current_streak >= 0),
  longest_streak integer NOT NULL DEFAULT 0 CHECK (longest_streak >= 0),
  last_active_date date,
  viewed_move_numbers integer[] NOT NULL DEFAULT '{}',
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.streaks TO authenticated;
GRANT ALL ON public.streaks TO service_role;
ALTER TABLE public.streaks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own streak" ON public.streaks FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users create own streak" ON public.streaks FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own streak" ON public.streaks FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);